gethomepage/homepage

- src/components/widget.jsx
- src/components/widgets/openweathermap/icon.jsx
- src/components/widgets/openweathermap/weather.jsx
- src/pages/api/widgets/openweathermap.js
- src/skeleton/widgets.yaml
- src/utils/owm-condition-map.js
I've little experience with JS, but looks like it's working. Still, please check the math in weather.jsx.
Using [current weather API](https://openweathermap.org/current), condition codes are [here](https://openweathermap.org/weather-conditions).
> Added OpenWeatherMap widget.

- README.md
- src/components/services/widget.jsx
- src/components/services/widgets/service/jellyseerr.jsx
Hello!
Here is the implementation for jellyseerr.
Check it our since I never worked on next.js :D
> Implement Jellyseerr integration

- README.md
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/fr/common.json
- public/locales/it/common.json
- public/locales/nb-NO/common.json
- public/locales/nl/common.json
- public/locales/pt/common.json
- public/locales/ru/common.json
- public/locales/vi/common.json
- public/locales/zh-CN/common.json
- src/components/services/widget.jsx
- src/components/services/widgets/service/readarr.jsx
- src/components/services/widgets/service/sabnzbd.jsx
- src/pages/api/services/proxy.js
- src/utils/api-helpers.js
Hi Ben,
Hopefully this is an appropriate way of submitting new widgets.  I wasn't sure what to do about the translations, and wasn't sure if I should update the README.md as well.
> Add Readarr and SABnzbd widgets

- public/locales/en/common.json
- src/components/services/widget.jsx
- src/components/services/widgets/service/sabnzbd.jsx
- src/components/services/widgets/service/transmission.jsx
- src/pages/api/services/proxy.js
- src/utils/api-helpers.js
- src/utils/http.js
- src/utils/proxies/transmission.js
- Update http.js to support writing request bodies
- Update http.js to support returning all response headers
resolves: #104
> Add transmission widget

- public/locales/en/common.json
- src/components/services/widget.jsx
- src/components/services/widgets/service/bazarr.jsx
- src/pages/api/services/proxy.js
- src/utils/api-helpers.js
> Add Bazarr widget

- public/locales/en/common.json
- src/components/services/widget.jsx
- src/components/services/widgets/service/lidarr.jsx
- src/pages/api/services/proxy.js
- src/utils/api-helpers.js
> Add Lidarr widget

- public/locales/en/common.json
- src/components/services/widget.jsx
- src/components/services/widgets/service/bazarr.jsx
- src/components/services/widgets/service/jackett.jsx
- src/components/services/widgets/service/lidarr.jsx
- src/components/services/widgets/service/qbittorrent.jsx
- src/components/services/widgets/service/readarr.jsx
- src/components/services/widgets/service/sabnzbd.jsx
- src/components/services/widgets/service/transmission.jsx
- src/pages/api/services/proxy.js
- src/utils/api-helpers.js
- src/utils/cookie-jar.js
- src/utils/http.js
- src/utils/proxies/qbittorrent.js
- extract cookie jar functionality into its own file
- use i18n for more strings in existing widgets
associated: #123
completes: #152
> Add qBittorrent Widget

- src/pages/api/services/proxy.js
associated: #180
associated: #194
> Fix issues with incorrect values in widgets

- public/locales/en/common.json
- src/components/services/widget.jsx
- src/components/services/widgets/service/mastodon.jsx
- src/pages/api/services/proxy.js
- src/utils/api-helpers.js
* Added Mastodon service widget
* Also works with some other mastodon-like services like pleroma
> Add Mastodon widget

- .gitignore
- package.json
- pnpm-lock.yaml
- src/pages/api/services/proxy.js
- src/utils/logger.js
- src/utils/proxies/generic.js
- write log data to 'homepage.log'
> Add Winston for log handling

- src/utils/logger.js
This will make it easier for people to find their log file(s)
> Write homepage.log into config folder

- src/components/widgets/search/search.jsx
Chinese search engine with the largest number of users
> support Baidu search engine

- src/components/bookmarks/group.jsx
- src/components/errorboundry.jsx
- src/components/services/group.jsx
- src/components/services/list.jsx
- src/pages/index.jsx
- wrap a myriad of components in ErrorBoundary
- ErrorBoundary errorInfo probably needs styling, or not showing.
resolves #270
> Add ErrorBoundary component

- .github/workflows/docker-publish.yml
- src/pages/_document.jsx
Fix the page auto zoom when ios input focus
> Fix the page auto zoom when ios input focus

- public/locales/en/common.json
- src/widgets/radarr/component.jsx
- src/widgets/radarr/widget.js
> Fix incorrect wanted value in Radarr widget

- src/utils/config/widget-helpers.js
Fixes #423 
For now, as discussed =)
> Fix: some info widgets exempt from cleaning private data

- .github/workflows/docker-publish.yml
See https://github.com/sigstore/cosign/issues/2390 / https://github.com/sigstore/cosign-installer/issues/100
> Update cosign to 1.13.1

- README.md
updated Readme.md to add malay languange into translation list.
> adding malay into translations list

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/diskstation/component.jsx
- src/widgets/diskstation/proxy.js
- src/widgets/diskstation/widget.js
- src/widgets/widgets.js
> Add Synology DiskStation widget

- src/widgets/npm/proxy.js
Fixes #591 
The npm widget token that we cache has an expiration. Like all good APIs they pass the expiration for us to use. Also tweaks error handling in the npm proxy.
> Fix: Add token expiration, tweak error handling for npm

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/flood/component.jsx
- src/widgets/flood/proxy.js
- src/widgets/flood/widget.js
- src/widgets/widgets.js
Add flood widget to homepage (https://github.com/jesec/flood)
> Add flood widget

- src/components/quicklaunch.jsx
Fixes #590 as verified in https://github.com/benphelps/homepage/issues/590#issuecomment-1335994632
Still not really sure of the root case, possibly when using older node version? Anyway, fix is simple
> Fix: unable to build from source on some installs

- src/widgets/plex/proxy.js
> Fix: plex widget error with 1 library

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/nextdns/component.jsx
- src/widgets/nextdns/widget.js
- src/widgets/widgets.js
Adds a simple widget to get the main analytics from the [NextDNS.io API](https://nextdns.github.io/api/), similar to the PiHole widget.
> Adds widget for NextDNS

- .gitignore
- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/mikrotik/component.jsx
- src/widgets/mikrotik/widget.js
- src/widgets/widgets.js
As per issue https://github.com/benphelps/homepage/issues/655, here is a Mikrotik widget for Homepage. 
Configuration is simple : 
- Mikrotik:
icon: mikrotik.png
href: https://192.168.10.206
description: My Mikrotik Router
widget:
type: mikrotik
url: https://192.168.10.206
username: username
password: passwd
> Mikrotik widget

- src/utils/config/api-response.js
- src/utils/config/service-helpers.js
> Fix: remove error on no discovered services

- src/widgets/downloadstation/proxy.js
Co-Authored-By: Benoit SERRA <11260343+Oupsman@users.noreply.github.com>
Big thanks to @Oupsman for providing access to a v6 + v7 instance to test with. Oupsman if you wouldn't mind testing yourself to make sure, this works for me but I think because its a little slow because its so remote I occasionally see a little weirdness. This again uses the logic your code (hence co-author) just reorganized / refactored a bit.
Closes #768
> Fix: Support Synology DownloadStation v6 + v7

- src/utils/proxy/handlers/credentialed.js
- src/widgets/truenas/widget.js
Using an API key is better than username/password and it is easy to generate an API key in TrueNAS.
Documentation updates in https://github.com/benphelps/homepage-docs/pull/18
> Change TrueNAS to use API key

- src/utils/proxy/use-widget-api.js
> Fix: useWidgetAPI refreshInterval not working

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/moonraker/component.jsx
- src/widgets/moonraker/widget.js
- src/widgets/widgets.js
I've added support for displaying prinstatus from Klipper via Moonraker.
To use it:
`type: moonraker`
`url: http://ip.to.your.moonraker:port`
> Add Moonraker (Klipper) widget

- Dockerfile
- docker-entrypoint.sh
Reverts benphelps/homepage#644
Closes #849
> Revert "use unprivileged user in a container"

- src/widgets/proxmox/component.jsx
> Don't include LXC templates in LXC count

- src/widgets/nzbget/component.jsx
> Fix nzbget download rate units

- public/locales/en/common.json
- src/components/quicklaunch.jsx
- src/components/widgets/search/search.jsx
- src/pages/index.jsx
Hey folks. So I've added this little part that adds option to search for item entered to quick launch panel. This is critical to those who needs google for something without moving hands away from keyboard to change focus on search input field. Please let me know if there needs something else to be added.
> Added search to quicklaunch

- src/components/widgets/search/search.jsx
Typo =/
Closes #920 
Closes #921
> Fix search broken in 0.6.5

- src/widgets/proxmoxbackupserver/component.jsx
> Fix label for PBS when data not returned yet

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/mylar/component.jsx
- src/widgets/mylar/widget.js
- src/widgets/widgets.js
Widget is working, this is for request  #898
One note, issues is the total issues available for a series NOT the total issues you own, unfortunately I am not seeing a way to grab that. 
services.yaml
```yaml
widget:
type: mylar
url: http://<mylarhost>
key: apikey
> Mylar widget

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/photoprism/component.jsx
- src/widgets/photoprism/proxy.js
- src/widgets/photoprism/widget.js
- src/widgets/widgets.js
Since I was not able to find a [PhotoPrism](https://photoprism.app/) widget, I made one! PhotoPrism is similar to Immich (widget added in v0.6.4), a user- and privacy-friendly solution to keep your pictures organized and accessible. It is an AI-Powered Photos App that makes use of the latest technologies to tag and find pictures automatically.
```yaml
widget:
type: photoprism
url: http://photoprism.host.or.ip:port
username: admin
password: password
```
Since there is no way of adding limited users, nor API key (yet?), admin user must be used.
See [https://docs.photoprism.app/developer-guide/api/](https://docs.photoprism.app/developer-guide/api/) for details, but this widget uses the following:
```json
{
"config": {
"mode": "user",
"name": "PhotoPrism",
"about": "PhotoPrism® CE", …
```
> Feature: PhotoPrism widget

- src/pages/_app.jsx
- src/styles/custom.css
Reverts benphelps/homepage#904
Honestly don't know what I was thinking. This doesn't work and has been discussed before because CSS gets compiled at buildtime.
Sorry for the space cadet moment
> Revert "feat: Custom CSS"

- src/widgets/components.js
- src/widgets/fileflows/component.jsx
- src/widgets/fileflows/widget.js
- src/widgets/widgets.js
I've added support for displaying info from FileFlows #605.
To use it:
```
type: fileflows
url: http://your.fileflows.ip:5000
```
> Add FileFlows widget

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/grafana/component.jsx
- src/widgets/grafana/widget.js
- src/widgets/widgets.js
> Add grafana widget

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/nextcloud/component.jsx
- src/widgets/nextcloud/widget.js
- src/widgets/widgets.js
I've added support for displaying info from Nextcloud #257 
To use it:
```
- Nextcloud:
icon: nextcloud.png
href: https://your.nextcloud.fqdn
description: Online Collaboration Platform
widget:
type: nextcloud
url: https://your.nextcloud.fqdn
fields: ["cpuload", "memoryusage", "freespace","activeusers", "shares"] //optional
username: your.user.name
password: your.password.or.app.password
```
API output:
<details>
<summary>ocs/v2.php/apps/serverinfo/api/v1/info?format=json</summary>
<br>
```json
{
"ocs": {
"meta": {
"status": "ok",
"statuscode": 200,
"message": "OK"
},
"data": {
"nextcloud": {
"system": {
"version": "25.0.1.1",
"theme": "",
"enable_avatars": "yes",
"enable_previews": "yes",
"memcache.local": "\\OC\\Memcache\\APCu",
"memcache.distributed": "\\OC\\Memcache\\Redis", …
```
> Add Nextcloud widget

- src/widgets/unifi/proxy.js
See #1007 , it seems some (maybe just this person?!) unifi controllers require the csrf-token. Though there's no official documentation the unofficial one implies this isn't needed, and again no one else has reported it but I don't think it will [negatively] affect others ie if there isn't a token at all nothing changes for those users.
Closes #1007 (which should have been left as #1006)
> Fix: pass csrf token for unifi login

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/kopia/component.jsx
- src/widgets/kopia/widget.js
- src/widgets/widgets.js
I've added support for displaying info from Kopia 
To use it:
```
- Kopia:
icon: kopia.png
href: https://your.kopia.ip:51515
description: Backup Management
widget:
type: kopia
url: https://your.kopia.ip:51515
username: your.user.name
password: your.password
```
API output:
<details>
<summary>api/v1/sources</summary>
<br>
```json
{
"localUsername": "root",
"localHost": "root",
"multiUser": true,
"sources": [
{
"source": {
"host": "root",
"userName": "root",
"path": "/appdata"
},
"status": "IDLE",
"schedule": {
"timeOfDay": [
{
"hour": 1,
"min": 0
}
]
},
"lastSnapshot": {
"id": "9cc8d00xxxxxxxx",
"source": {
"host": "root",
"userName": "root",
"path": "/appdata"
},
"description": "",
"startTime": "2023-02-16T22:00:00.002254055Z",
"endTime": "2023-02-16T22:01:49.578911321Z",
"stats": { …
```
> Add Kopia widget

- charts/homepage/Chart.yaml
Fixes typo in version specified for the chart's common library.
> Typo in common lib version

- package.json
- pnpm-lock.yaml
- public/locales/en/common.json
- src/utils/proxy/handlers/minecraft.js
- src/widgets/components.js
- src/widgets/minecraft/component.jsx
- src/widgets/minecraft/proxy.js
- src/widgets/minecraft/widget.js
- src/widgets/widgets.js
Adds a minecraft server status widget
Closes #1042
> Minecraft server status widget

- src/components/quicklaunch.jsx
> Fix: Cannot access qBittorrent from quick launch

- public/locales/en/common.json
- src/widgets/audiobookshelf/component.jsx
- src/widgets/audiobookshelf/proxy.js
- src/widgets/audiobookshelf/widget.js
- src/widgets/components.js
- src/widgets/widgets.js
Does require a custom proxy, unfortunately, due to API structure.
Closes #525
> Add audiobookshelf widget

- public/locales/en/common.json
- src/components/services/status.jsx
- src/widgets/homebridge/component.jsx
> Fix: Add translation for some missing items

- src/components/widgets/glances/glances.jsx
- src/components/widgets/resources/cputemp.jsx
> Fix glances cpu temp detection & fahrenheit conversion

- src/components/widgets/resources/memory.jsx
> Fix memory display in v0.6.11

- src/widgets/emby/component.jsx
> Fix emby/jellyfin now playing > 1

- src/components/services/group.jsx
For [2xl e.g. > 1536px](https://tailwindcss.com/docs/screens)
Closes #987
> Add 5th column for 2xl screens

- src/components/services/group.jsx
- src/pages/index.jsx
> Move 5th column behind setting

- src/components/services/ping.jsx
- src/pages/api/ping.js
The more I think about it, accepting 401/403 seems acceptable.
Closes #1239
> Accept http 401 / 403 for ping

- src/widgets/prowlarr/component.jsx
> Fix grabs data for Prowlarr

- src/pages/api/docker/stats/[...service].js
- src/pages/api/docker/status/[...service].js
Bug fix: Correct handling of docker multiple names
> solving docker multiple names

- public/locales/en/common.json
- public/locales/sl/common.json
- src/utils/proxy/handlers/credentialed.js
- src/widgets/components.js
- src/widgets/tailscale/component.jsx
- src/widgets/tailscale/widget.js
- src/widgets/widgets.js
This change introduces the new Tailscale widget that pulls stats from Tailscale's API.
The user will be able to add the widget to the `services.yaml` file using the following configuration:
```yaml
widget:
type: tailscale
deviceid: deviceid
key: tailscaleapikey
```
The Tailscale API is documented here:
https://github.com/tailscale/tailscale/blob/main/api.md#device
You can create an API access token on this page:
https://login.tailscale.com/admin/settings/keys
To find your device ID go to the Machines page:
https://login.tailscale.com/admin/machines
Select your machine, scroll down to "Machine Details" and copy the `ID`
The API request would look like this:
```http
GET https://api.tailscale.com/api/v2/device/xxxxx
Authorization: Bearer tskey-api-xxxxx
```
The API response would like this …
> Add Tailscale Widget

- public/locales/en/common.json
- src/widgets/caddy/component.jsx
- src/widgets/caddy/widget.js
- src/widgets/components.js
- src/widgets/widgets.js
> Implement Caddy widget

- src/pages/api/ping.js
> Fix: Add try catch for ping

- src/utils/proxy/http.js
Relates to [this comment/discussion](https://github.com/benphelps/homepage/discussions/951#discussioncomment-4913916). Older version of deluge (1.x) always gzipped its api responses, so attempting to parse the body would fail. This PR adds support to the httpProxy for decompressing the upstream gzip or deflate encoded content.
Tip for testing: deluge 2.x respects the accept-encoding header, so adding `"accept-encoding": "gzip"` to the [request headers](https://github.com/benphelps/homepage/blob/c1a68a79ee40cc7830c508197f88e0ea1ec77d8d/src/utils/proxy/handlers/jsonrpc.js#L12-L15) will cause it to gzip its responses.
> Support proxying compressed responses

- src/utils/config/service-helpers.js
Closes #1606 (issue)
Updates the Traefik API endpoint. [Traefik Migration Documentation](https://doc.traefik.io/traefik/migration/v2/#kubernetes-crds)
> Update Traefik API

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/jdownloader/component.jsx
- src/widgets/jdownloader/proxy.js
- src/widgets/jdownloader/tools.js
- src/widgets/jdownloader/widget.js
- src/widgets/widgets.js
Working jdownloader service widget, now not using any modules.
Closes #1232 
https://github.com/benphelps/homepage-docs/pull/113
> Working Jdownloader

- public/locales/en/common.json
- src/widgets/jdownloader/component.jsx
- src/widgets/jdownloader/proxy.js
Have updated the widget to show the Total Queue Size as well as the Queue Size Remainig
> JDownloader Widget - Add Total Queue and Remaining In Queue

- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/kavita/component.jsx
- src/widgets/kavita/proxy.js
- src/widgets/kavita/widget.js
- src/widgets/widgets.js
> Adding Kavita

- src/components/bookmarks/group.jsx
- src/pages/index.jsx
> Feature: add collapsible feature to bookmarks

- src/components/widgets/logo/logo.jsx
> Fixes oversized logo in 0.6.22

- src/components/widgets/glances/glances.jsx
- src/components/widgets/openmeteo/icon.jsx
- src/components/widgets/openmeteo/openmeteo.jsx
- src/components/widgets/openweathermap/icon.jsx
- src/components/widgets/openweathermap/weather.jsx
- src/components/widgets/weather/icon.jsx
- src/components/widgets/weather/weather.jsx
- src/components/widgets/widget/widget_icon.jsx
> Fix more errors from PR #1603

- src/components/widgets/glances/glances.jsx
> Fix: Handle cpu sensors without `warning` property

- src/components/widgets/resources/resources.jsx
> Fix: default resources refresh rate

- src/widgets/urbackup/component.jsx
- src/widgets/urbackup/proxy.js
> Fix: Handle urbackup clients with images disabled

- src/widgets/octoprint/component.jsx
> Fix jobStats potentially accessed before instantiated

- src/widgets/emby/component.jsx
> Fix: support streaming media from jellyfin

- src/components/quicklaunch.jsx
- src/pages/index.jsx
Fixes quick launch on boxed header, some small focus issues. Yet another related to https://github.com/benphelps/homepage/pull/1603 🫤
Closes #1878
> Fix location of quicklaunch, some focus issues

- src/widgets/glances/metrics/fs.jsx
> fix linting

- src/components/services/item.jsx
> Fix: remove pointer events on ping div

- src/widgets/jdownloader/proxy.js
> Fix JDownloader Remaining

- src/components/widgets/glances/glances.jsx
> Enhancement: Support disable glances cpu + mem

- src/pages/api/ping.js
- src/utils/proxy/cookie-jar.js
- src/utils/proxy/handlers/generic.js
Reverts benphelps/homepage#1804
Closes #1938
> Revert "Forward cookies from request"

- src/pages/index.jsx
Fix for layout issue
Closes #1988
> Fix for broken layout when layout is not defined

- src/pages/index.jsx
> Fix: custom.js not working

- src/utils/config/service-helpers.js
> Fix k8s traefikingresslist detection

- src/components/bookmarks/item.jsx
This PR adds an optional `description` setting in `bookmarks.yaml` which defaults to hostname (current behavior) if not defined.
This would also allow to replace too long hostnames which would break the layout (ie. Unraid URLs: `https://192-168-100-100.0123456789abcdef0123456789abcdef01234567.myunraid.net/Docker`)
```yaml
- Home Server:
- Docker:
- icon: docker
href: https://192-168-100-100.0123456789abcdef0123456789abcdef01234567.myunraid.net/Docker
description: Unraid@Home
```
> Enhancement: add bookmark description option

- public/locales/de/common.json
- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/opendtu/component.jsx
- src/widgets/opendtu/widget.js
- src/widgets/widgets.js
Adds an OpenDTU Widget (as discussed in https://github.com/benphelps/homepage/discussions/2055)
Closes https://github.com/benphelps/homepage/discussions/2055
> Add OpenDTU Widget

- .github/workflows/docker-publish.yml
- .github/workflows/docs-publish.yml
Currently `main` branch in fork tries to deploy the docs and fails with:
```
Collecting git+https://****@github.com/benphelps/mkdocs-material-insiders.git
Cloning https://****@github.com/benphelps/mkdocs-material-insiders.git to /tmp/pip-req-build-p4vf9vd8
Running command git clone --filter=blob:none --quiet 'https://****@github.com/benphelps/mkdocs-material-insiders.git' /tmp/pip-req-build-p4vf9vd8
fatal: could not read Username for 'https://github.com/': No such device or address
error: subprocess-exited-with-error
× git clone --filter=blob:none --quiet 'https://****@github.com/benphelps/mkdocs-material-insiders.git' /tmp/pip-req-build-p4vf9vd8 did not run successfully.
│ exit code: 128
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem …
```
> Fix: Skip workflows if it is fork

- .github/workflows/docs-publish.yml
- docs/widgets/services/calendar.md
> Documentation: update docs ci test vs build, add tip to calendar docs

- .github/workflows/docker-publish.yml
- .github/workflows/docs-publish.yml
> CI: Filter ci actions by path

- public/locales/en/common.json
- src/components/services/kubernetes-status.jsx
- src/components/services/ping.jsx
> Fix: dot visibility in some cases, translation strings

- docs/widgets/services/gluetun.md
Fixed link to control server documentation
This fixes a link to point to the new gluetun wiki documentation
> Documentation: update gluetun documentation link

- src/widgets/docker/stats-helpers.js
> Fix calculation for docker container memory usage

- src/widgets/glances/metrics/fs.jsx
> Fix glances fs metric for disks with colon

- docs/installation/k8s.md
> Fix: Update k8s deployment with specific files

- src/widgets/proxmox/component.jsx
> fix for proxmox CPU/MEM when cluster has offline nodes

- src/widgets/glances/metrics/net.jsx
See https://github.com/nicolargo/glances/issues/1704#issuecomment-673510389
Also swapped the order just to be consistent with glances
Closes #2200
> Fix glances network calculation

- src/components/services/kubernetes-status.jsx
- src/components/services/status.jsx
- tailwind.config.js
> Fix: dot status when exited

- docs/configs/docker.md
- package-lock.json
- package.json
- pnpm-lock.yaml
- src/utils/config/service-helpers.js
- src/utils/config/shvl.js
When [0.6.29](https://github.com/gethomepage/homepage/releases/tag/v0.6.29) with feature [CustomAPI](https://github.com/gethomepage/homepage/pull/1858) was released, It configure only in YAML file but invalid in docker tags.
Docker tags for example:
```yaml
labels:
- homepage.group=Media
- homepage.name=Emby
- homepage.icon=emby.png
- homepage.href=http://emby.home/
- homepage.description=Media server
- homepage.widget.type=customapi
- homepage.widget.url=http://argus.service/api/v1/service/summary/emby
- homepage.widget.field[0].label=Deployed Version
- homepage.widget.field[0].field.status=deployed_version
- homepage.widget.field[1].label=Latest Version
- homepage.widget.field[1].field.status=latest_version
```
API response:
```json
{
"id": "emby",
"type": "github",
"status": { …
```
> Enhancement: support dot-notated field properties in customapi widget

- docs/configs/kubernetes.md
- src/pages/api/kubernetes/stats/[...service].js
- src/pages/api/kubernetes/status/[...service].js
- src/utils/config/service-helpers.js
> Enhancement: Support k8s `app` IngressRoute annotation

- src/utils/proxy/http.js
> Change: Enable `autoSelectFamily` for http(s) requests

- README.md
- docs/configs/service-widgets.md
- docs/configs/settings.md
- docs/widgets/info/openweathermap.md
- docs/widgets/info/resources.md
- docs/widgets/info/weather.md
- docs/widgets/services/azuredevops.md
- docs/widgets/services/customapi.md
- docs/widgets/services/glances.md
- docs/widgets/services/pihole.md
This pull request addresses minor issues in the documentation by fixing typos and enhancing language coherence. The changes aim to improve the overall clarity and readability of the documentation for a better user experience.
Please review my PR. Thank you for your time and consideration.
> docs: fix typos and improve language coherence

- src/widgets/octoprint/component.jsx
> Fix: octoprint error when progress empty

- src/widgets/downloadstation/component.jsx
> Fix: Synology DownloadStation units

- src/widgets/docker/stats-helpers.js
Fixes https://github.com/gethomepage/homepage/issues/2271
Closes #2271
> Fix: container memory_stats in podman

- src/widgets/unifi/proxy.js
> Fix: support Unifi widget with Unifi OS v3.2.5+

- src/widgets/immich/component.jsx
- src/widgets/immich/widget.js
> Fix: handle immich v1.85.0 breaking change

- docs/configs/settings.md
> Documentation: fix typo

- src/styles/theme.css
> Fix: Disable override white bkgd with card blur

- .babelrc
- next.config.js
> Chore: re-enable swc

- src/utils/config/service-helpers.js
> Fix: dont ignore empty string for kubernetes podSelector

- docs/widgets/services/calendar.md
- src/utils/config/service-helpers.js
- src/widgets/calendar/agenda.jsx
> Feature: Support previous days option in Calendar Agenda

- docs/configs/docker.md
- docs/scripts/extra.js
- mkdocs.yml
> Documentation: Add ai bot

- next.config.js
This partially reverts commit 90c12abf87f6949a4fc689b9f6bfeff4f0260b95.
> Chore: enable swc, again

- docs/widgets/services/iframe.md
The value of allowPolicy is used directly in the attribute. So I added a semicolon to the example code.
Without the semicolon, fullscreen didn't work.
> Added semicolons to the example code

- docs/widgets/services/calibre-web.md
Updating docs to reflect that the API endpoint used by this widget has now been released in a stable release, and is also present in latest stable lsio builds.
> Update minimum calibre-web version reference

- .github/workflows/crowdin.yml
- crowdin.yml
> Chore: migrate crowdin to GHA

- src/pages/api/kubernetes/stats/[...service].js
> Fix: Increase kubernetes cpu/mem usage scale

- next-i18next.config.js
- public/locales/en/common.json
- src/components/widgets/resources/uptime.jsx
- src/widgets/fritzbox/component.jsx
- src/widgets/uptimerobot/component.jsx
> Chore: Unify uptime formatting

- src/widgets/peanut/component.jsx
> Fix: Peanut widget v2 api compatibility

- src/utils/config/service-helpers.js
> Change: better handle malformed docker labels

- src/components/quicklaunch.jsx
- src/components/services/list.jsx
> Fix: unique element key generation in quicklaunch and services

- src/widgets/calendar/monthly.jsx
> Fix: sort ical events in monthly view

- src/utils/config/service-helpers.js
> Fix configured service weight = 0

- src/components/widgets/resources/usage-bar.jsx
A bit absurd, but sure
Closes #2649
> Fix: constrain usage bar percentage between 0 and 100

- src/widgets/calendar/integrations/ical.jsx
> Fix: Calendar widget iCal integration catch RRule failures

- docs/widgets/services/coin-market-cap.md
> Documentation: fix typo in coin-market-cap widget docs

- src/utils/config/service-helpers.js
> Fix broken docker service discovery in v0.8.5

- docs/widgets/services/gluetun.md
Fix a spelling issue in the page for the Gluetun service widget.
> Documentation: fix gluetun typo

- src/widgets/unifi/component.jsx
> Unifi widget: Show a more helpful error if specified site not found

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
Here the new PR adding the Python requirements and prettier to the devcontainer.
Sorry again for messing up.
> Chore: add Python requirements and prettier to devcontaier

- src/pages/index.jsx
> Change: use Script component instead of async script for custom.js

- docs/widgets/services/gitea.md
- mkdocs.yml
- public/locales/en/common.json
- src/utils/proxy/api-helpers.js
- src/widgets/components.js
- src/widgets/gitea/component.jsx
- src/widgets/gitea/widget.js
- src/widgets/widgets.js
> Feature: add gitea widget

- src/pages/api/search/searchSuggestion.js
- src/utils/proxy/cached-fetch.js
> Fix: Google search suggestions with accented characters

- .github/workflows/repo-maintenance.yml
- CONTRIBUTING.md
> Documentation: repository typo

- docs/widgets/services/openwrt.md
Add missing comma to homepage.json file + update format to json
Add guidance on creating strong hashed password (advice from OpenWRT community developer)
Correct /etc/config/rpc to /etc/config/rpcd
Remove extra privelage permission from rpcd
Closes #3012
> Documentation: fix openwrt docs

- docs/widgets/services/tandoor.md
- public/locales/en/common.json
- src/utils/proxy/handlers/credentialed.js
- src/widgets/components.js
- src/widgets/tandoor/component.jsx
- src/widgets/tandoor/widget.js
- src/widgets/widgets.js
Add a [Tandoor](https://github.com/TandoorRecipes/recipes) service widget. Returns information (recipe number, user count, keyword count) for the active recipe space. I mostly copied the Mealie widget with modifications. 
Examples
This widget uses the `/space` and `/keyword` API endpoints. A space is like a shared cookbook which can have multiple users - recipes must be placed into a space. I could not find a single API call to return number of users, recipe count, and keywords in one call. The `/space` endpoint returns a singleton list of the active patient space with the user_count and recipe_count properties. The `/keyword` endpoint returns the active space's keywords with the `count` property.
The information should update upon switching to a new space.
These are the API calls
Closes …
> Feature: Add tandoor widget

- docs/configs/settings.md
This was a super minor typo 😀 I feel bad making a whole pull request for this but spelling triggers me
> Very minor typo in docs

- docs/widgets/services/gitea.md
Added `issue` permissions as a requirement. The widget does not appear to work unless `issue` permissions are also granted.
> Documentation: note that "issue" permissions are also required for Gitea widget

- src/components/tab.jsx
- src/pages/index.jsx
> Fix: correctly handle direct tab navigation with encoded chars

- docs/widgets/services/crowdsec.md
- mkdocs.yml
- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/crowdsec/component.jsx
- src/widgets/crowdsec/proxy.js
- src/widgets/crowdsec/widget.js
- src/widgets/widgets.js
Only thing is these payloads can get large because the crowdsec API returns huge decision lists with the alerts, for some reason.
Closes #2840
> Feature: crowdsec widget

- docs/widgets/services/pihole.md
- src/utils/config/service-helpers.js
- src/widgets/pihole/component.jsx
- src/widgets/pihole/proxy.js
- src/widgets/pihole/widget.js
v6 is still in beta and its a very-breaking change, but figured I'd put in the work now, we can keep an eye if things change before the actual release.
Closes #3168
> Feature: support pihole v6

- .github/PULL_REQUEST_TEMPLATE.md
> Chore: Fix a Typo in the PR Template

- README.md
I came across this repo and wanted to check how to use the docker service discovery. But the link in the Readme is confusing.  Why does the link in the `Docker Integration` section point to the `Docker Installation` [link ](https://gethomepage.dev/latest/installation/docker/) that should belong to the `Getting Started -> With Docker` part. I'm trying to make it more clear by raising this PR :) 
Hope it's at least a little helpful and thanks for this wonderful project!
> Documentation: correct link for Docker automatic service discovery 

- src/components/widgets/widget/container_form.jsx
Even though I cant reproduce it, this is an invalid attribute so no reason to keep it.
Closes #3149
> Fix: remove invalid form attribute

- docs/widgets/services/azuredevops.md
- docs/widgets/services/crowdsec.md
- docs/widgets/services/gitea.md
- docs/widgets/services/peanut.md
- docs/widgets/services/prometheus.md
- docs/widgets/services/pterodactyl.md
Address small documentation fixes. 
Closes no issue, but I can open one if required
> Documentation: fix allowed fields uniformity

- docs/widgets/services/diskstation.md
Replaced phrases related to Download Station with DSM. Made clear that DiskStation is presented as DSM in the admin panel. Added step in issues area. Logging into Synology with new user account solved API error.
> Documentation: update diskstation instructions

- docs/widgets/services/uptime-kuma.md
Took me a while to figure this out, so here's a small clarification that can same a lot of time.
> Documentation: clarify uptime kuma slug

- src/utils/proxy/api-helpers.js
- src/utils/proxy/http.js
> Fix some unsanitized error URLs

- docs/widgets/services/channelsdvrserver.md
I found an IP left in this widget's example YAML, so I removed it and replaced it with the style of placeholder usually used on the other widget pages.
> Documentation: generic server url for channels script widget docs

- src/widgets/ghostfolio/component.jsx
> Fix: handle ghostfolio v2.79.0 breaking API changes

- src/widgets/kubernetes/component.jsx
> Fix: handle some status cases with non-existent k8s pods

- README.md
- docs/index.md
Required for getting DO Open Source Credits.
> Documentation: DO Credits

- docs/widgets/services/swagdashboard.md
- mkdocs.yml
- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/swagdashboard/component.jsx
- src/widgets/swagdashboard/widget.js
- src/widgets/widgets.js
Added a widget for [SWAG Dashboard](https://github.com/linuxserver/docker-mods/tree/swag-dashboard) as requested by our SWAG users.
> Feature: SWAG dashboard widget

- src/widgets/glances/widget.js
> Fix: glances cpu metric broken in v0.9.0

- src/widgets/omada/component.jsx
- src/widgets/omada/widget.js
> Fix: omada widget broken in v0.9.1

- src/components/quicklaunch.jsx
> Fix: dont force lowercase URL in QuickLaunch

- docs/widgets/services/myspeed.md
- mkdocs.yml
- public/locales/en/common.json
- src/utils/proxy/handlers/credentialed.js
- src/widgets/components.js
- src/widgets/myspeed/component.jsx
- src/widgets/myspeed/widget.js
- src/widgets/widgets.js
This PR implements the [MySpeed](http://github.com/gnmyt/myspeed) widget (Feature Request #3514).
Closes #3514
Closes https://github.com/gnmyt/myspeed/issues/614
> Feature: MySpeed widget

- src/widgets/truenas/component.jsx
> Fix: Sort truenas pools by name

- src/utils/proxy/validate-widget-data.js
> Enhancement: strip whitespace when checking JSON

- docs/widgets/services/pfsense.md
- src/utils/config/service-helpers.js
- src/widgets/pfsense/component.jsx
- src/widgets/pfsense/widget.js
Best effort based on https://github.com/gethomepage/homepage/discussions/3713#discussioncomment-9981740
Closes #3713
> Enhancement: support pfsense v2 api

- src/pages/api/kubernetes/status/[...service].js
> Fix: correct k8s service status check

- src/widgets/truenas/widget.js
> Change: handle errored truenas pools

- src/widgets/wgeasy/component.jsx
- src/widgets/wgeasy/proxy.js
Also reverts #3768
I should have looked at #3768 more carefully, error should be handled by the proxy.
> Fix: properly handle wg-easy errors

- package-lock.json
- package.json
- pnpm-lock.yaml
> Chore: update gamedig to 5.1.2

- src/widgets/wgeasy/proxy.js
> Enhancement: use password header for reliable wg-easy widget

- docs/widgets/services/watchtower.md
> Documentation: Fix watchtower typo

- src/widgets/nzbget/widget.js
> Fix: jsonrpchandler requires mappings

- src/widgets/proxmoxbackupserver/component.jsx
> Fix: handle proxmoxbackupserver without datastore

- src/widgets/ghostfolio/component.jsx
> Enhancement: support another ghostfolio API breaking change

- docs/widgets/services/mailcow.md
- public/locales/de/common.json
- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/mailcow/component.jsx
- src/widgets/mailcow/widget.js
- src/widgets/widgets.js
Implement a widget for [Mailcow](https://github.com/mailcow/mailcow-dockerized).
Closes https://github.com/gethomepage/homepage/discussions/3548
> Feature: mailcow widget

- docs/widgets/services/pihole.md
- src/widgets/pihole/proxy.js
> Enhancement: support pihole v6 with api auth disabled

- src/widgets/mikrotik/widget.js
Should be fine since all the widget does is count the items
Closes #3994
> Enhancement: reduce properties retrieved from mikrotik endpoint

- docs/configs/services.md
The address changed to: https://pictogrammers.com/library/mdi/
> Documentation: update mdi link

- docs/widgets/services/photoprism.md
- src/widgets/photoprism/proxy.js
> Enhancement: support photoprism app passwords

- docs/widgets/services/index.md
- docs/widgets/services/lubelogger.md
- public/locales/en/common.json
- src/utils/config/service-helpers.js
- src/widgets/components.js
- src/widgets/lubelogger/component.jsx
- src/widgets/lubelogger/widget.js
- src/widgets/widgets.js
> Feature: LubeLogger service widget

- src/components/bookmarks/item.jsx
> Fix: add noreferrer to bookmark links

- src/widgets/npm/component.jsx
- src/widgets/npm/proxy.js
> Enhancement: npm widget support ≥ v2.12

- docs/widgets/services/zabbix.md
Just fixing a typo in a description.
> Documentation: fix typo in zabbix doc

- docs/widgets/services/lubelogger.md
Added missing characters to LubeLogger widget documentation to fix broken `code` block.
> Documentation: Typo in LubeLogger widget documentation

- src/widgets/pyload/proxy.js
> Fix: pyload widget - encode proxy params

- docs/widgets/authoring/translations.md
- next-i18next.config.js
- public/locales/en/common.json
- src/components/widgets/resources/uptime.jsx
- src/widgets/audiobookshelf/component.jsx
- src/widgets/frigate/component.jsx
- src/widgets/fritzbox/component.jsx
- src/widgets/openwrt/methods/system.jsx
- src/widgets/stash/component.jsx
- src/widgets/truenas/component.jsx
- src/widgets/uptimerobot/component.jsx
> Enhancement: use duration for audiobookshelf tottal, refactor uptime

- docs/widgets/services/beszel.md
- docs/widgets/services/index.md
- mkdocs.yml
- public/locales/en/common.json
- src/utils/config/service-helpers.js
- src/widgets/beszel/component.jsx
- src/widgets/beszel/proxy.js
- src/widgets/beszel/widget.js
- src/widgets/components.js
- src/widgets/widgets.js
For now, given the relative youth of the project we'll only use a beszel service widget
Closes #3776
> Feature: Beszel service widget

- src/components/quicklaunch.jsx
> Enhancement: quicklaunch fill search suggestion on arrowright

- docs/widgets/services/opnsense.md
Amend OPNSense widget documentation page, specifically the section on effective privileges that need to be selected for API calls to return data. It appears that in the 24.7.x release, the "Status: Traffic Graph" privilege is no longer present. However, this appears to have been replaced / is covered by the Reporting: Traffic privilege grouping, which covers the /api/diagnostics/traffic/* endpoint(s). I am submitting a proposed documentation change to identify the Reporting: Traffic privilege as the correct one to select with newer versions of OPSense.
Not clear of exactly the best / correct way to reflect this in the documentation, but proposed what I felt may work.
*Note: I tested this privilege selection on my own OPNSense 24.7.8 installation as I was unable to find the Status: Traffic …
> Documentation: Update opnsense.md privileges section for OPNSense 24.7.x

- src/utils/proxy/handlers/generic.js
> Enhancement: allow widgets to specify default headers, fix buffer error output

- src/components/services/group.jsx
- src/components/services/item.jsx
- src/components/services/list.jsx
- src/components/services/ping.jsx
- src/components/services/site-monitor.jsx
- src/pages/api/ping.js
- src/pages/api/siteMonitor.js
- src/pages/index.jsx
- src/utils/config/api-response.js
- src/utils/config/service-helpers.js
Get ready for some crazy layouts. Would be good to get some testing in the wild.
With yaml as you would expect:
```yaml
- Testing Nested:
- Radarr:
...
widget:
type: radarr
...
- Plex:
...
widget:
type: plex
...
- Nested A:
- Gitlab:
...
widgets:
- type: gitlab
...
- Pihole:
...
widgets:
- type: pihole
...
- Nested B:
- Lubelogger:
...
widgets:
- type: lubelogger
...
- Stocks:
description: stocks
widget:
type: stocks
...
- Nested B1:
- Unifi:
...
widgets:
- type: unifi
...
- Sonarr:
...
widgets:
- type: sonarr
...
- Nested B2:
- Multiwidget:
widgets:
- type: uptimerobot
...
- type: homebridge
...
```
and layout:
```yaml
layout:
Testing Nested:
style: row
columns: 2
icon: mdi-test-tube
Nested A:
icon: mdi-alpha-a
Nested B:
style: row
columns: 2
icon: mdi-alpha-b
Nested B1:
icon: …
```
> Feature: nested groups

- src/pages/index.jsx
> Use theme context, scheme tailwind utilities

- docs/widgets/services/glances.md
- src/widgets/glances/component.jsx
- src/widgets/glances/metrics/containers.jsx
- src/widgets/glances/widget.js
> Enhancement: glances containers metric widget

- docs/widgets/services/evcc.md
- public/locales/en/common.json
- src/widgets/evcc/component.jsx
> Fix: correct evcc units

- docs/installation/k8s.md
Add new Traefik V3 API version.
> Documentation: update k8s.md to Reflect New Traefik V3 API

- src/utils/proxy/handlers/synology.js
See https://github.com/gethomepage/homepage/pull/4411#issuecomment-2541888059
> Enhancement: encode uri params for synology proxy

- src/components/widgets/stocks/stocks.jsx
> Enhancement: better display of finnhub tickers with exchange

- src/utils/config/api-response.js
- src/utils/config/service-helpers.js
> Fix: dont discard service groups not included in layout

- src/styles/globals.css
- src/widgets/glances/components/container.jsx
- src/widgets/glances/metrics/process.jsx
> Tweak: adjust chart height

- src/widgets/glances/components/container.jsx
- src/widgets/glances/metrics/process.jsx
> Fix: chart heights in 0.10.x

- src/utils/config/service-helpers.js
> Chore: warn and dont fail for invalid services

- src/styles/globals.css
- src/widgets/glances/components/chart.jsx
- src/widgets/glances/components/chart_dual.jsx
- src/widgets/glances/components/container.jsx
- src/widgets/glances/metrics/fs.jsx
- src/widgets/glances/metrics/info.jsx
- src/widgets/glances/metrics/process.jsx
> Tweak: again trying to restore chart sizing in 0.10.x

- src/components/services/group.jsx
- src/components/services/list.jsx
> Fix: fun with padding and margins

- docs/widgets/services/beszel.md
- src/widgets/beszel/component.jsx
> Enhancement: support 'nice name' for beszel system ID

- src/widgets/glances/metrics/containers.jsx
> FIx: glances containers header position

- src/widgets/gluetun/widget.js
> Change: make region optional for gluetun api response

- docs/configs/settings.md
- src/pages/_document.jsx
- src/pages/index.jsx
> Feature: meta description setting

- src/widgets/calendar/monthly.jsx
> Fix: incorrect weekyear for events

- src/widgets/glances/metrics/fs.jsx
> Fix: better fs height

- src/pages/index.jsx
> Fix: toggle light / dark makes background white

- docs/widgets/services/gluetun.md
Small documentation update as we can  need to make sure the route Homepage uses is allowed
> Documentation: update gluetun apikey config instructions

- src/components/widgets/search/search.jsx
Some kind of breaking change in react-icons, unintended perhaps
Closes #4565
> Fix: fix bing search logo

- src/widgets/evcc/component.jsx
> Fix: handle evcc breaking change

- .github/workflows/docker-publish.yml
> Development: pnpm lint on ci

- docs/widgets/services/firefly.md
- docs/widgets/services/index.md
- mkdocs.yml
- public/locales/en/common.json
- src/utils/proxy/handlers/credentialed.js
- src/widgets/components.js
- src/widgets/firefly/component.jsx
- src/widgets/firefly/widget.js
- src/widgets/widgets.js
Created widget for [Firefly III](https://www.firefly-iii.org)
> Image of the demo profile
Closes #3598 (issue)
> Feature: Firefly widget

- package-lock.json
- package.json
This PR just increments the homepage version in package.json.
> Fix: correct package version number

- docs/widgets/services/speedtest-tracker.md
- src/utils/config/service-helpers.js
- src/utils/proxy/handlers/credentialed.js
- src/widgets/speedtest/component.jsx
- src/widgets/speedtest/widget.js
> Enhancement: support speedtest v1.2 API

- src/widgets/prometheus/widget.js
> Enhancement: filter prometheus API endpoint for active only

- src/utils/config/api-response.js
- src/utils/config/service-helpers.js
> Fix nesting with unsorted groups

- src/widgets/truenas/component.jsx
- src/widgets/truenas/pool.jsx
- src/widgets/truenas/widget.js
> Enhancement: use datasets for truenas pools

- docs/installation/docker.md
- docs/installation/source.md
- src/middleware.js
- src/pages/index.jsx
> [BREAKING] Enhancement: require host validation

- src/widgets/calendar/integrations/ical.jsx
> Enhancement: better tz parsing of ical recurring events

- src/utils/kubernetes/resource-helpers.js
No issue created. Discussed [here](https://github.com/gethomepage/homepage/discussions/4021#discussioncomment-12182907).
> Fix: handle possible null reference in k8s gateway api

- src/utils/proxy/api-helpers.js
> Enhancement: improve try to prune trailing slashes

- docs/widgets/services/kavita.md
- src/widgets/kavita/proxy.js
> Enhancement: support API key for Kavita

- src/widgets/calendar/integrations/ical.jsx
> Enhancement: better handle recurring events poorly handled by ical library

- docs/widgets/info/unifi_controller.md
- docs/widgets/services/unifi-controller.md
- src/utils/config/service-helpers.js
- src/utils/config/widget-helpers.js
- src/widgets/unifi/proxy.js
> Enhancement: support new unifi network api and api key

- public/locales/en/common.json
- src/widgets/omada/component.jsx
> Fix: correct omada widget connectedGateways

- docs/widgets/services/komga.md
- src/utils/config/service-helpers.js
- src/utils/proxy/cookie-jar.js
- src/widgets/komga/component.jsx
- src/widgets/komga/proxy.js
- src/widgets/komga/widget.js
Closes https://github.com/gethomepage/homepage/discussions/4126
> Enhancement: support komga API keys, breaking API changes

- src/pages/api/widgets/kubernetes.js
> Fix: fix k8s get nodes error log

- src/utils/config/api-response.js
Closes #4867 (and others I think)
> Enhancement: support automatic service discovery services with layout-only nesting

- src/widgets/plex/proxy.js
> Chore: add plex container size to requests

- docs/configs/settings.md
- src/components/version.jsx
- src/pages/api/releases.js
- src/pages/index.jsx
> Feature: cache release data, allow disable release checking

- src/components/services/group.jsx
- tailwind.config.js
> Fix: fix fiveColumns option

- src/widgets/plex/proxy.js
> Fix: fix plex total size with larger libraries

- src/components/services/group.jsx
- src/styles/globals.css
> Fix: fix larger breakpoint

- src/components/bookmarks/item.jsx
> Fix: wrapping in bookmarks

- src/widgets/kavita/proxy.js
> Fix: fix kavita API body with key

- Dockerfile
- src/middleware.js
> Change: prefer IPv4 in docker image

- docs/installation/index.md
- src/middleware.js
> Enhancement: allow disabling host header checking

- package.json
- pnpm-lock.yaml
> Chore: update minecraftstatuspinger to 1.2.2

- src/pages/api/kubernetes/stats/[...service].js
> Fix: fix Kubernetes stats in v1.0.0

- src/components/bookmarks/item.jsx
Closes #4995
Closes https://github.com/gethomepage/homepage/discussions/4944 (again)
Supersedes #4989
> Fix: fix bookmark heights again

- src/pages/api/search/searchSuggestion.js
> Fix: fix custom quicklaunch search without search widget

- src/widgets/medusa/widget.js
> Fix: remove medusa widget trailing slash

- src/widgets/minecraft/proxy.js
Closes https://github.com/gethomepage/homepage/discussions/4979#discussioncomment-12525971
> Fix: fix minecraft players after move to minecraftstatuspinger

- docs/widgets/services/customapi.md
- src/widgets/customapi/component.jsx
This pull request is an implementation of the following feature request: https://github.com/gethomepage/homepage/discussions/4906
As my engineering background is not in web, I used Cursor to assist me. I thoroughly checked its output and tested the new feature with a mock api. If anything has to change, please let me know!
> Enhancement: support dynamic list rendering in custom api widget

- docs/widgets/services/customapi.md
- src/widgets/customapi/component.jsx
Probably should've been like this from the beginning
> Enhancement: support shvl syntax for customapi fields

- docs/configs/settings.md
- src/pages/index.jsx
> Enhancement: support full width container

- docs/configs/settings.md
- src/pages/_app.jsx
> Fix: include new backdrop-blur-xs option

- docker-entrypoint.sh
> Tweak: try to reduce rootless startup time

- docs/widgets/services/index.md
- docs/widgets/services/slskd.md
- public/locales/en/common.json
- src/widgets/components.js
- src/widgets/slskd/component.jsx
- src/widgets/slskd/widget.js
- src/widgets/widgets.js
This PR adds a widget for [Slskd](https://github.com/slskd/slskd), which is a client-server application that connects to the Soulseek file sharing network.
There are 5 options for fields (and room for future updates to add more options), however only 4 are allowed at any one time.
Closes #4200
> Feature: Slskd Service Widget

- src/widgets/customapi/component.jsx
> Enhancement: add shvl fallback for custom api dynamic list

- docs/widgets/services/proxmoxbackupserver.md
Added some more infos on how to add user/token.
> Documentation: add info re proxmox backup server key

- Dockerfile
> Change: install iputils-ping inside docker image

- docs/configs/kubernetes.md
Update Gateway API HttpRoute support documentation to give better guidance on configuration.
Closes # N/A
> Documentation: update Gateway API HttpRoute documentation

- docs/widgets/services/gamedig.md
- src/utils/config/service-helpers.js
- src/widgets/gamedig/proxy.js
Refactor to include optional 'token' key to provide an authorization code to some services that may require it to function fully.
> Enhancement: add optional token parameter for gamedig

- src/utils/config/docker.js
> Fix: ensure https protocol with docker tls

- src/components/widgets/search/search.jsx
I realized that when specifying multiple search engines that the order in the config was not respected.  So by default google was always selected unless I manually selected a new search engine from the dropdown.  This poses an issue when using multiple devices since the client side is caching the selection.
Ideally, the order should be respected, in this case DuckDuckGo would be the default search engine unless switched via the dropdown:
```
- search:
provider: [duckduckgo, google]
```
This PR is a small change and will take care of this.
> Enhancement: respect search engine order from config

- docs/widgets/services/jdownloader.md
Fixed description from NextPVR to JDownloader.
Also added information about the requirement of a MyJDownloader account.
> Documentation: fix jdownloader widget documentation

- docs/configs/docker.md
- src/utils/config/docker.js
> Enhancement: support specifying protocol for Docker Socket Proxy

- src/utils/config/api-response.js
> Enhancement: support nested services via labels for mixed layout-only groups

- docs/configs/docker.md
- src/utils/config/docker.js
Following #5285, this change adds even more options to customize the connection to the docker API. I'd argue it also makes it more secure if you are running with a reverse proxy because you can now add basic auth :)
> Enhancement: Support more docker API connection options.

- docs/widgets/services/checkmk.md
- public/locales/en/common.json
- src/utils/proxy/handlers/credentialed.js
- src/widgets/checkmk/component.jsx
- src/widgets/checkmk/widget.js
- src/widgets/components.js
- src/widgets/widgets.js
Hi! I was surprised when I haven't found [CheckMK](https://checkmk.com/)'s widget in the library, so I created my own) For now it shows the number of currently active host and service issues on the specified CheckMK installation (site).
Closes #2500
> Enhancement: Checkmk widget

- Dockerfile
- docker-entrypoint.sh
- src/utils/config/config.js
> Chore: improve PUID/PGID support

- src/widgets/glances/metrics/info.jsx
Adjusts the glances info component to have the same block location classes it previously had before the commit: https://github.com/gethomepage/homepage/commit/94936ed09d64d594fe991eac998704b8fa5aad93 because when charts are disabled the value ends up being outside the card and is no longer visible.
This change should only affect the display properties when charts are disabled on this widget, but I have also checked to make sure there are no changes when charts are enabled.
Before change:
After Change:
> Fix: glances info widget system data out of bounds

- docs/widgets/services/wgeasy.md
- src/utils/config/service-helpers.js
- src/utils/proxy/handlers/credentialed.js
- src/widgets/wgeasy/component.jsx
- src/widgets/wgeasy/widget.js
> Enhancement: support breaking changes in wg-easy v15

- docs/widgets/services/gluetun.md
- src/widgets/gluetun/component.jsx
> Fix: make gluetun port_forwarded opt-in

- src/widgets/gluetun/component.jsx
> Fix: fix gluetun port_forward detection

- docs/widgets/services/beszel.md
Trivial typo in documentation
- [x ] Documentation only
- [x ] If applicable, I have added corresponding documentation changes.
- [x ] If applicable, I have reviewed the [feature / enhancement](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [x ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [x ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
> Documentation: fix beszel documentation typo

- src/utils/proxy/handlers/generic.js
> Change: preserve trailing slash in custom api calls

- src/widgets/glances/metrics/info.jsx
> Enhancement: improve glances info widget spacing

- src/widgets/calendar/proxy.js
> Enhancement: include ua for outlook ical integrations

- docker-entrypoint.sh
> Tweak: Improve ownership check and chown handling for .next dir

- src/widgets/romm/component.jsx
Supersedes #5563 
See https://github.com/rommapp/romm/pull/1903 --> https://github.com/rommapp/romm/releases/tag/3.10.0
> Fix: Handle Romm v3.10.0 filesize breaking change

- src/pages/index.jsx
- src/styles/globals.css
- src/utils/contexts/color.jsx
- src/utils/contexts/theme.jsx
- Removes scroll wrapper and returns scroll to body. Hopefully styling unaffected, but will have to check other platforms. Moreover, this returns the auto-hiding scrollbar one would expect.
- Fixes the horrible appearance in safari / other browsers by bringing the colors all the way to the [entire] body, see linked thread.
- Again, hopefully nothing unintentionally breaking background-wise
Closes #5569
> Fixhancement: restore native scrolling, background

- src/widgets/portainer/component.jsx
> Fix: fix error handling in Portainer Kubernetes widget

- src/pages/index.jsx
> Fix: properly handle classlist with light theme

- src/styles/globals.css
> Fix: set body background color

- src/widgets/evcc/component.jsx
Closes #5618
See https://github.com/evcc-io/evcc/pull/22299
> Enhancement: handle evcc 0.207 breaking change

- src/pages/index.jsx
> Fix bg opacity calculation

- src/widgets/iframe/component.jsx
> Fix: try to restore iframe transparency by restoring light scheme

- src/components/widgets/openmeteo/openmeteo.jsx
- src/components/widgets/openweathermap/weather.jsx
- src/components/widgets/weather/weather.jsx
> Enhancement: Auto-request geolocation if permission already granted

- src/widgets/tandoor/component.jsx
> Enhancement: support Tandoor v2 api structure

- docs/configs/settings.md
Found a typo in the documentation while using it, proposing the correction in a PR
> Documentation: fix typo in docs/configs/settings.md

- docs/configs/settings.md
- src/components/quicklaunch.jsx
- src/pages/index.jsx
> Enhancement: mobile QuickLaunch button

- docs/widgets/services/yourspotify.md
- mkdocs.yml
- public/locales/en/common.json
- src/utils/config/service-helpers.js
- src/widgets/components.js
- src/widgets/widgets.js
- src/widgets/yourspotify/component.jsx
- src/widgets/yourspotify/widget.js
Introduces a new service widget for [Your Spotify](https://github.com/Yooooomi/your_spotify) (Self hosted Spotify tracking dashboard).
Closes #5810
Example config:
```
- Your Spotify (day):
icon: your-spotify.png
href: https://{host-client}
description: Spotify tracking dashboard
widget:
type: yourspotify
url: https://{host-server}
key: {key}
interval: day
```
It makes 3 requests to the `your-spotify` server.
Request:
```
GET {url}/spotify/songs_per?token={key}&start=2025-09-20T22:00:00.000Z&timeSplit=all
```
Response:
```
[{"_id":null,"count":16,"differents":14}]
```
Request:
```
GET {url}/spotify/time_per?token={key}start=2025-09-20T22:00:00.000Z&timeSplit=all
```
Response:
```
[{"_id":null,"count":3362437}]
```
Request:
```
GET …
```
> Feature: Your spotify widget

- src/pages/index.jsx
Added `color-scheme` <head> property to ensure browser won't change page styling (as styling is precisely defined in config file).
Fixes improper theme handling by darkreader - now darkreader extension doesn't want to override homepage's theme with a less appealing main color (for me it's solid red):
After this commit:
**dark theme detected** appears in darkreader, which prohibits overriding the theme
> Fix: specify color-scheme meta for darkreader

- docs/configs/proxmox.md
I recently went through the Proxmox integration for Homepage and noticed some confusion around the `proxmox.yaml` configuration. Specifically, the key in `proxmox.yaml` must match the actual Proxmox node name, and this exact name must be used in the `proxmoxNode` field of service configurations (see [discussion](https://github.com/gethomepage/homepage/discussions/5540#discussioncomment-14531489)).
The current [Proxmox documentation](https://gethomepage.dev/configs/proxmox/) wasn’t entirely clear on this, so I’ve updated the wording and examples to clarify this requirement for users.
> Note: I will submit a separate PR for the Kubernetes-specific configmap and volume mount instructions to keep changes focused.
```
> pre-commit run --files docs/configs/proxmox.md
Trim Trailing …
```
> Documentation: clarify proxmox.yaml key must match Proxmox node name

- src/pages/index.jsx
- src/styles/globals.css
Loving this Apple-induced whack-a-mole crap 😒
> Fix: restore bg image to body again
