.github/workflows/docker-publish.yml
I added amd64, arm64, armv6, armv7, and commented the list of supported architectures.
By the way, you should setup Dependabot in order to update (via pull requests) the Actions you use (e.g. docker/setup-qemu-action): https://github.com/marketplace/actions/docker-setup-buildx#keep-up-to-date-with-github-dependabot
=> Build for multiple CPU architectures

package.json, pnpm-lock.yaml, public/locales/en/common.json, src/components/services/widget.jsx, src/components/services/widgets/service/jackett.jsx, src/pages/api/services/proxy.js, src/utils/api-helpers.js, src/utils/http.js
- add the follow-redirect package
- add the tough-cookie package
Jackett API uses a redirect mechanism to set a CSRF token. This CSRF token is stored in a cookie that is required to be present or the API won't work.
=> Add the Jackett widget

src/pages/index.jsx
This fix improves readability with bright background images adding a tint.
Just add a new line to the `settings.yaml` (defaults to 1):
```yaml
backgroundOpacity: 0.5
```
=> Add backgroundOpacity option

.vscode/launch.json, src/pages/api/services/proxy.js, src/utils/proxies/generic.js
This is a proof of concept on how to reduce the amount of data returned to the client via the existing proxy system, at the cost of additional CPU and memory utilization.  An upshot is that this could allow for clients to request data that you might not want to expose to those clients and potentially mask or remove any sensitive data.
=> Proposal to add ability to map data in a proxy

public/locales/en/common.json, src/components/services/widget.jsx, src/components/services/widgets/service/strelaysrv.jsx, src/pages/api/services/proxy.js, src/utils/api-helpers.js
* Added Syncthing Relay Server widget
=> Add Syncthing Relay Server widget

src/widgets/prowlarr/widget.js
During the refactor we left the `?apikey={key}` part off of the api widget property.
=> Fix Prowlarr show API Error

.vscode/settings.json, public/locales/en/common.json, src/utils/proxy/cached-fetch.js, src/widgets/unifi/component.jsx
- Needed to decompose i18n labels for Unifi widget in order for field visibility setting to work correctly
- Fixed weird edge case where a call to cached-fetch would fail if no duration was passed
- Have VS Code hide the .next and node_modules folders from tree view
=> Decompose i18n labels for Unifi widget

package.json, pnpm-lock.yaml, public/locales/en/common.json, src/widgets/components.js, src/widgets/plex/component.jsx, src/widgets/plex/proxy.js, src/widgets/plex/widget.js, src/widgets/widgets.js
I didn't love the idea of installing Tautulli just for the widget goodness for Plex so I wrote a service widget that uses the Plex API directly. Its not as fancy as the Tautulli one but its still useful and is a little more 'standard'. If you guys dont like the approach here feel free to close this.
Details:
- As noted in the wiki, the Plex API is not great so this merges a few different endpoints to get useful info (active streams, n movies and n tv shows).
- Caching is used to prevent too many calls. The active streams call is still every 5s (`refreshInterval`) but the libraries call is cached for 6 hours, the movie/tv counts for 10 minutes. Obviously these times can be tweaked but these seemed a reasonable balance.
- Plex API serves XML so this uses (lightweight!) …
=> Feature: Plex service widget without Tautulli

src/widgets/plex/widget.js
As discussed in https://github.com/benphelps/homepage/pull/366#issuecomment-1274247350
New `services.yaml`:
```yaml
- Plex:
href: https://app.plex.tv
description: My Plex media server
icon: plex.png
widget:
type: plex
url: http://x.x.x.x:32400
key: mytokenhere # see https://www.plexopedia.com/plex-media-server/general/plex-token/
```
=> Fix: change Plex service widget to use "key" not "token"

public/locales/en/common.json, src/components/widgets/glances/glances.jsx, src/components/widgets/widget.jsx, src/pages/api/widgets/glances.js
One more! An info widget for [Glances](https://nicolargo.github.io/glances/) i.e. to remotely monitor another machine. Obviously this is built to match the `resources` info widget
- Uses the [quicklook](https://glances.readthedocs.io/en/latest/api.html#get-quicklook) endpoint to make it just one http call.
- ~~Moved `UsageBar` to a common folder to share with resources.~~
- Allows basic auth if enabled for glances
- Allows multiple instances with optional `id` property
Part of #125
`widgets.yaml`:
```yaml
- glances:
id: glances1 # if using multiple instances
label: RaspPi # optional
```
`settings.yaml`:
```yaml
- glances1: # if using multiple instances or just 'glances' for a single instance
url: http://x.x.x.x:61208
username: user # optional
password: pass # optional
```
=> Feature: Glances info widget

src/components/widgets/unifi_console/unifi_console.jsx, src/pages/api/widgets/glances.js, src/utils/config/api-response.js, src/utils/config/config.js, src/utils/config/service-helpers.js, src/utils/config/widget-helpers.js, src/widgets/unifi/proxy.js
As discussed, this PR implements "unified" settings for info widgets. It also updates the `glances` and `unifi_console` info widgets to use this. Appreciate any input.
- Adds `getPrivateWidgetOptions` which optionally takes a widget type + index argument and returns... private widget options
- private settings (currently "url", "username", "password", "key") are removed from the widget options API response so theyre not passed as query vars
This allows for "unified" widgets.yaml (and multiple instances of a widget without needing `id` or anything), no settings.yaml needed 🎉
e.g. `widgets.yaml`:
```yaml
- glances:
url: http://1.2.3.4:61208
username: user
password: pass
label: RaspPi
- glances:
url: http://5.6.7.8:61208
username: user
password: pass
label: AnotherMachine
- unifi_console: …
```
=> Feature: Unified info widget settings

src/components/bookmarks/item.jsx, src/components/services/item.jsx
Allows the user to add `target:` to specific individual service and bookmarks, so it will treat specific links similar to the `target:` that can be set in the settings file.
An example service with this PR in mind would be:
```
- Apps:
- Grafana:
href: https://example.com/
icon: grafana
description: System statistics and graphs
server: docker2
target: _self
```
If no target is added in the service/bookmark,  it continues to default to `_blank` like it normally does.
Will need to update the wiki to add this information to the services and bookmark pages, if this is accepted. Thanks.
=> Feature: support target in individual services/bookmarks

public/locales/en/common.json, src/components/quicklaunch.jsx, src/components/search.jsx, src/components/services/item.jsx, src/pages/index.jsx
I made a thing! Its a "quick launcher"? aka global search of all services & bookmarks, triggered by just typing on the page. Its very simple but as a result its fast AF. Im sure I missed some things in here but overall pretty happy with this. Appreciate any feedback / tweaks. Video is all keyboard =)
Edit:
- A way to bring this up on mobile, or keep it desktop only?
- Should we search / include descriptions? 
- Edit: added as [an option](https://github.com/benphelps/homepage/pull/409#issuecomment-1285970882)
- ~~Prioritization?~~ 
- Edit: uses same order as services/bookmarks config, I think thats good
- ~~Highlighting?~~
- Edit: Only for descriptions. [I dont like it for the main name.](https://user-images.githubusercontent.com/4887959/196809825-ceef596b-c5ff-4cc8-a3ba-93e26ccc322f.png) …
=> Feature: homepage quick launch aka search

public/locales/en/common.json, src/widgets/changedetectionio/component.jsx, src/widgets/changedetectionio/widget.js, src/widgets/components.js, src/widgets/widgets.js
How to use:
```yaml
- ChangeDetectionIO:
href: http://localhost/
description: Homepage is awesome
widget:
type: changedetectionio
url: http://192.168.15.2:5000
key: asfasdasfasdasfasdasfasdasd
```
Preview:
=> Add ChangeDetection.io widget

public/locales/en/common.json, src/widgets/components.js, src/widgets/homebridge/component.jsx, src/widgets/homebridge/proxy.js, src/widgets/homebridge/widget.js, src/widgets/widgets.js
Simple homebridge widget,
How to use:
```javascript
- Homebridge:
icon: homebridge.png
container: homebridge
service: homebridge
href: http://your-ip-address:8581
description:
widget:
type: homebridge
url: http://your-ip-address:8581
username: your-username
password: your-password
```
Preview:
If you dont have child bridges:
=> feature: add homebridge widget

public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/autobrr/component.jsx, src/widgets/autobrr/widget.js, src/widgets/components.js, src/widgets/widgets.js
Adds widget support for autobrr
service.yaml example:
```
- autobrr:
icon: autobrr.png
container: autobrr
href: http://<url>:<port>
description: the modern autodl-irssi replacement
widget:
type: autobrr
url: http://<url>:<port>
key: <api_key>
```
Preview:
=> feature: add autobrr widget

src/components/widgets/datetime/datetime.jsx
- the widget was missing a flex-col div around it and was therefore taking up more space than it needed as it was reported here https://github.com/benphelps/homepage/issues/235#issuecomment-1276209354
=> Fix datetime widget size issue

public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/tubearchivist/component.jsx, src/widgets/tubearchivist/widget.js, src/widgets/widgets.js
Adds widget support for [Tube Archivist](https://www.tubearchivist.com/)
service.yml example
```yml
- Tube Archivist:
icon: tube-archivist.png
href: https://tubearchivist.example.com
description: Your self hosted YouTube media server
widget:
type: tubearchivist
url: https://tubearchivist.example.com
key: <apikey>
fields: ["downloads", "videos", "channels", "playlists"]
```
Screenshot:
=> Feature: add Tube Archivist widget

src/components/bookmarks/item.jsx
#291 
Same functionality as service icons. Falls back to abbreviation.
=> Adds the option for a bookmark icon

public/locales/en/common.json, src/widgets/components.js, src/widgets/navidrome/component.jsx, src/widgets/navidrome/widget.js, src/widgets/widgets.js
This PR adds initial support for displaying now playing song information from Navidrome using the Subsonic API. The widget will display the currently-playing song for all users currently connected to the provided Navidrome server.
`services.yaml`
```yaml
- Navidrome
icon: navidrome.png
href: http://<url>:<port>
description: Bangers and Kool-Aid Jammers
widget:
type: navidrome
url: http://<url>:<port>
user: <user>
token: <token>
salt: <salt>
```
For example:
```yaml
- Navidrome
icon: navidrome.png
href: http://localhost:4533
description: Bangers and Kool-Aid Jammers
widget:
type: navidrome
url: http://localhost:4533
user: navidrome
token: 9e686d7eb61b8639642c6dfc26b23c7e
salt: ca976fd9
```
Navidrome currently supports Subsonic API version 1.16.1: …
=> Feature: add navidrome support

public/locales/de/common.json, public/locales/en/common.json, src/widgets/components.js, src/widgets/pyload/component.jsx, src/widgets/pyload/proxy.js, src/widgets/pyload/widget.js, src/widgets/widgets.js
Adds a simple widget for monitoring [Pyload](https://github.com/pyload/pyload/) downloads.
possible fields:
- speed
- active
- queue
- total
example config:
```yaml
- Pyload:
icon: /icons/pyload.png
href: http://home:8668/
description: Download Manager
container: pyload
widget:
type: pyload
url: http://home:8668
username: secure_monitor
password: super!secret
```
The pyload user in question needs at least "LIST" permissions.
Empty passwords are also supported. So you can create a monitoring user with only "LIST" permissions and no password.
This would look like this in the config:
```yaml
widget:
type: pyload
url: http://home:8668
username: monitor
```
=> Add Pyload widget

src/components/widgets/openweathermap/weather.jsx
The day/night icon does not display properly in openwathermap widget due to the typo (sundown -> sunset) in parsing data from openweathermap api. The icon would be displayed properly after the fix.
=> Fix: openweathermap day/night icon issue

public/locales/en/common.json, src/widgets/components.js, src/widgets/gluetun/component.jsx, src/widgets/gluetun/widget.js, src/widgets/widgets.js
Added widget to support [gluetun](https://github.com/qdm12/gluetun) information:
Configuration:
```
- Gluetun:
icon: /icons/pipe.png
href: https://gluetun.mydomain.com
description: VPN Client
widget:
type: gluetun
url: https://gluetun.mydomain.com
```
Preview:
=> Add gluetun widget

src/widgets/npm/component.jsx, src/widgets/npm/proxy.js
This PR adjusts the npm widget to use the backend proxy instead of browser `fetch`. I think this is the reason we've been seeing sporadic reports of issues with this one. It also now caches the login token, cause why not.
Closes #387
=> Fix: Change npm widget to use httpProxy not fetch

src/pages/index.jsx, src/utils/config/api-response.js
This PR supports sorting of layouts so that the user can place the specified layout at the top
By default, the behavior remains the same as before, and the layout to be sorted needs to be declared manually for it to take effect
Edit:
settings.yaml
```
layout:
layout1:
sort: true  # enable
style: row
columns: 3
layout2:
sort: true
style: row
columns: 3
layout3:
style: row
columns: 3
layout4:
style: row
columns: 3
```
=> Feature: support sort layout

public/locales/en/common.json, src/widgets/components.js, src/widgets/hdhomerun/component.jsx, src/widgets/hdhomerun/widget.js, src/widgets/widgets.js
- Tracking Channels, and HD Channels
- Condensed API Calls into 1, per request in [earlier pr](https://github.com/benphelps/homepage/pull/481)
=> Add HDHomeRun widget

src/utils/logger.js
Added a setting `logpath` that when set, will allow the administrator to specify a log location on disk. If not set, the value will remain the config directory as before.
Why necessary:
1) Its a best practice to be able to configure the log place.
2) Logs probably shouldn't be stored in the config directory.
3) For certain platforms, the config directory might not be writable, no widgets appear to work when this is the case
=> Added configurable setting for log folder

public/locales/en/common.json, src/components/services/item.jsx, src/components/services/ping.jsx, src/components/services/status.jsx, src/pages/api/ping.js, src/utils/proxy/http.js
See #388 , I accidentally deleted the head branch closing that one =)
As discussed, this PR implements the ping which uses a `HEAD` request, also shows estimated latency if status is 200. Changes look of docker status too. As noted users would need to be careful about which URL to ping, if the public domain is behind a reverse-proxy this will potentially falsely always return status 200, instead local URL / ip could be specified to test http status.
Closes #248, closes #78
`services.yaml`
```yaml
- Paperless-ngx:
href: https://paperless.domain.com
description: My awesome Paperless-ngx instance
icon: paperless.png
ping: https://google.com
server: docker
container: paperless
```
=> Feature: Service ping, redesign docker status

public/locales/en/common.json, src/widgets/components.js, src/widgets/scrutiny/component.jsx, src/widgets/scrutiny/widget.js, src/widgets/widgets.js
Added widget to support [scrutiny](https://github.com/AnalogJ/scrutiny) information:
Configuration:
```
- Scrutiny:
icon: scrutiny.png
href: https://scrutiny.mydomain.com
description: Hard Drive Monitoring
widget:
type: scrutiny
url: https://scrutiny.mydomain.com
```
Preview:
=> Add scrutiny widget

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/setup.sh
devcontainers can be used by IDEs like VSCode to build the whole development environment in a container. This allows you to keep dependencies, build, and all development aspects separated from any development. It also allows contributors to instantly have a working, standardized development environment. It also allows cloud development tools like GitHub Codespaces be automatically setup with the desired environment.
See https://containers.dev/ for more details
=> Add devcontainer configuration

public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/components.js, src/widgets/paperlessngx/component.jsx, src/widgets/paperlessngx/widget.js, src/widgets/widgets.js
Added a widget for [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx). It should also be compatible with paperless-ng (and paperless?), as i didn't see any difference in the api endpoints, that this widget is using.
Config:
```
- Paperless-ngx:
description: Document Management
icon: paperless
href: https://paperless.somedomain.com
widget:
type: paperlessngx
url: https://paperless.somedomain.com
username: user
password: password
```
Preview:
Currently the total number of documents and the number of documents in the Inbox can be displayed.
In order to get the number of documents in the inbox, the `inboxTag` must be specified in the config.
---
Now these are two metrics that i am particularly interested in. I am happy to hear your opinion/ideas (different metrics? more dynamic …
=> Add paperless-ngx widget

src/components/widgets/datetime/datetime.jsx
This bug seems to have no real negative effect but currently the date time info widget will throw react rehydration errors e.g. `Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.` due to the server vs client rendering of the date time widget. This PR corrects this. 
Functionally for users this will mean that instead of seeing a flash of the incorrect time on startup they will see a flash of nothing. Videos below demonstrate.
Current:
https://user-images.githubusercontent.com/4887959/204359201-e4569694-043f-48cf-b9d1-3b20abc1d7e2.mov
Now:
https://user-images.githubusercontent.com/4887959/204359217-478ae42c-7611-4c1b-9629-c66f4 …
=> Fix datetime react render error

src/widgets/deluge/proxy.js
As noted in #563 the deluge API uses the webui password e.g. https://dev.deluge-torrent.org/wiki/Faq#Whatisthedefaultpassword, which doesnt have a username. Technically the current widget will work if you use that password but we dont need the username. Docs were updated to explain this
I am testing this against the lsio deluge container but I think from the docs should be same with bare metal, see https://deluge-webapi.readthedocs.io/en/latest/quickstart.html
Closes #563
=> Fix: deluge widget doesnt use username

src/components/widgets/resources/memory.jsx
I agree with the issue #497 that memory should show a decimal, i.e. 1.7GiB instead of 2GiB, doesnt negatively affect the aesthetic of the widget imho (screenshot below). If others disagree happy to discuss ofc.
Closes #497
=> Change: Show memory up to 1 decimal place

public/locales/en/common.json, src/widgets/overseerr/component.jsx, src/widgets/overseerr/widget.js
The `processing` count is a count of the still in process (Requested) media. It is equal to the `approved` minus the `available`.
It is available in the same API call as the other information.
=> Added processing count to overseerr

src/components/quicklaunch.jsx
As noted in the linked issue, quick launch overlaps a few different widgets, increasing its z-index solves it
Closes #582
=> Fix quicklaunch z-index

src/pages/api/ping.js
After much discussion in #572 it seems that its not so uncommon that services reject a `HEAD` request but do respond to a regular `GET`, this PR adds a fallback to GET for the ping feature. The 'cost' is that true failures will now require 2 calls if the response is not a 500.
=> Change: Add fallback to http GET for ping

src/utils/config/service-helpers.js, src/widgets/coinmarketcap/component.jsx
This PR supersedes #597 and fixes #444 by adding an optional default interval for for CMC
```
widget:
type: coinmarketcap
currency: GBP # Optional
symbols: [BTC, LTC, ETH]
defaultinterval: 24h
key: xxx
```
=> Feature: Add default interval setting for coinmarketcap

src/widgets/docker/component.jsx
=> Fix: Hide docker memory stats when unsupported

src/widgets/scrutiny/component.jsx, src/widgets/scrutiny/widget.js
This PR addresses the issue mentioned [here](https://github.com/benphelps/homepage/issues/596).
The scrutiny widget now respects the device status threshold setting when calculating the number of failed and passed devices.
=> Respect scrutiny device status threshold setting

src/widgets/homebridge/proxy.js, src/widgets/npm/proxy.js, src/widgets/plex/proxy.js, src/widgets/pyload/proxy.js, src/widgets/transmission/proxy.js, src/widgets/unifi/proxy.js
Closes #649
This allows for duplicates of certain widgets (the ones that cache a key or token or whatever) by appending the service name to the cache key. This still requires that the service name be unique, but that's already the case.
I did make sure I didnt break them all =)
=> Fix: allow multiple instances of certain widgets

src/components/resolvedicon.jsx, src/components/widgets/logo/logo.jsx
Closes #565
Added the ability to change the default homepage logo widget in the header.
Configuration:
```yaml
- logo:
source: whatever/you/want # URLs are also allowed: https://..
```
Preview:
Uses the default homepage logo if the source isn't set:
=> Add ability to use custom logo

public/locales/en/common.json, src/widgets/components.js, src/widgets/tdarr/component.jsx, src/widgets/tdarr/proxy.js, src/widgets/tdarr/widget.js, src/widgets/widgets.js
Adding a widget for Tdarr to close [#404](https://github.com/benphelps/homepage/issues/404).
This will display 4 fields: 
- Count of items currently in queue
- Count of items that have been processed
- Count of items that have errored
- Total amount of disk space saved
Configuration example:
```        
widget:
type: tdarr
url: http://tdarr.host.or.ip
```
Preview:
=> added tdarr widget

next-i18next.config.js, public/locales/en/common.json, src/widgets/qbittorrent/component.jsx, src/widgets/speedtest/component.jsx
Closes #619 
I need a 🍺 after this one...
This updates speedtracker + qbittorrent, there may be other widgets using the wrong unit (wrong meaning dont match their source) but there are now options that should cover them if anyone notices, and hopefully are correct e.g.
```
"byterate": "{{value, rate(bits: false)}}",
"bibyterate": "{{value, rate(bits: false; binary: true)}}",
"bitrate": "{{value, rate(bits: true)}}",
...
```
=> Fix rate unit displays

src/widgets/pihole/component.jsx, src/widgets/pihole/widget.js
As helpfully pointed out in #711 pihole added an auth requirement to its api endpoints in a recent version. This adds support for that (`key` just like other widgets) and also updates the API endpoints to be more explicit. I tested this going back a few versions to ensure backwards-compatability and didnt see any issues, I think the API has been stable for quite a while.
Closes #711 
New config e.g. 
```yaml
widget:
type: pihole
url: http://iporhost
key: mypiholeapikey
```
=> Pihole allow auth, updated API endpoint

public/locales/en/common.json, src/widgets/components.js, src/widgets/omada/component.jsx, src/widgets/omada/proxy.js, src/widgets/omada/widget.js, src/widgets/widgets.js
Supersedes #674 
Obviously this is working for me locally (with all 3 versions of API) but I dont have any actual devices so would be good if someone can test and report.
@Oupsman sorry to close your PR but needed to squash your commits [for reasons discussed](https://github.com/benphelps/homepage/pull/674#issuecomment-1349262127) =) and because of the way you added commits they couldn't be squashed in your branch. Also, even thought this required some changes, still appreciate your effort!
Closes #202 
```yaml
widget:
type: omada
url: https://localhost:8043
username: username
password: password
site: Default
```
=> Feature: Omada widget

src/widgets/overseerr/component.jsx, src/widgets/radarr/component.jsx, src/widgets/sonarr/component.jsx
I've fixed some of the widgets to give them some proper number formatting while using the i18n-translator
widgets:
- sonarr
- radarr
- overseerr
sample when having culture information setup to: de-DE
before:
after:
=> fixed number formatting in widgets: radarr, sonarr, overseerr

public/locales/en/common.json, src/widgets/components.js, src/widgets/opnsense/component.jsx, src/widgets/opnsense/widget.js, src/widgets/widgets.js
First working version of OPNsense widget. CPU and memory usage are not quite reliable yet.
=> OPNSense widget

src/components/version.jsx, src/pages/api/releases.js
Now that version checking was fixed =) its become apparent that the current implementation of caching of the GH releases API data used for version checking doesnt actually cache the data because its in browser memory not server-side. This fixes that.
The fact that homepage breaks when the call fails is fixed separately already but this will likely prevent that anyway.
See #738 #744
=> Fix: version check caching

src/components/widgets/datetime/datetime.jsx
Uses `font-variant-numeric: tabular-nums` to prevent width changes as datetime widget seconds tick
Enjoy this relaxing video where nothing moves 🤓:
https://user-images.githubusercontent.com/4887959/210258119-d29c055a-7f3c-423e-8ced-c0bc507471c5.mov
Closes #764
=> Use tabular nums for datetime to prevent size changing

README.md
Giving Read Only rights to homepage container in docker-compose example.
Adding :RO to the docker.sock volume. When the container gets compromised the intruder will have root access basically. The container doesn't need the write privileges.
This measure will stop inexperienced people from exposing their docker.socket to the public internet.
=> Giving Read Only rights to homepage

src/components/widgets/datetime/datetime.jsx
=> Feature: allow setting locale for datetime widget directly

src/pages/index.jsx, src/utils/config/config.js
Wow, this one was a rabbit-hole...
See the linked issue, basically every time the container is re-created the settings aren't picked up until forcing revalidate (e.g. with the little refresh icon, changing the file etc).
I eventually traced this to the fact that [`getSettings()`](https://github.com/benphelps/homepage/blob/f09268230e269a8a6f679b1cfec1212a6029d28f/src/utils/config/config.js#L30) is returning nonsense for the file contents of the settings file when run at build time. It literally returns the string `-\n`. Thats true if you have a normal settings.yaml file, an empty one or the skeleton.
I have no idea if thats a bug in a dependency somewhere or what, I tried to track down why but still dont know. That said, if we can detect that we should be able to force revalidate to fix …
=> Fix: settings not picked up after first container creation

Dockerfile, docker-entrypoint.sh
A good practice is to avoid running processes in containers as root, unless absolutely necessary. Since homepage only uses it's own `/app` directory, and exposes port `3000`, I think it is safe to drop privileges on start :)
=> use unprivileged user in a container

src/components/bookmarks/item.jsx, src/components/resolvedicon.jsx
Hello, I submitted a [feature request](https://github.com/benphelps/homepage/issues/814) and was able to implement it myself. This uses the abbr property of bookmarks as a fallback in case it doesn't find the icon by replacing the "logo" string in the image's alt text. It's a tiny change, but I think it's a good one since previously abbr would just be ignored if the icon failed to load.
Here's a screenshot:
Using the following bookmarks.yaml:
```
---
- Dashboard icon:
- Icon with abbr:
- icon: github-light.png
abbr: GH
href: https://github.com/
- Icon without abbr:
- icon: github-light.png
href: https://github.com/
- Bad icon with abbr:
- icon: github-light1.png
abbr: GH
href: https://github.com/
- Bad icon without abbr:
- icon: github-light1.png
href: https://github.com/
- Direct or …
```
=> use abbr as icon fallback

public/locales/en/common.json, src/widgets/components.js, src/widgets/medusa/component.jsx, src/widgets/medusa/widget.js, src/widgets/widgets.js
This PR add medusa widget.
It is used with :
```yaml
- Medusa:
icon: medusa.png
href: http://medusa.host.or.ip
widget:
type: medusa
fields: ["wanted", "queued", "series"]
url: http://medusa.host.or.ip
key: apikeyapikeyapikeyapikeyapikey
```
Here are some api payload for each endpoint that are used:
```json
{
"data": {
"ep_downloaded": 492,
"ep_snatched": 0,
"ep_total": 508,
"shows_active": 11,
"shows_total": 27
},
"message": "",
"result": "success"
}
```
```json
{
"data": {
"later": [],
"missed": [],
"soon": [
{
"airdate": "2023-01-22",
"airs": "Sunday 9:00 PM",
"ep_name": "The Abyss",
"ep_plot": "",
"episode": 6,
"indexerid": 360295,
"network": "BBC One",
"paused": 0,
"quality": "HD",
"season": 3,
"show_name": "His Dark Materials",
"show_status": "Continuing",
"tvdbid": 360295, …
```
=> Add Medusa widget

src/utils/config/service-helpers.js, src/widgets/opnsense/component.jsx
Closes #823
Im not sure how widespread the issue is here ie if the user in the linked issue's setup is highly atypical (not really familiar with opnsense) ~~but the fix is simple enough, if no `wan` fall back to `opt1`, if that doesnt exist we still prevent erroring out~~.
Edit: after re-considering, we'll allow specifying this with `wan` (optional, of course)
```yaml
widget:
type: opnsense
url: http://host
username: ...
password: ...
wan: opt1
```
sample data
```json
{"interfaces":{"opt1":{"flags":"8843","promiscuous listeners":"0","send queue length":"0","send queue max length":"50","send queue drops":"11405","type":"Ethernet","address length":"6","header length":"14","link state":"2","vhid":"0","datalen":"152","mtu":"1500","metric":"0","line rate":"1000000000 bit\/s","packets …
```
=> Fix: Handle opnsense no wan interface

public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/cloudflared/component.jsx, src/widgets/cloudflared/widget.js, src/widgets/components.js, src/widgets/widgets.js
This reaches out to cloudflare using an API call and gets the status of the tunnel and the origin ip, as requested in a feature request.
Here is the services.yaml
```yaml
widget:
type: cloudflared
email: fake@email.com
accountid: <accountid> #this can be pulled from your dash page in the url
tunnelid: <tunnelid> #this is pulled from your tunnel dashboard
key: <apikey> #this is an api key you setup in your account at https://dash.cloudflare.com/profile/api-tokens
```
=> Cloudflared Widget

src/utils/config/service-helpers.js
At least in Kubernetes, the field list is not being parsed. This PR detects if the fields list is a string and if it is parses it as JSON. This resolves the issue for Kubernetes widgets and should not disturb existing functionality.
=> Enhancement: support specifying widget fields in docker labels / kubernetes annotations

src/utils/config/api-response.js, src/utils/config/service-helpers.js
* Default for discovered services is 0
* Default weight for configured services is their index within their group scaled by 100, i.e. (index + 1) * 100
* Should be backwards compatible with current loose ordering
* If two items have the same weight value, then they will be sorted by name
closes #673
=> Services are now sorted by a new 'weight' field

src/widgets/proxmox/component.jsx
=> Don't show QEMU templates in VMs field for Proxmox widget

src/components/widgets/search/search.jsx, src/pages/index.jsx
support multiple `provider` for option in search widget
Example:
```yaml
- search:
provider: [baidu, google, duckduckgo]
target: _blank
```
When `providers` is configured, the search button is replaced with a ListBox, from which a search engine can be selected.
Look like this
=> Support multi search providers

src/components/services/status.jsx
If data.health is an empty string, ?? will accept it and not use the right side value; instead, we should use || which treats empty string as false and returns the right side value. This will show "RUNNING" in the status box if health is "".
=> Fix: Show container status if health is an empty string

src/pages/_app.jsx, src/styles/custom.css
Hi @benphelps,
based on the discussions in #235, #139  and similar issue I have encountered myself (trying to insert a logo which I want to be wider than 48px), I would suggest adding support for custom css to cater for unique and custom usecases users may have. This way everyone can simply override the style they want to customize.
I'd be of course happy to update the docs accordingly in the benphelps/homepage-docs repo if this change is accepted.
Side note: I have considered adding custom styles via settings but it's troublesome because the imports must be static otherwise Webpack build fails. There could be probably ways to use dynamic import but tbh this seems much easier and transparent.
=> feat: Custom CSS

public/locales/en/common.json, src/components/widgets/unifi_console/unifi_console.jsx, src/utils/config/service-helpers.js, src/widgets/unifi/component.jsx
Two things:
- Support other sites (now allows `site` key with name)
- When no [useful] data is returned from a controller currently it looks like there's no widget (and no error is shown), now it shows this to the user
Closes #706 
Closes #926
=> Feature: Unifi widgets support non-default site

src/utils/proxy/cookie-jar.js
cookieJar.setCookieSync crash node when error, like:
```
uncaughtException: Error: Cookie not in this host's domain. Cookie:example.com Request:127.0.0.1
```
=> Fix: cookieJar.setCookieSync ignore error

src/utils/config/service-helpers.js
This adds the missing support for "ping" in Kubernetes ingress. It can be used as follows:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: pihole
annotations:
gethomepage.dev/enabled: "true"
gethomepage.dev/name: PiHole
gethomepage.dev/description: Ad Blocker and Local DNS
gethomepage.dev/group: Admin
gethomepage.dev/ping: "https://pihole.my.network/admin"
gethomepage.dev/icon: pihole.png
gethomepage.dev/widget.type: "pihole"
gethomepage.dev/widget.url: "https://pihole.my.network"
gethomepage.dev/widget.key: "secretwidgetkey"
spec:
rules:
- host: pihole.my.network
http:
paths:
- pathType: Prefix
path: /
backend:
service:
name: pihole
port:
number: 80
```
Fixes #957
=> Added support for "ping" configuration in kubernetes ingress annotations

package.json, pnpm-lock.yaml, src/widgets/rutorrent/proxy.js
This rewrites the rutorrent widget proxy (still needed) to:
- Use the proxied http calls (currently uses fetch via the dependency)
- Remove the rutorrent-promise dependency
- This also allows using https with invalid cert
=> Feat: rewrite rutorrent proxy

src/pages/index.jsx
I moved the footer to the bottom of the screen.
If the home page is smaller than a screen (for example, without bookmarks), the footer is in the middle of the screen. I made the max page height to move the footer down.
=> Move the footer to the bottom

src/components/services/status.jsx, src/pages/api/docker/stats/[...service].js, src/pages/api/docker/status/[...service].js, src/widgets/docker/component.jsx
Digging into swarm a bit, currently the code just chooses the 0th task for a service which might be on a different node, in which case we can't get container stats, so this PR tries to find one running locally which fixes the status and stats badge (though stats are still only for 1 task as current).
Closes #970 (which may actually be partly a separate issue too)
@vinaydawani would be great if you could check this out, again Im just playing with swarm for testing purposes...
Edit: this now also contains changes from #998 which improved swarm status with N replicas info
=> Fix: improve swarm status for replicated services & prefer stats for local containers

src/utils/proxy/api-helpers.js, src/utils/proxy/handlers/credentialed.js, src/utils/proxy/handlers/generic.js
In the end it's not that many widgets but some contain sensitive information in the URL e.g. API key, not only do we want to prevent display but prevent data from being returned to frontend at all, so strip it server-side. For better or worse this is an 'exclude' list rather than an 'allow'. Again I believe this covers the current cases, certainly the two noted in the linked issues.
Fixes #896 
Fixes #1001
=> Feature: strip sensitive information contained in URLs from frontend API calls

src/pages/api/hash.js, src/pages/index.jsx, src/utils/config/config.js
Ok, this is another approach to try and fix #576 (and it reverts the other attempt).
The idea here is to include `NEXT_PUBLIC_BUILDTIME` in the config hash, which in effect will force revalidation after the container is updated even if the settings haven't changed.
It's not perfect, if someone recreates the container it'll still happen and folks building their own image will need to supply the build time arg for this to work. But for the majority of users who are seeing this e.g. after watchtower updates this should help.
Still welcome other solutions here, especially to the post-recreation part
Closes #576 (again)
=> Fix settings after container update

src/widgets/flood/component.jsx, src/widgets/transmission/component.jsx
Convert Flood download and upload rates from B/s to b/s
Closes #1021
=> Fix: Correct flood + transmission rate units

public/locales/en/common.json, src/widgets/components.js, src/widgets/healthchecks/component.jsx, src/widgets/healthchecks/widget.js, src/widgets/widgets.js
First time open source contributor.
I implemented a widget for [healthchecks.io](https://healthchecks.io/). It shows the current status of a project. (online, offline, etc)
This closes https://github.com/benphelps/homepage/issues/965
widget:
type: healthchecks
key: <YOUR_API_KEY>
uuid: <YOUR_CHECK_UUID>
Let me know if you need any changes done. 👍
=> Add Health checks widget

src/widgets/homebridge/proxy.js
Seems something changed in recent home bridge version, the API kicks back login credentials long before expiration with a 403, remedy is just to login again.
Closes #1025
=> Fix homebridge config UI-X API expires login with 403

src/components/services/item.jsx, src/utils/config/service-helpers.js
External services define a kubernetes service pointing to an application hosted outside of the cluster. These services should not attempt to get the status based on kubernetes deployments. The new boolean flag disables this functionality. Since this is an edge case, the default value is "false".
Prior to this change the system would attempt to find a matching deployment and fail, resulting in a "not found" error and small box in the top right corner.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: uptimekuma
annotations:
gethomepage.dev/enabled: "true"
gethomepage.dev/name: Uptime Kuma
gethomepage.dev/description: Service Uptime Monitoring
gethomepage.dev/group: Admin
gethomepage.dev/url: "https://uptime.k3d.localhost"
gethomepage.dev/icon: uptime-kuma.png …
```
=> Added "external" boolean annotation to specify external services

.github/workflows/chart-publish.yml, charts/homepage/Chart.yaml, charts/homepage/ci/test-values.yaml, charts/homepage/readme.md, charts/homepage/templates/common.yaml, charts/homepage/templates/configmap.yaml, charts/homepage/templates/rbac.yaml, charts/homepage/values.yaml
Moving my unofficial helm chart to the official repo. In addition to merging this, a new `gh-pages` branch needs to be created first which is where the resulting chart will be published to.
This is based on the official docs: https://helm.sh/docs/howto/chart_releaser_action/
=> Migrated helm chart from jameswynn/helm-charts

public/locales/en/common.json, src/widgets/components.js, src/widgets/prometheus/component.jsx, src/widgets/prometheus/widget.js, src/widgets/widgets.js
Adds a service widget for Prometheus to quickly see the health of targets.
Based on the Targets api: https://prometheus.io/docs/prometheus/latest/querying/api/#targets
sample GET `/api/v1/targets`:
```JSON
{
"status": "success",
"data": {
"activeTargets": [
{
"discoveredLabels": {
"__address__": "REDACTED_IP:8080",
"__metrics_path__": "/metrics",
"__scheme__": "http",
"__scrape_interval__": "15s",
"__scrape_timeout__": "10s",
"job": "cadvisor"
},
"labels": { "instance": "REDACTED_IP:8080", "job": "cadvisor" },
"scrapePool": "cadvisor",
"scrapeUrl": "http://REDACTED_IP:8080/metrics",
"globalUrl": "http://REDACTED_IP:8080/metrics",
"lastError": "",
"lastScrape": "2023-02-25T02:00:13.484940363Z",
"lastScrapeDuration": 0.095007963,
"health": "up",
"scrapeInterval": "15s",
"scrapeTimeout": …
```
=> add prometheus service widget

src/utils/proxy/handlers/credentialed.js
This PR updates the cloudflare widget to use only an API token with minimal read permissions rather than the [deprecated] and overly-broad global API key. This is a breaking change, will be indicated as such in release notes. Of course I verified this still works and [updated docs](https://github.com/benphelps/homepage-docs/pull/42/commits/0646a54806d6a9a4ab19cee0a0f0c9e5fe65510f) accordingly.
Closes #1060
=> Change: Alter cloudflare widget to use api token [Breaking Change]

public/locales/en/common.json, src/components/quicklaunch.jsx, src/pages/index.jsx
I wanted to be able to (quickly) open arbitrary URLs from Homepage.  This change adds some functionality to the quicklaunch feature so that users can input a url, ~~and then press SHIFT+ENTER to open the url.  The url will open in the window or tab corresponding to what the user has configured).  I've also added an indicator for this functionality so that a user knows when they are going to use the quicklaunch for a url.
Pressing enter while the shift button is pressed will open the url in the appropriate tab/window.~~
Edit: now
=> Add Quicklaunch feature to jump to a url

src/utils/config/api-response.js, src/utils/config/config.js, src/utils/config/docker.js, src/utils/config/kubernetes.js, src/utils/config/service-helpers.js, src/utils/config/widget-helpers.js
* Only environment variables starting with HOMEPAGE_VAR_ and HOMEPAGE_FILE_ are supported
* The value of env var HOMEPAGE_VAR_XXX will replace {{HOMEPAGE_VAR_XXX}} in any config
* The value of env var HOMEPAGE_FILE_XXX must be a file path, the contents of which will be used to replace {{HOMEPAGE_FILE_XXX}} in any config
* If a substituted value contains a variable reference it may also be replaced, but the behavior is non-deterministic
Closes #60
=> Added support for environment variable substitution

public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/ghostfolio/component.jsx, src/widgets/ghostfolio/widget.js, src/widgets/widgets.js
This change will add a new [Ghostfolio](https://github.com/ghostfolio/ghostfolio) widget. 
I'm aware that 4 requests is a lot, and I'm hoping that perhaps there's a solution to this issue that I am not seeing. I've been unable to find documentation for the Ghostfolio API, and testing with combined endpoints (e.g. `range=max&range=ytd` or `range=max,ytd`) proved unsuccessful. Perhaps it'd be possible to calculate all four values from the `max` endpoint (using the `chart` data with the `value` field), but I have yet to explore this option - I wanted to hear your thought first.
Authentication for Ghostfolio is rather cumbersome. It involves using a "Secret Token" (given on user creation time), to obtain a (JWT) Bearer token that can then be used for further requests. Since this is not …
=> Added Ghostfolio widget

src/widgets/pyload/component.jsx
=> Fix: use correct rate units for pyload

src/widgets/immich/component.jsx
Immich updated its API endpoint to return raw bytes instead of human readable data. This PR adapts the existing code to take this into account.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/22578704/224118838-a18b02ab-5629-4ed6-bc25-85271a1f89fa.png) | ![image](https://user-images.githubusercontent.com/22578704/224119144-f53f6dc3-35f3-4b9f-a5a0-466286744f7f.png) |
=> Fix: Use human readable units for storage in Immich widget

public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/emby/component.jsx, src/widgets/emby/widget.js
… #264
Closes # (#264)
pnpm lint output
Proof of testing :
when one of count or session api fails 
When no active session
When active play session
When active paused session
When playing and Pausing the session
https://drive.google.com/file/d/116BT19BRRj7USV7pnG3MQx2kCAyyrraF/view?usp=share_link
=> Feature: support optional media counts in jellyfin / emby widgets

src/components/widgets/resources/cpu.jsx, src/components/widgets/resources/disk.jsx, src/components/widgets/resources/memory.jsx
Closes #1110
After:
Current:
Closes #1110
=> Fix: Add padding to values in resources widget

src/utils/proxy/handlers/credentialed.js, src/widgets/nextcloud/widget.js
Adds support for Nextcloud's NC-Token authentication. This is safer than user+pass, as the only purpose of this token is to access the serverinfo endpoint, AFAIK.
Closes #1122
https://github.com/benphelps/homepage-docs/pull/60
=> Add support of NC-Token to Nextcloud widget

.devcontainer/devcontainer.json, .gitignore, src/widgets/docker/component.jsx, src/widgets/docker/stats-helpers.js
Hi!
Current implementation of stats for Docker containers displays total memory including cache, which in some cases might be really off compared to currently used memory. 
This change aligns used memory calculation with formula provided in [Docker API docs](https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerStats) (see `used_memory` formula)
Example:
I have a container which due to its nature caches a lot of memory, but does not use much in general (screen from Portainer):
Before change: 
After change:
I also took a liberty to bump base image in devcontainer to allow developing on ARM64-based machines. Microsoft started providing ARM64 images starting from bullseye.
=> Display Docker container's used memory instead of total memory

src/utils/config/docker.js
Adds the ability to use TLS key/cert to connect to remote docker instances, rather than only supporting plaintext HTTP connections.
=> Feature: support for Docker TLS based connections

package.json, pnpm-lock.yaml, public/locales/en/common.json, src/components/widgets/glances/glances.jsx, src/components/widgets/resources/cputemp.jsx, src/components/widgets/resources/disk.jsx, src/components/widgets/resources/memory.jsx, src/components/widgets/resources/resources.jsx, src/components/widgets/resources/uptime.jsx, src/pages/api/widgets/glances.js, src/pages/api/widgets/resources.js
This revamps the resources widget (edit: and glances):
- Changes from node-os-utils to https://github.com/sebhildebrandt/systeminformation 
- I didn't see any issues with this swap
- Adds cpu temp (requires additional package for macOS running from source)
- Allows for imperial or metric (default)
- Adds uptime
- For this one currently there's nothing extra when the widget is 'expanded'
Welcome any feedback of course. Would be good to get this tested to make sure works ok in other platforms (e.g. when running from source)
Temp:
Expanded:
Uptime:
Glances:
Closes #240 
Closes #86
=> Feature: updated resources widget with cpu temp + uptime

src/utils/config/service-helpers.js, src/widgets/diskstation/component.jsx
Implements proposal I made in https://github.com/benphelps/homepage/issues/1167. Allows user to specify which volume's free space to display on Diskstation widget
The change is backwards compatible, if user does not specify volume, then first volume from the list will be displayed.
Closes #1167
=> Add option to specify volume in Diskstation widget

src/utils/config/service-helpers.js
*Please excuse the duplicate PR, I messed up the last one!*
This adds support for Traefik IngressRoute CRDs as well as the traditional Kubernetes Ingress manifest.
A check for Traefik IngressRoute objects is carried out and if found, will then check for the `href` attribute set in annotations. If found, it will push the IngressRoute object into the existing `ingressList.items` array.
The reason for the `href` requirement is the matching rule that IngressRoute can be tricky to parse, and it seems better to rely on the user to set it. If it is not set, it will not be added to the `ingressList` for later processing.
A log error has been added for failing to find IngressRoute objects, but this could be only set via an additional Homepage setting.
Closes #906
Documentation PR: …
=> Feature: Add Traefik IngressRoute support for Kubernetes

Dockerfile, docker-entrypoint.sh, src/pages/api/hash.js, src/utils/config/config.js
Perhaps just needed some time to meditate on this but I think this is a true solution here. Using similar logic from #963, this PR inserts a timestamp into the hash which gets set by docker-entrypoint.sh i.e. on container start. The only real downside of this that I can think of is that revalidate will happen even when the container is _restarted_ not just _re-created_, but actually... that seems totally acceptable =)
There's another (not really directly related) change in here just to make settings.yaml creation consistent with others
Fixes #576 , like for reals
=> True fix for settings revert after container creation

src/components/services/item.jsx, src/utils/config/service-helpers.js
Combined with https://github.com/benphelps/homepage/commit/7aa496f66f0962495c98a1a3ee0814f835d985aa this PR allows expanding docker stats globally with (`showStats: true` in settings.yaml) or per-service (with `showStats: true` in the service config). In my testing theres a delay for the stats but not an unreasonable one and with anything like this its users-choice.
Closes #390
=> Feature: Global & per-service docker stats control

public/locales/en/common.json, src/components/services/widget/container.jsx, src/widgets/components.js, src/widgets/homeassistant/component.jsx, src/widgets/homeassistant/proxy.js, src/widgets/homeassistant/widget.js, src/widgets/widgets.js
This change will add a new [Home Assistant](https://www.home-assistant.io/) widget.
There is some discussion about it and further information [here](https://github.com/benphelps/homepage/discussions/1246).
The widget is a bit unusual as it allows user defined information from Home Assistant to be displayed. It defaults however to displaying some basic information without custom configuration by the user.
There is a custom proxy handler but only one useWidgetAPI call is needed in component.jsx. The component is then dynamically created with the information returned.
*This is my first ever PR so I hope I didn't mess anything up.*
*This is also my first ever JS code so I more than welcome any changes/improvements/comments.*
=> Added homeassistant widget

src/components/widgets/glances/glances.jsx
See API output from linked issue, PR is to include sensors labeled "Tctl"
Closes #1375
=> Fix: Glances include cpu tempts labeled `Tctl`

src/pages/index.jsx
I like this idea to allow more customization of background images, this is of course backwards compatible but can now specify:
```yaml
background: 
image: https://images.unsplash.com/photo-1681802731183-c07ee779dabd
blur: sm # sm, "", md... see https://tailwindcss.com/docs/backdrop-blur
saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
opacity: 50 # 0-100
```
yields :
Closes #1378
=> Feature: support blur, saturation & brightness filters for background images

src/widgets/transmission/proxy.js, src/widgets/transmission/widget.js
[Transmission allows setting the RPC url path](https://github.com/transmission/transmission/blob/e68c72daa479f81d519fb83219aedc81d1516fb9/docs/Editing-Configuration-Files.md#L128) to something other than the default `/transmission/`. Changing this value can be necessary when doing some types of routing (e.g. `transmission.custom-domain.com`) to get the web front end to function properly.
The Transmission widget in Homepage hardcodes the value to the default and doesn't allow modifying it. This small refactor creates an `rpcUrl` optional prop on the Transmission widget that can be set to the same value as the `rpc-url` value in your Transmission `settings.json` file. If unset, the widget will use the default value of `/transmission/`.
=> Allow setting rpcUrl path for Transmission widget

public/locales/en/common.json, src/widgets/channelsdvrserver/component.jsx, src/widgets/channelsdvrserver/widget.js, src/widgets/components.js, src/widgets/widgets.js
This adds a new service widget for [Channels DVR Server](https://getchannels.com/dvr-server/) that powers [Channels](https://getchannels.com)
Docs pull: https://github.com/benphelps/homepage-docs/pull/79
https://github.com/benphelps/homepage/discussions/1385
=> Add Channels DVR Server widget

src/utils/config/service-helpers.js
I swore I fixed this already then it broke again...
Closes #1395
=> Fix: quick launch services show as bookmarks

src/components/resolvedicon.jsx
Closes #1404 
This adjusts the CSS for icons to ensure that if they are taller than they are wide, they are constrained to a 32x32 icon
Before:
After:
=> force icons to fit withing a 32x32 square

public/locales/en/common.json, src/widgets/plex/component.jsx, src/widgets/plex/proxy.js
With this change album count of the music library of Plex is added to Plex widget...
=> Feature: add albums to Plex service widget

src/components/services/item.jsx
Fix misalignment of services and widgets...
Before: ![imatge](https://user-images.githubusercontent.com/13131391/234815885-46a89025-08fa-49ed-bb15-439711700764.png)
After: ![imatge](https://user-images.githubusercontent.com/13131391/234816365-90090197-dda7-4d70-99af-2d9955e72587.png)
=> Fix: align services and widgets

src/components/resolvedicon.jsx
I was setting up my homepage bookmarks to use material icons and there were two things that I wanted to address. The mask gradient wasn't the aesthetic I was going for and I saw a deprecation warning for most if not all of the brand icons in the material design icon set that I wanted to use.
I didn't look to see when the deprecation will go into effect but I don't think it hurts to implement something like this ahead of time.
Deprecation warning can be seen here; https://pictogrammers.com/library/mdi/icon/reddit/
Github Issue from maintainer with list: https://github.com/Templarian/MaterialDesign/issues/4901
I wanted to add support for simple-icons as suggested in the message from the mdi maintainer. The way that I implemented it anticipates support for other prefixes and should be …
=> Add Support for Simple Icons + Add optional theme colors for icons

src/components/resolvedicon.jsx
I encountered an issue with `iconStyle: theme` where for the service section icons, `--tw-text-opacity` was not set. I believe this was because since they aren't clickable they weren't nested in the hover css class which makes that var available. I am unsure why I didn't encounter this in my testing before. This PR adds a fallback so it will use the opacity if defined otherwise it will be opaque.
=> fallback for --tw-text-opacity

src/pages/index.jsx
When no bookmarks or no services configured in your homepage, some space can be saved...
=> Fix: save space when services or bookmarks are not in use

public/locales/en/common.json, src/components/services/widget/container.jsx, src/widgets/nextcloud/component.jsx
I find that `CPU Load` and `Memory Usage` are pointless to query from Nextcloud, seeing as we have other ways to get that information from the system hosting it (resources, glances, etc.). So I've replaced them with `Files` and `Shared`.
Also adds a setting to the widget to choose the last active range (5 minutes, 1 hour, 24 hours).
=> Replace fields in Nextcloud widget with file count and shared item count

public/locales/en/common.json, public/locales/it/common.json, src/widgets/pihole/component.jsx, src/widgets/pihole/widget.js
Added a new block in the PiHole widget that shows the percentage of blocked queries as shown in the PiHole's admin page.
=> PiHole widget: added new Percentage block

public/locales/en/common.json, src/widgets/components.js, src/widgets/qnap/component.jsx, src/widgets/qnap/proxy.js, src/widgets/qnap/widget.js, src/widgets/widgets.js
Add basic support for QNAP NAS. Should support majority of current gen devices.
Simply provide widget details as following:
```yaml
widget:
type: qnap
url: http://qnap.host.or.ip:port
username: user
password: pass
```
[[Feature Request] - Qnap Storage Widget](https://github.com/benphelps/homepage/discussions/1463)
[Widget for qnap](https://github.com/benphelps/homepage/discussions/1028)
https://github.com/benphelps/homepage-docs/pull/91
=> Prelim support for QNAP NAS

src/widgets/changedetectionio/component.jsx
When a "changedetection.io" widget is visible on the screen, it caused an error, because while it was waiting for the API data, it returned a "Container" component without children, causing below.
And now with this fix returns Block components as children without values.
=> Fix Slice error on container.jsx

src/utils/proxy/http.js
Missing a colon between `host:port` in the error message.
=> error hostname:port/path was missing colon

tailwind.config.js
=> Fix: Include backdrop classes in css build

src/pages/index.jsx
=> Fix: background filters are not full height

public/locales/en/common.json, src/widgets/components.js, src/widgets/pialert/component.jsx, src/widgets/pialert/widget.js, src/widgets/widgets.js
This PR introduces the new PiAlert widget that pulls stats from PiAlert's APi (https://github.com/jokob-sk/Pi.Alert).
The user will be able to add the widget to the services.yaml file using the following configuration:
```yaml
widget:
type: pialert
url: http://ip:port
```
The PiAlert's API are not documented, I am using as endpoint /php/server/devices.php?action=getDevicesTotals, that returns the following response:
```js
[30,22,0,0,0,0]
```
It is an array where each item corresponds respectively to AllDevices, Connected, Favorites, NewDevices, DownAlerts, Archived.
=> Added PiAlert widget [WIP]

public/locales/en/common.json, src/components/widgets/glances/glances.jsx, src/pages/api/widgets/glances.js, src/utils/config/widget-helpers.js
Enhance the glances widget to include the ability to display disk(s) and mirror the style and structure of the resource widget.
Closes #672
=> Enhanced glances widget

src/widgets/qnap/component.jsx
Some what noted by @ToqQrrlin a comment on https://github.com/benphelps/homepage/pull/1470#issuecomment-1556388243 I had used CPU temp, when I should have system temp.
CPU temp is also not available in older QNAPs.
This pull request switches to using the correct temperature sensor to match the system temp output.
https://github.com/benphelps/homepage/pull/1470#issuecomment-1556388243
=> Correctly use sys_tempc instead of cpu_tempc in QNAP widget

src/widgets/homeassistant/proxy.js
See 
E.g. 
```
homepage.widget.custom=[{"template":"{{states.cover|selectattr('state','equalto','closed')|list|length}}/{{states.cover|list|length}}","label":"Garage Doors"},{"state":"alarm_control_panel.alarm_control_panel","label":"Alarm System"}]
```
Closes #1544
=> Fix: support using docker labels for HASS widget custom

src/utils/config/config.js
See linked issue. Should be backwards compatible
New syntax is e.g., I'll update the docs:
```yaml
layout:
- Group1:
- Group2:
- Group3:
style: row
columns: 3
```
Closes #1546
=> Enhancement: support settings layout as a list

src/widgets/qbittorrent/proxy.js
=> Fix: Properly encode qbittorrent credentials

src/pages/api/widgets/kubernetes.js
=> Fix: Handle k8s widget metrics call fails

src/utils/config/service-helpers.js
Docker services with dynamic labels that have environment vars like HOMEPAGE_VARS_XXX and HOMEPAGE_FILE_XXX are not parsed currently. This ensures all labels are checked for applicable replacements.
~~NOTE: This bug likely still exists in the Kubernetes function. I do not have a Kubernetes environment to test with.~~
Closes #1553
=> Enhancement: substitute environment vars in container labels

src/utils/proxy/handlers/credentialed.js, src/widgets/paperlessngx/widget.js
According to the [Paperless-ngx documentation ](https://docs.paperless-ngx.com/api/#authorization) the API endpoint support either via username/password or a token. 
This PR adds support for using a token instead of username/password.
Closes # (no issue)
=> Enhancement: add support for auth token in paperless-ngx widget

src/utils/proxy/use-widget-api.js, src/widgets/lidarr/component.jsx
=> Fix: potentially avoid `album` api call in lidarr widget, allow useWidgetAPI to not actually send a request

src/utils/config/service-helpers.js
The current implementation of service detection focuses on containers. However when using Docker Swarm this limits automatic service detection to the containers running on the same node as homepage (or docker-proxy). Detecting other services in the docker swarm is with the current implementation not possible.
This commit fixes this by getting the appropriate labels from services when Docker swarm is configured in the config file. This ensures that the appropriate labels are gathered from the service definition instead of the container definiation, thus allowing for automatic service detection for the entire Docker swarm. Please note that in order for this to function the homepage (or dockerproxy) should be running on a manager node. Only the manager node is able to gather all the relevant …
=> Fix: use service labels instead of container for service discovery with Docker Swarm

src/components/services/widget/error.jsx, src/widgets/kubernetes/component.jsx, src/widgets/portainer/component.jsx
Fixes for portainer when the environment is offline, and kubernetes widgets when it tries to pass error message.
A change in https://github.com/benphelps/homepage/pull/1437 broke the error output when services are behind the reversed proxy as proxy will return buffer data instead, so original code was working as intended.
=> Fixes for portainer and kubernetes and error component

src/components/services/group.jsx, src/components/services/item.jsx, src/components/services/list.jsx, src/components/services/ping.jsx, src/pages/api/ping.js, src/pages/index.jsx, src/utils/config/service-helpers.js
Changes the ping feature to not receive the URL from query params but rather just service group / name (which is what we use to 'find' services) and pulls the URL from service item itself. Closes potential security concern as noted in linked issue. Tested with dynamic services as well, since this does touch that code (we now need to pass `group.name` all the way down)
Closes #1599
=> Fix: Retrieve ping url from config rather than as query parameter

src/components/services/group.jsx, src/pages/index.jsx, tailwind.config.js
This allows for collapsible `ServiceGroup` objects in the UI.  I have introduced an optional configuration value in the `settings.yaml` file to control this.  `disableCollapse: true` (defaults to `false`) will disable the component that collapses the different `ServiceGroup` sections.
This can also be included in `BookmarksGroup` at a later date.  The configuration option can also be included at the individual group level at a later date.
Closes #1210
=> Feature: collapsible layout sections

src/utils/proxy/http.js
Adds zlib flushing configuration options.
Assuming that I understand the zlib documentation correctly, the EOF sequence may be omitted in some cases ([docs](https://www.bolet.org/~pornin/deflate-flush.html#:~:text=the%20sender%20can%20omit%20it)). Using the sync flush flag will handle that. I took a peek at some other http libraries ([axios](https://github.com/axios/axios/blob/v1.x/lib/adapters/http.js#L28-L31), [request](https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/request.js#L1018-L1025)) and it appears that they always use those flags.
Closes #1609
This is a little odd to test and there's some hoops to jump through.
1. Force gzip compression by adding this [before the request is made](https://github.com/benphelps/homepage/blob/main/src/utils/proxy/htt …
=> Handle missing EOF when decompressing responses

src/pages/api/hash.js, src/utils/config/api-response.js, src/utils/config/config.js, src/utils/config/docker.js, src/utils/config/kubernetes.js, src/utils/config/service-helpers.js, src/utils/config/widget-helpers.js, src/utils/logger.js
Until this change, the config directory was assumed to be located at '$PWD/config'. This patch retains that default behaviour, but enables users/devs to override that behaviour by setting the HOMEPAGE_CONFIG_DIR variable.
=> Override config directory with env var.

src/pages/api/services/proxy.js, src/utils/config/service-helpers.js, src/widgets/coinmarketcap/component.jsx, src/widgets/coinmarketcap/widget.js
This allows specifying `slug` with coinmarketcap since crypto does dumb things like reuse their crypto symbols. So this supports e.g.
```yaml
widget:
type: coinmarketcap
slugs: [chia-network, uniswap]
defaultinterval: "1h"
key: ...
```
Closes #1683
=> Feature: support coinmarketcap slugs

public/locales/en/common.json, src/widgets/tautulli/component.jsx
Return an empty widget when tautulli's response data object is empty. This is a fix for when tautulli can't reach plex. The response looks like the following when it can't reach plex, which causes the `sort` option to error out.
```json
{
"response": {
"result": "success",
"message": null,
"data": {}
}
}
```
Closes #713
=> Fix: Handle tautulli response when unable to connect to Plex

public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/azurePipelines/component.jsx, src/widgets/azurePipelines/widget.js, src/widgets/components.js, src/widgets/widgets.js
Add new service widget - Azure pipelines. 
use to monitor specific pipeline running status and see it buildId.
Closes #1700
=> Adding Azure Pipelines

src/components/services/widget/container.jsx
=> Fix: error when fields specified via labels in 0.6.23

src/components/bookmarks/group.jsx, src/components/services/group.jsx
Improves the new collapse feature with a more modern drawer slide animation. It also allows the document to transition the layout of elements at the same time. This results in a much less jarring collapse than before where suddenly the page would shift after the animation completed. This was especially apparent for larger sections.
Please see a demo video blow
https://github.com/benphelps/homepage/assets/6865942/7e822850-7358-4560-a286-52ad27ca504f
This change was tested and works as expected for both mobile and desktop, but I don't have a mobile recording. Others can test on mobile or desktop currently on my personal `homepage` instance if they want. (URL upon request as I don't want to appear to self-promote)
Minor improvement to a recently introduced feature.
=> Improve disclosure collapse animation

src/components/widgets/logo/logo.jsx
Was broken by https://github.com/benphelps/homepage/pull/1603 , only applies with custom logo (and a certain concoction of widgets)
Closes #1720
=> Ensure spacing with custom logo

src/components/resolvedicon.jsx
Enables appending a color code (e.g. "#123456") to all mdi and si icons, in order to change their color to a per-icon custom one.
If no color code is appended, defaults to current behaviour (depending on theme setting).
Example: mdi-folder-#123456
=> Support custom colors for icons

src/components/widgets/resources/cpu.jsx, src/components/widgets/resources/cputemp.jsx, src/components/widgets/resources/disk.jsx, src/components/widgets/resources/memory.jsx, src/components/widgets/resources/resources.jsx, src/components/widgets/resources/uptime.jsx
Adds the option to set a custom refresh rate for the resource widget. It reads the "refresh" setting in the widget options and, if it is a number, sets the refresh rate to this number. In case it is not a number, it defaults to the previous behavior (default refresh rate of 1500 ms).
=> Enable custom refresh rate for resource widget

src/components/widgets/widget/resource.jsx
=> Fix: usage bar 0% displays '0'

src/components/services/widget/container.jsx
=> Fix: handle service container stopped causes crash in v0.6.24

src/components/widgets/glances/glances.jsx
=> Fix: glances widget disk loading blocks remain after load

src/components/bookmarks/item.jsx, src/components/services/item.jsx
Adds a visual setting to give cards a backdrop-blur option
This uses a new setting in settings.yaml named `cardBlur` which works the same way as background.blur
Supported options are sm, md, etc. from tailwind
The downside is that you cannot apply multiple backdrop-effects, thus this only works when backdround blur saturation and brightness are disabled.
This is only an issue when the cardBlur option is used, and could be clearly described in the documentation
[Documentation Pull Request](https://github.com/benphelps/homepage-docs/pull/133)
#1644
- [ - ] New service widget
- [ - ] Bug fix (non-breaking change which fixes an issue)
- [ ✔️ ] New feature (non-breaking change which adds functionality)
- [ ✔️ ] Other (please explain)
- [ ✔️ ] If adding a service widget or a …
=> Feature: card blur background option

src/widgets/glances/metrics/memory.jsx
=> Fix glances metrics widget memory units

src/components/services/group.jsx
Allows for hiding section headers, as well as lowering the padding between these sections.
Before, without:
After, with:
=> allow hiding section headers

src/utils/config/service-helpers.js, src/widgets/components.js, src/widgets/mjpeg/component.jsx, src/widgets/mjpeg/widget.js, src/widgets/widgets.js
Adds a new mjpeg stream widget.  Simply displays the stream in the same box area as the glances graphs, so it mixes with those well.
Looks like this:
Adds a new `mjpeg` widget type.
=> Feature: mjpeg stream widget

public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/components.js, src/widgets/openmediavault/component.jsx, src/widgets/openmediavault/methods/downloader_get_downloadlist.jsx, src/widgets/openmediavault/methods/services_get_status.jsx, src/widgets/openmediavault/methods/smart_get_list.jsx, src/widgets/openmediavault/proxy.js, src/widgets/openmediavault/widget.js, src/widgets/widgets.js
Widget for integration with OpenMediaVault (https://github.com/benphelps/homepage/discussions/1204)
```yaml
- OpenMediaVault:
- Services:
widget:
type: openmediavault
url: http://
username: admin
password: pass
method: services.getStatus
- S.M.A.R.T.:
widget:
type: openmediavault
url: http://
username: admin
password: pass
method: smart.getListBg
- Downloader Plugin:
widget:
type: openmediavault
url: http://
username: admin
password: pass
method: downloader.getDownloadList
```
OMV RPC docs: https://docs.openmediavault.org/en/6.x/development/tools/omv_rpc.html
Real docs: [Source Code on GH](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/engined/rpc)
=> OpenMediaVault widget

public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/mealie/component.jsx, src/widgets/mealie/widget.js, src/widgets/widgets.js
Adds a widget for [Mealie](https://mealie.io/) self-hosted recipe management app.
Mealie has a [well-documented API](https://nightly.mealie.io/api/redoc/) that exposes two endpoints that can be queried for statistics. I chose to query the group `Get Statistics` API that returns:
```json
{
"totalRecipes": 0,
"totalUsers": 0,
"totalCategories": 0,
"totalTags": 0,
"totalTools": 0
}
```
I omitted `totalTools` to keep with the Homepage standard of limiting widgets to four fields. The group `Get Statistics` API can be queried with a user-generated long-lived API token.
The other option would be to query the admin `Get Admin Statistics` that returns:
```json
{
"totalRecipes": 0,
"totalUsers": 0,
"totalGroups": 0,
"uncategorizedRecipes": 0,
"untaggedRecipes": 0
}
```
This API can be queried by …
=> Feature: mealie widget

src/components/widgets/widget/container.jsx, src/pages/index.jsx
=> Fix: apply cardBlur to header boxed / boxedWidgets

README.md
Add user:group 1000:1000 to the docker compose, to match host user. Restart container unless stopped.
Change the default user. When mounting files from the host, it's better to match the host user:group. Usually that is 1000:1000, which makes it a good default.
When deploying this container, the user usually want to keep the container running persistently, hence the restart unless stopped.
Change example docker-compose in README.
=> Add user and restart options to docker-compose

src/pages/api/services/proxy.js, src/utils/proxy/handlers/generic.js
Adds support for specifying `headers` to be added to proxied requests for widgets.
=> Enhancement: support extra headers in widgets

src/utils/proxy/handlers/generic.js
Adds the ability for service widgets to set custom headers or method. This is specifically meant for the new `customapi` widget, but I left it generic affecting all widgets, feel free to change this. I think this is important to have at least for `customapi` in order to handle cases like non-basic authorization or custom key header authorizations for APIs.
Addresses comment https://github.com/benphelps/homepage/pull/1858#issuecomment-1694243842
```yml
- Syncthing:
icon: mdi-sync
widget:
type: customapi
url: http://syncthing:8384/rest/svc/report
headers:
X-API-Key: key-redacted
mappings:
- field: totMiB
label: Stored (MB)
format: number
- field: numFolders
label: Folders
format: number
- field: totFiles
label: Files
format: number
- field: numDevices
label: Devices
format: number
```
=> Allow widgets to add headers or set method

src/utils/config/service-helpers.js
Two parts here:
1. Do not pollute logs if list cluster object on traefik returns 404, they resources likely are simply not there and lack of their existence would bring host of other problems that would be far more "loud" than an error log in one pod.
2. Do not use fall back logic using try  catch, if both exist in cluster unexpected behaviour can occur.
P.S. Although I am a developer by day I rarely ever touch javascript so there is a chance i did something stupid, please double check my changes.
Closes https://github.com/benphelps/homepage/issues/1874
=> Making both Containo and Io work regardless if they are both present or not

public/locales/en/common.json, src/widgets/components.js, src/widgets/uptimerobot/component.jsx, src/widgets/uptimerobot/widget.js, src/widgets/widgets.js
Add a service widget for UptimeRobot.com. User may choose between a summary of multiple monitors, or details of a single monitor.
Closes #1827 
See #1846
Multiple monitors:
Single monitor, currently up, with previous down time:
=> Add UptimeRobot widget

package-lock.json, package.json, pnpm-lock.yaml
This PR updates the GameDig dependency to the latest as of writing, `4.0.7`, this update includes support for 14 games, a minor bugfix and updated dependencies to fix potential vulnerabilities.
Related: @sahara101 asked about Sons Of The Forest support for this project on the GameDig repository: https://github.com/gamedig/node-gamedig/issues/346
=> Update GameDig dependency to 4.0.7

src/pages/_document.jsx
I'm using the Traefik proxy to connect to Homepage with Authentik as the Forward Auth service. Everything works perfectly except for fetching the manifest file because it doesn't send cookies.  
The solution is to add `crossorigin="use-credentials"` to the `link` tag. 
Documented here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
Based on: https://github.com/home-assistant/frontend/issues/940
=> Add crossorigin="use-credentials" to manifest link tag.

src/components/widgets/widget/container.jsx
=> Fix: cardBlur with boxedWidgets shrinks search widget

src/pages/index.jsx
This builds on top of #1902 by allowing mixing of bookmark & service groups. A couple notes:
- Any service groups or bookmark groups that aren't included in `layout` are still built like they currently are
- If a bookmark group & service group have the same name, the service wins
e.g.
```yaml
layout:
Glances Viz:
style: row
columns: 2
icon: glances.png
Developer Tools:
style: row
columns: 3
Media:
Home Management & Info:
icon: home-assistant.png
Server Tools:
icon: https://cdn-icons-png.flaticon.com/512/252/252035.png
Downloaders:
```
See #89 #804 #1235
=> Enhancement: mixed bookmarks / services layout

public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/glances/components/container.jsx, src/widgets/glances/metrics/cpu.jsx, src/widgets/glances/metrics/disk.jsx, src/widgets/glances/metrics/fs.jsx, src/widgets/glances/metrics/gpu.jsx, src/widgets/glances/metrics/info.jsx, src/widgets/glances/metrics/memory.jsx, src/widgets/glances/metrics/net.jsx, src/widgets/glances/metrics/process.jsx, src/widgets/glances/metrics/sensor.jsx
Adds a new `chart: false`, glances alternative view.  These are "half-height", or the same height as a service with no widget at all, and do not render a chart.
This change also brings the `fs` widget normal view into line with the others, that was an experiment that I was never very happy with.
=> mini-non-chart charts

src/widgets/glances/metrics/cpu.jsx
Fixes occasional 
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'linux_distro')
```
on startup
=> Fix: error in glances cpu when system data not available yet

src/pages/api/ping.js, src/utils/proxy/cookie-jar.js, src/utils/proxy/handlers/generic.js
Take any cookies that are present on the request to endpoints such as `api/ping` and `api/services` and add them to the cookie jar. This means that services that are behind authentication such as authelia can be pinged and used in widgets.
The way this is done probably isn't overly correct - but it works for my usage. I thought I'd make an MR anyway to see if there was any interest in this feature.
Closes #1797
=> Forward cookies from request

src/widgets/pterodactyl/component.jsx
Service Widget: Pterodactyl
Fixing a math issue which result in just representing the last node server count.
Closes #1937
=> Fix: Service Widget Pterodatyl | Total servers only representing last node

.dockerignore, Dockerfile, package-lock.json, package.json, pnpm-lock.yaml
This PR updates the GameDig dependency to the latest as of writing, `4.1.0`, this update includes support for 4 games, but most importantly, replaces the `compressjs` dependency with an equivalent library, thus fixing #1795 (already fixed with a hack, this pr also reverts #1811).
=> Update GameDig dependency to `4.1.0` and revert compressjs fix.

src/pages/site.webmanifest.jsx
For browsers to provide the option to install a website as an app, the manifest must meet certain requirements. One of the requirements is the `start_url` property.
Added `start_url` in `manifest.json` to fulfill requirements for installable app. Value of this property can be controlled from settings.yaml or if emitted it will fallback to `"/"`.
=> Added start_url in manifest.json to fulfill requirements for installable app

src/components/tab.jsx, src/pages/_app.jsx, src/pages/index.jsx, src/utils/config/service-helpers.js, src/utils/contexts/tab.jsx
This pull request implements tabs when `tab:`  is defined in the layout configuration for at least single service/bookmark group (as suggested in https://github.com/benphelps/homepage/discussions/1316#discussioncomment-6165188).
Tabs will sort based on the order in the layout block. 
If there are no tabs defined, all services/bookmarks groups will be shown. 
If the group doesn't have a tab definition, it will be shown on every tab.
Every tab can be accessed directly by visiting Homepage URL with `#Group name` at the end of the URL.
I had a bit of trouble making a design of the tabs to look similar to the rest of the UI (using any colour), but I'm no designer so any suggestions or CSS changes are welcome. 
https://github.com/benphelps/homepage/assets/5442891/ffcacab6-9b49-4296-affe-54440ecc …
=> Feature: tabbed layouts

src/widgets/customapi/component.jsx
I've got an [OpenEVSE](https://openevse.com/index.html) at home that I wanted to integrate with Homepage. It exposes a `/status` endpoint that returns JSON, so I [wrote a new widget](https://github.com/benphelps/homepage/compare/main...greglook:benphelps-homepage:openevse-widget) for it... then saw that the project only wants new widgets with a certain number of upvotes. :sweat_smile: 
So instead I decided to take a different approach, using the new `customapi` widget. Currently, the options for displaying data are pretty much limited to the label applied and a couple of format options. I'd like to be able to do some transformations on the values before displaying them, as well as applying unit strings to the fields. To that end, I've added a couple of new extensions to the `customapi` …
=> Add remap, scale, and suffx to customapi fields

src/components/tab.jsx, src/pages/index.jsx
See #1981 , should sanitize these
=> Fix: slugify tab names

src/pages/index.jsx
Fixes issue for initial tab with slugified tab name.
=> Fix layouts for initial tab with slugify

src/components/tab.jsx
=> Fix: allow numbers in tab name

src/utils/config/service-helpers.js
Within #1998 we discussed that the RBAC for the Kubernetes service account currently needs the following permission to not run into errors and spam the log. 
```
- apiGroups:
- traefik.io
- traefik.containo.us
resources:
- ingressroutes
verbs:
- get
- list
```
This is needed even if you have no custom resource definitions of traefik. If you have this permission not in place the kubernetes-client in "service-helpers.js" will run into an error because you can not access the CRD. You have to add the permission to silence the alert but because you do not have the CRDs installed the next API call will fail too. Until now this was simply silenced with an statusCode != 404 if-clause. @benphelps  extended this today to exclude 403 errors which are generated if you do not have the above RBAC in …
=> Kubernetes Check for Custom Resource Definitions

src/widgets/openmediavault/methods/smart_get_list.jsx
Current OpenMediaVault widget didn't ignore device which is not monitored. This change would filter SMART result by monitor property.
=> Fix: SMART result of OMV should always from monitored devices

src/widgets/jdownloader/proxy.js
=> Fix: jdownloader remaining should be 0 after download complete

src/widgets/glances/metrics/fs.jsx
Fix Glances free fs display in widget...
Before: ![imatge](https://github.com/benphelps/homepage/assets/13131391/cf6e3a97-da5a-4eb4-bf5f-c426695cd558)
After: ![imatge](https://github.com/benphelps/homepage/assets/13131391/926d333e-9b98-4e52-b197-4a26752c523b)
=> Fix: add maximumFractionDigits to Glances free fs

src/components/services/group.jsx
=> Fix: collapsing service group prevents resize / stats

src/widgets/glances/metrics/memory.jsx
Fix Glances memory display in widget (with and without chart)...
=> Fix: add maximumFractionDigits to Glances memory

src/widgets/octoprint/component.jsx
I found a way to detect when the 3D printer is not connected, allowing us to get rid of that annoying red box.
Closes #1841
See #834 
**Before:**
**After:**
**Solution:**
The `job` endpoint returns 200 even when the printer is not connected. It also provides information that the printer is Offline. Here's an example `job` endpoint's response when the printer is not connected:
```
{
"job": {
"averagePrintTime": null,
"estimatedPrintTime": null,
"filament": null,
"file": {
"date": null,
"display": null,
"name": null,
"origin": null,
"path": null,
"size": null
},
"lastPrintTime": null,
"user": null
},
"progress": {
"completion": null,
"filepos": null,
"printTime": null,
"printTimeLeft": null,
"printTimeLeftOrigin": null
},
"state": "Offline"
}
```
=> Feature: Added detect octoprint offline printer

package-lock.json, package.json, pnpm-lock.yaml, public/locales/en/common.json, src/pages/_app.jsx, src/utils/config/service-helpers.js, src/utils/contexts/calendar.jsx, src/utils/proxy/handlers/generic.js, src/widgets/calendar/component.jsx, src/widgets/calendar/integrations/lidarr.jsx, src/widgets/calendar/integrations/radarr.jsx, src/widgets/calendar/integrations/readarr.jsx, src/widgets/calendar/integrations/sonarr.jsx, src/widgets/calendar/monthly-view.jsx, src/widgets/components.js, src/widgets/lidarr/widget.js, src/widgets/radarr/widget.js, src/widgets/readarr/widget.js, src/widgets/sonarr/widget.js
This PR implements calendar widget, with optional integrations to show events from supported widgets. This PR has support for radarr, sonarr, lidarr and readarr.
Closes #1243
Closes #1015
Closes #1200
=> Feature: calendar widget

src/utils/config/service-helpers.js, src/widgets/calendar/monthly-view.jsx
Related to calendar widget https://github.com/benphelps/homepage/pull/2077 , adds a configuration for first day of the week.
=> Added choice for first day in a week with a fix

src/components/services/item.jsx, src/components/services/ping.jsx
Adds ping indicator styles "dot" and "basic":
Closes: https://github.com/benphelps/homepage/discussions/1289
=> New ping-indicator styles

docs/widgets/services/glances.md
At https://gethomepage.dev/v0.7.0/widgets/services/glances/ the "Find the Glances information widget [here]" links back to itself instead of the info widget link, fixing that
=> Update services/glances.md with correct info/glances link

src/widgets/calendar/monthly-view.jsx
Implements "Today" action for calendar when clicking  the month name
Closes #2089
- [] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
=> Enhancement: go to current day when clicking calendar month name

mkdocs.yml
There is an extra service widgets between Immich and Jackett?
=> Documentation: Remove extra Service Widgets in new documentation

docs/configs/services.md, docs/configs/settings.md, public/locales/en/common.json, src/components/services/item.jsx, src/components/services/kubernetes-status.jsx, src/components/services/ping.jsx, src/components/services/status.jsx, src/utils/config/service-helpers.js
This finishes the job properly from #2074 
- style can be set in settings
- Ping & docker / k8s status use the same dot
- support k8s with the styles
- changes to use a rounded div with height, not ◉
- Changes ping to be up / down, cause its ping
_Will squash_
=> Enhancement: statusStyle improvements

src/components/quicklaunch.jsx, src/pages/index.jsx
This fix addresses the issue where quicklaunch shows all the services, even non-clickable ones, without a url.
=> Fix: Quicklaunch shows also services without a url

src/widgets/emby/component.jsx
=> Fix: emby / jellyfin direct stream determination with >1 stream

src/widgets/sonarr/component.jsx
Closes #1801
A queue item could end up with a different React component key after each API call.
=> Fix: sonarr widget queue duplicates

src/widgets/changedetectionio/component.jsx
If a changedetection.io watch never had a change before, the api will return `0` for `last_changed`, this is often combined with the same watch never been checked before, which would make `last_checked` also `0`, that in turn would trigger a `diffsDetected` for the widget. That's incorrect, since the watch never been checked (and also never seen any changes) before.
=> Changedetection.io: Skip checking for diff if watch never had a change

docs/configs/kubernetes.md, kubernetes.md, src/utils/config/service-helpers.js
This may have been causing some confusion. Internally homepage uses `podSelector` (it gets assigned in service-helpers) but in manifests should be `pod-selector`.
See https://github.com/gethomepage/homepage/commit/4d6ce1f7e2a8dfa99225877d74a506c5ab5f4bd1
=> Fix references to podSelector in k8s manifests

docs/widgets/services/coin-market-cap.md
Found a missing parameter in docs - "defaultinterval"
Adds missing parameter into documentation
=> Documentation: add defaultinterval option for coinmarketcap

next.config.js, src/components/services/ping.jsx, src/components/services/status.jsx, src/components/toggles/revalidate.jsx, src/components/version.jsx, src/components/widgets/glances/glances.jsx, src/components/widgets/kubernetes/kubernetes.jsx, src/components/widgets/longhorn/longhorn.jsx, src/components/widgets/openmeteo/openmeteo.jsx, src/components/widgets/openweathermap/weather.jsx, src/components/widgets/resources/cpu.jsx, src/components/widgets/resources/cputemp.jsx, src/components/widgets/resources/disk.jsx, src/components/widgets/resources/memory.jsx, src/components/widgets/resources/uptime.jsx, src/components/widgets/weather/weather.jsx, src/pages/_document.jsx, src/pages/index.jsx, src/utils/proxy/api-helpers.js, src/widgets/docker/component.jsx
Closes #2128 #539
tips:
next.config.js. add `assetPrefix: ".",`
others. mod `/api/xxx` to `api/xxx`.
thanks for @benphelps @shamoon guides. #2194
I am learning to contribute code & PR. If there are any mistakes, I kindly request guidance from everyone.
=> Fix: subdirectory deployment

src/components/tab.jsx
=> Fix: Tab spacing on mobile

docs/configs/services.md, docs/configs/settings.md, package-lock.json, package.json, pnpm-lock.yaml, public/locales/en/common.json, src/components/services/item.jsx, src/components/services/ping.jsx, src/components/services/site-monitor.jsx, src/pages/api/ping.js, src/pages/api/siteMonitor.js, src/utils/config/service-helpers.js
I've always been a little annoyed (at myself) that ping isn't a real ping and as noted in the linked request, at least some people want it. So I'm proposing (or at least considering) that we:
- Make ping true ping, using a tiny wrapper module for system `ping`. AFAIK almost all systems will have this available. Options may differ across platforms but we're using the absolute basics.
- Rename the current ping functionality to 'site monitor' (`siteMonitor`) since thats more actually what it is.
This is _kind of_ breaking:
- Current users will now use true `ping`, that said, the implementation here does still accept the URL, so it should work but results will be different than before.
This isn't like, the most important thing to me in the world, but I think it's 'worth' the hassle. But open …
=> Feature: true ping, rename old ping to siteMonitor

docs/widgets/services/calendar.md, src/pages/_app.jsx, src/utils/config/service-helpers.js, src/utils/contexts/calendar.jsx, src/widgets/calendar/agenda.jsx, src/widgets/calendar/component.jsx, src/widgets/calendar/integrations/lidarr.jsx, src/widgets/calendar/integrations/radarr.jsx, src/widgets/calendar/integrations/readarr.jsx, src/widgets/calendar/integrations/sonarr.jsx, src/widgets/calendar/monthly-view.jsx, src/widgets/calendar/monthly.jsx
This PR adds agenda view for calendar, contains additional improvements to show when event has completed status (for example media has available file),  and add additional configuration to limit number of events in the event list.
Closes #2106
Closes #2097
=> Feature: Added agenda view for calendar, calendar improvements

docs/widgets/services/customapi.md, next-i18next.config.js, public/locales/en/common.json, src/widgets/customapi/component.jsx
* Add date formatting option
Before:
After:
* The date format will be parsed from the `dateStyle` property (default value: `long`):
```yaml
...
- field:
time_entries:
0: created_on
label: Created at
format: date
dateStyle: long
...
```
=> Feature: add date formatting option in custom api

src/styles/theme.css
But really, does anyone use the white theme?
Closes #2239
=> Fix: override some colors for white theme

src/widgets/authentik/widget.js
Has nothing to do with uuid, seems their new versions enforce the trailing slash
Closes #2243
=> Fix authentik users endpoint URL

src/widgets/calendar/component.jsx, src/widgets/calendar/integrations/lidarr.jsx, src/widgets/calendar/integrations/radarr.jsx, src/widgets/calendar/integrations/readarr.jsx, src/widgets/calendar/integrations/sonarr.jsx
=> Fix: Respect hideErrors for Calendar widget

docs/widgets/services/customapi.md, src/widgets/customapi/component.jsx
- Added timeStyle option to custom API service.
- If no timeStyle option is set, only the date is shown.
Example: (November 8, 2023 at 7:00:00 PM)
```yaml
widget:
type: customapi
...
mappings:
- field: key
label: Field 4
format: date
dateStyle: long
timeStyle: medium # optional - Allowed values: `["full", "long", "medium", "short"]`.
```
=> Feature: Added timeStyle to date format for custom API

src/pages/index.jsx
This changes allows the user to search for the string in the clipboard by pasting it into Homepage.
=> Enhancement: open the searchbox on paste

src/pages/_document.jsx, src/pages/index.jsx
=> Fix: dont set pinned icon if custom favicon

src/widgets/docker/component.jsx, src/widgets/docker/stats-helpers.js
I believe this is in fact correct, see https://github.com/docker/cli/issues/647
E.g. with the data from the linked issue:
Closes #2333
=> Fix: sum throughput data for docker stats

docs/widgets/info/longhorn.md
Add details for how to specify longhorn auth
Had to dig into the source code to find the keys "username" and "password". Adding to documentation to (hopefully) have less digging for others.
=> Documentation: add Longhorn example

docs/configs/docker.md, docs/configs/settings.md, src/utils/config/service-helpers.js
Adds support for scoping docker labels to specific homepage instances.
To limit a label to an instance, insert `.instance.{{instanceName}}` after the `homepage` prefix.
```yaml
labels:
- homepage.group=Media
- homepage.name=Emby
- homepage.icon=emby.png
- homepage.instance.internal.href=http://emby.lan/
- homepage.instance.public.href=https://emby.mydomain.com/
- homepage.description=Media server
```
In this example it is used with two homepage instances for internal and public access.
=> Enhancement: Add service discovery support for multiple homepage instances

docs/widgets/services/gluetun.md
Add more details to the Gluetun's widget page:
* Converted the note about the HTTP control server to an [admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/).
* Added more details about the default `8000` port number.
=> Update the Gluetun widget docs to have more details

src/utils/config/service-helpers.js, src/widgets/glances/metrics/cpu.jsx, src/widgets/glances/metrics/disk.jsx, src/widgets/glances/metrics/fs.jsx, src/widgets/glances/metrics/gpu.jsx, src/widgets/glances/metrics/info.jsx, src/widgets/glances/metrics/memory.jsx, src/widgets/glances/metrics/net.jsx, src/widgets/glances/metrics/process.jsx, src/widgets/glances/metrics/sensor.jsx
Add support for configurable refresh interval and amounts of points for the Glances service widget.
``` services.yaml
-CPU:
widget:
type: glances
url: http://url:port
metric: cpu
refreshInterval: 2500
pointsLimit: 50
```
This opens 2 possibilities, mainly useful for people with a home that stays open for a long period:
- Reduce the number of API calls by increasing the interval.
- Have different monitored periods (see below)
**A small note about network / disk**
Information about IO/s for net (RX, TX) and disk (Read, Write) might seems strange, but is still correct. It will simply show the value for the immediate last refresh on glances' side, regardless of the configured interval
(I also alphabetically sorted the allowed keys to ease finding existing values)
=> Enhancement: Add configurable refresh interval and points for glances service

src/widgets/kubernetes/component.jsx
=> Fix: show mem / cpu stats for k8s partial health status

docs/widgets/index.md
`widgets.yml` should be `widgets.yaml` now in the document.
=> Documentation: fix typo in widgets file name

src/widgets/changedetectionio/component.jsx
I would consider this non-breaking, and non-contentious, but I am open to other critiques/options
I think this makes the widget match the functionality of changedetection and what is shown on the changedetection site a bit better...
Prior to this change, the widget could display a count of diffs detected that did not match "new unseen" diffs so when you navigated to the changedetection site, they had already been seen and were not bolded. The state would not "reset" until the following check happened.
More background at https://github.com/dgtlmoon/changedetection.io/issues/1998
=> Change: changedetection.io widget count diff if not viewed

src/skeleton/widgets.yaml
The url in the skeleton is dead, i have change it to point at the new active url.
=> Changing widget doc url

docs/widgets/services/fritzbox.md, public/locales/de/common.json, public/locales/en/common.json, src/widgets/fritzbox/component.jsx, src/widgets/fritzbox/proxy.js
- only request the endpoints required by the field configuration
- note in the documentation on the use of http instead of https, as it is significantly faster (~1.2 seconds => ~90 milliseconds)
=> Enhancement: improve fritzbox proxy perfomance

docs/configs/settings.md, src/components/services/group.jsx, src/components/services/item.jsx, src/components/services/list.jsx, src/pages/index.jsx
Forces every service in a row to be the same vertical size without removing any content.
Before
After
Desktop tested on chromium & firefox
Mobile on iOS Safari
=> Feature: setting for equal height cards

src/widgets/healthchecks/component.jsx
If the `fields` key is defined for the `healthchecks` widget, no fields will show due to the field labels being translated manually on the `Block` component's `label` prop.
Before (fields not set in YAML):
Before (fields: ["status"] set in YAML):
After (fields: ["status"] set in YAML):
Closes # N/A
=> Fix: fields not working for healthchecks widget

docs/widgets/services/fritzbox.md
`upTime`  corrected to `uptime`
Closes #2456
=> Fix: Typo in fritzbox documentation 

package-lock.json, package.json, pnpm-lock.yaml, src/widgets/calendar/integrations/ical.jsx
This PR fixes issue where all recurring ical events aren't shown and multi-day events don't show instance for every day they're scheduled.
=> Fix: show recurring and multi-day events

docs/widgets/services/peanut.md, mkdocs.yml, public/locales/en/common.json, src/widgets/components.js, src/widgets/peanut/component.jsx, src/widgets/peanut/widget.js, src/widgets/widgets.js
Add support for https://github.com/Brandawg93/PeaNUT.
=> Feature: Add peaNUT Widget

src/widgets/fritzbox/proxy.js
Make the fritzbox proxy more robust, that missing or empty properties does not result in an error.
Closes #2461
=> Fix: fritzbox error when response contains empty values

docs/configs/services.md
This PR changes the destination of a link in the docs which refers to information and configuration for each of the supported integrations. The link should point to `/widgets/`, which contains this information, but currently points to `/configs/service-widgets/`, which does not.
- [n/a] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [n/a] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
=> Documentation: Fix link to widgets page in docs

src/widgets/calendar/component.jsx
Unclear if this changed or has always been an issue but since params gets serialized, Radarr seems happier with empty strings for these values
Closes #2469
=> Fix: calendar widget radarr integration API params invalid

package-lock.json, package.json, pnpm-lock.yaml
Update the `GameDig` dependency from `4.1.0` to `4.3.0`.
Checkout the changelog [here](https://github.com/gamedig/node-gamedig/blob/master/CHANGELOG.md), but shortly said, `4.2.0` introduced a lot of new supported games and `4.3.0` a single new game and 2 fixes, no code breaking changes.
=> chore: update gamedig dep to 4.3.0

src/widgets/changedetectionio/component.jsx
Followup to https://github.com/gethomepage/homepage/pull/2401
Context at https://github.com/gethomepage/homepage/pull/2401#issuecomment-1853092022
=> changedetection.io widget count diff not showing all valid diffs

src/widgets/fritzbox/component.jsx, src/widgets/fritzbox/proxy.js
- The uptime will be shown shown in days when it reaches 24 hours (mentioned by @FurkanVG [here](https://github.com/gethomepage/homepage/pull/2387#issuecomment-1850131870)) 
- Seconds will be hidden when days are shown to save space
- Days, hours & minutes will not be shown, if the uptime is not high enough
- Error messages are now returned correctly from the proxy, so that they will be displayed in the frontend
Seconds:
Minutes & Seconds:
Hours, Minutes & Seconds:
Days, Hours & Minutes:
=> Enhancement: fritzbox uptime display

docs/configs/kubernetes.md, src/utils/config/service-helpers.js
Add another annotation to kubernetes discovery to allow user to specify for which instance is this supposed to be present for. If no instance provided then it works for all instances preserving current behaviour.
Closes #2487
=> Enhancement: support `instanceName` filtering for kubernetes auto-discovery deployment

src/widgets/tdarr/component.jsx
Use viewable count if it exists, which removes file count of any disabled libraries etc
Only shows items which are viewable in the tables in the UI.
If new data not available then use previous data.
- [ x] Other (please explain)
Slight data change which fixes:
https://github.com/HaveAGitGat/Tdarr/issues/932
- [x ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
=> Use viewable count if it exists

package-lock.json, package.json, pnpm-lock.yaml
Some logos of companies in the `react-icons/si` (Simple Icons) package have been updated (e.g. Ubiquiti), so this change updates that external package to bring it more up to date :~)
=> Chore: bump react-icons to 4.12.0

src/widgets/openmediavault/proxy.js
=> Fix: pass user/pass as strings with OMV proxy

docs/widgets/services/healthchecks.md, public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/healthchecks/component.jsx, src/widgets/healthchecks/widget.js
I use Healthchecks in my homelab and manage multiple checks. While I am grateful for the initial development work outlined [here](https://github.com/gethomepage/homepage/pull/1023), I believe the initial approach could not have been the most effective. The reason being that having a widget for a single check often falls too short. I agree with the sentiments expressed in other [comments](https://github.com/gethomepage/homepage/pull/1023#issuecomment-1586332373) and the associated [feature request](https://github.com/gethomepage/homepage/discussions/2411). The widget would be vastly improved if it could display the total number of "ups" and "downs."
Other changes:
- I also got [confused](https://github.com/gethomepage/homepage/discussions/2566) about the terms "Online"/"Offline" that don't …
=> Enhancement: support multiple checks for healthchecks widget

docs/widgets/services/calendar.md, src/widgets/calendar/agenda.jsx, src/widgets/calendar/event.jsx, src/widgets/calendar/integrations/ical.jsx, src/widgets/calendar/monthly.jsx
New `timezone` option forces the events to use a specific timezone when provided calendar file is missing that information.
Closes #2575
=> Add option to specify a timezone for events

docs/widgets/services/customapi.md, next-i18next.config.js, public/locales/en/common.json, src/widgets/customapi/component.jsx
- _[FIX]_ Added a `locale` option to the `date` format of the CustomAPI widget
- _[FEATURE]_ Added a new `relativeDate` format to the CustomAPI widget
Closes #2612
**Note**  
When writing this PR, I initially did not see the requirement of having 5 up-votes for new features. As this PR contains both a bug fix and new feature and both changes are rather minimal, I still hope it will be accepted.
If you do not want to add the new feature because of said rule, let me know if I can still submit the locale option as a new PR _(and that will teach me to properly read guidelines before jumping in to code my requested features...)_.
=> CustomAPI changes: locale option for date & relativeDate format

docs/widgets/services/calendar.md, src/utils/config/service-helpers.js, src/widgets/calendar/agenda.jsx, src/widgets/calendar/component.jsx, src/widgets/calendar/event.jsx, src/widgets/calendar/integrations/ical.jsx, src/widgets/calendar/monthly.jsx
This PR addresses slower performance when using timezone in calendar: 
- doubles the performance when timezone is specified
- slower timezone performance should have no impact when timezone is not specified.
=> Fix: Calendar timezone performance improvements

docs/widgets/services/netdata.md, mkdocs.yml, public/locales/en/common.json, src/widgets/components.js, src/widgets/netdata/component.jsx, src/widgets/netdata/widget.js, src/widgets/widgets.js
This change introduces a (very simple) Netdata widget that pulls data from the locally exposed API. I used the Adguard Home widget as a base.
The user will be able to add the widget to the services.yaml file using the following configuration:
```yaml
widget:
type: Netdata
url: http://netdata.host.or.ip
```
Relates to https://github.com/gethomepage/homepage/discussions/1217
=> Feature: Netdata service widget

src/components/widgets/datetime/datetime.jsx
Howdy!
This small change should allow the date time to pop up on the initial page load and not after a one-second delay.
I'm just now getting into homepage in my homelab, and I am very interested in using and improving it any way I can.
=> Fix: remove date time load delay

docs/configs/bookmarks.md
Improve documentation, working examples for bookmarks.
I stumbled to get Homepage working because the example omitted the configuration filename and [YAML: start of document](https://yaml.org/spec/1.2.2/#22-structures).
=> Documentation: improve bookmarks documentation and working examples

docs/widgets/services/gatus.md, mkdocs.yml, public/locales/en/common.json, src/widgets/components.js, src/widgets/gatus/component.jsx, src/widgets/gatus/widget.js, src/widgets/widgets.js
This change adds support for a [Gatus](https://github.com/TwiN/gatus) widget for uptime tracking. I used the existing Uptime-Kuma widget as a basis.
The user will be able to add the widget to the services.yaml file using the following configuration:
```yaml
widget:
type: gatus
url: http://gatus.host.or.ip:port
```
Relates to #2341
=> Feature: Added gatus uptime widget

src/widgets/calendar/integrations/ical.jsx
Im not certain if the calendar in the linked issue is improperly implementing the calendar spec (I'd guess so) but in that case the uid is not stable between pulls of the calendar. See diffs from pulling the calendar even seconds apart:
- https://github.com/gethomepage/homepage/assets/4887959/337cc4ff-c647-40e0-8edc-441d92d11e1b
- https://github.com/gethomepage/homepage/assets/4887959/f4c5213c-9596-4bd4-ada0-98a8f28d8a5a
Apparently this is not so uncommon https://stackoverflow.com/questions/38193837/how-to-handle-a-uid-of-an-ics-calednar-that-will-change-every-time-i-access-it
Solution is to hash the start/end/title & a couple other things. I tested with a few calendars out there including recurrence but as we've seen, calendars are messy...
Closes #2753
=> Fix: iCal integration use event data hash instead of unstable uid

docs/widgets/services/hdhomerun.md, public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/hdhomerun/component.jsx, src/widgets/hdhomerun/widget.js
- maintain the previous behavior if no new configuration is done
- define additional available fields and present the data in order configured
- global: "tunerCount"
- per-tuner: "channelNumber", "channelNetwork", "signalStrength", "signalQuality", "symbolQuality", "networkRate", "clientIP"
- add handling for refreshInterval
- update docs
An example of two instances of the widget with the fields configured to be `fields: [ "channels", "hd", "tunerCount" ]` and `fields: [ "clientIP", "channelNumber", "channelNetwork", "signalQuality" ]` respectively:
Closes #772
=> Enhancement: extend hdhomerun widget

docs/widgets/services/openwrt.md, public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/components.js, src/widgets/openwrt/component.jsx, src/widgets/openwrt/methods/interface.jsx, src/widgets/openwrt/methods/system.jsx, src/widgets/openwrt/proxy.js, src/widgets/openwrt/widget.js, src/widgets/widgets.js
Adds a widget for OpenWRT integration
Allows for either system info or information on a particular interface (i.e eth0 for WAN) by adding that interface name as `interfaceName` in services.yaml
Closes #1509
Adds a new widget for OpenWRT
=> Feature: OpenWRT service widget

docs/widgets/services/kavita.md
The Kavita widget requires that a Kavita user must at least have the roles of **Admin** and **Login**, otherwise a call to the API server stats endpoint fails and the widget returns **NaN** in both fields.
This minor documentation change hightlights the requirement for the **Admin** role.
Tested on:
- Homepage v0.8.7 (latest)
- Kavita v0.7.13.0 (latest)
Closes #2797
=> Fix: role requirement in Kavita documentation

src/pages/index.jsx, src/utils/proxy/cached-fetch.js
=> Fix quick launch not opening with accented characters, decoding of characters in suggestions

src/widgets/immich/component.jsx
Make use of formatting tools to format the totals for Users, Images and Videos that Immich provide.
From
to
=> Fix: Add formatting to Immich totals

docs/widgets/services/pialert.md
Unlike other widgets, PiAlert has one line for "learn more about ..." and another line for "widget for ...", where the first PiAlert is pointed to the abandoned repo. The second line is the actual repo for the widget.
Instead of putting the abandoned repo after learn more about like other widgets, the actual actively devleoped one is used, also a note of the original repo that has been abandoned was added.
=> Documentation: fix abandoned PiAlert repo

src/components/services/item.jsx
=> Fix: Increase icon z-index 

docs/configs/settings.md, src/components/bookmarks/group.jsx, src/components/services/group.jsx, src/pages/index.jsx
This PR adds the possibility to let layout groups be initially collapsed.
This can be configured in the layout group as follows:
```yaml
layout:
Section A:
initiallyCollapsed: true
```
It defaults to false.
Closes #1636
=> Enhancement: initially collapsed option for layout groups

src/components/quicklaunch.jsx, src/components/widgets/search/search.jsx
This PR fixes two bugs with the search suggestion.
- The search box opened the search URL when loosing focus.
- The suggestion API kept getting called without the search changing.
Closes #2866
=> Fix: search opens when losing focus, prevent unnecessary search API calls

src/widgets/healthchecks/component.jsx
A recent [change](https://github.com/gethomepage/homepage/pull/2580) to Healthchecks widget added an `hasUuid` check to allow for multiple functionalities. Due to a quirky behavior of the `Container` and `Block` components, the block components must be directly nested underneath the `Container` component in order for the optional `fields` prop to be respected. 
This change fixes the conditional in the component while maintaining the current functionality.
Closes # N/A
=> Fix: Incorrect Container/Block structure in Healthchecks widget

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
It's pretty annoying to have to install the pre-commit package every time the devcontainer is rebuilt.
Therefore, this PR adds the installation of the pre-commit package to the Dockerfile.
Furthermore, this PR adds the prettier VS Code extiontion to the devcontainer.  
Closes # N/A
=> Chore: add pre-commit and prettier to devcontainer

src/widgets/calendar/integrations/ical.jsx
This PR fixes a issue of iCal integration.
For the one-day event with Google Calendar, the `dtend` would not defined.  So the error appeared.
This PR fixes about it: when `dtend` is not defined, set it as same as `dtstart`.
And also, if `dtend` and `dtstart` are the same, set duration to `1`;
Closes #2882
=> Fix: iCal integration fails with all-day events

docs/widgets/services/customapi.md, src/utils/proxy/handlers/generic.js
Add new optional `requestBody` option to `customapi` widget. This will allow accessing endpoints that might require filtering via request body instead of query params.
This new option will support objects or strings to allow for clean ways to write JSON request bodies or the ability to pass a raw body for non JSON formats.
Here is the services configuration I used:
```yaml
- Custom API:
- POST No Body:
widget:
type: customapi
url: https://api.mockfly.dev/mocks/febdbed3-d77d-4665-b94f-d12ffb0813a9/test
method: POST
headers:
Content-Type: application/json
Accept: application/json
mappings:
- field: msg
label: Message
format: text
- POST Object Body:
widget:
type: customapi
url: https://api.mockfly.dev/mocks/febdbed3-d77d-4665-b94f-d12ffb0813a9/test
method: POST
headers:
Content-Type: …
```
=> Add requestBody as option for customapi widget

docs/widgets/services/moonraker.md, src/widgets/moonraker/widget.js
Changed the genericProxyHandler to use the credentialedProxyHandler for moonraker instances that uses authorization by API keys.
With the genericProxyHandler you get a 401 unauthorized error on those instances.
=> Enhancement: allow api auth with moonraker service

docs/widgets/services/planit.md, mkdocs.yml, public/locales/en/common.json, public/locales/it/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/plantit/component.jsx, src/widgets/plantit/widget.js, src/widgets/widgets.js
Implements https://github.com/gethomepage/homepage/discussions/2723
Copy of https://github.com/gethomepage/homepage/pull/2890 (up-votes required number is now reached)
Example of usage:
```
- Plant-it:
href: http://localhost:8085/
description: 🪴 Self-hosted, open source gardening companion app
widget:
type: plantit
url: http://localhost:8085
key: 7QiFTqEdRguDhPNXxr83F8Obl6HpDTUTNg+7SUJdxn+s34kXfxhxHBTEA96w5NgnfS60so3XY/10YKrRXA6vow==
```
=> Add Plant-it widget

.github/dependabot.yml
Allow dependabot to update python packages
=> Chore: add pip to dependabot

docs/widgets/info/glances.md, docs/widgets/info/resources.md, docs/widgets/services/glances.md, src/components/widgets/glances/glances.jsx, src/components/widgets/resources/disk.jsx, src/components/widgets/resources/resources.jsx, src/utils/config/service-helpers.js, src/widgets/glances/metrics/fs.jsx
Resources / glances info / glances service widgets all behave the same, default to bytes, can be set to 'bbytes'
Supersedes #2964
=> Enhancement: support different bytes multipliers for disk space for resources / glances and metrics widgets

docs/widgets/services/stash.md, mkdocs.yml, public/locales/en/common.json, src/widgets/components.js, src/widgets/stash/component.jsx, src/widgets/stash/widget.js, src/widgets/widgets.js
Adds a new widget for the [Stash](https://github.com/stashapp/stash) app with a number of fields matching their in-built stats page as suggested in the original widget request #2238. Though I understand if this is rejected or needs to be adjusted due to it being an adult/18+ oriented app.
Closes #2238
=> Feature: add stash widget (#2238)

docs/widgets/services/homeassistant.md
Changes link in `docs/widgets/services/homeassistant.md` to correct format. Previous format was `(description)[link]` which is incorrect.
=> Documentation: Fix link formatting in Home Assistant service widget document

src/components/services/status.jsx
This resolves the styling / inconsistency issues regarding docker status labels.
Closes #3027
In addition to the color issues stated in #3072, I've found some other inconsistencies regarding what statuses got translated or not and what would be set as the `statusTitle`. Those have also been touched in this PR. (Makes it easier to apply custom CSS Styling e.g. specifically for containers that have `exited` without touching containers of status `unknown`.
With styling fixed:
=> Fix: docker status labels colors

src/components/widgets/widget/container.jsx, src/pages/index.jsx
=> Fix: info widget gaps

src/widgets/omada/component.jsx
=> Fix: omada widget missing switches field, enforce default and max fields

docs/widgets/services/pihole.md, src/widgets/pihole/component.jsx
Shoulda thought of this before. If user specifies `blocked_percent` still show it, otherwise just merge it.
Default:
with `blocked_percent` field specified:
Closes #3064
Closes #2473
Closes #2426
=> Change: default merge pihole blocked fields

docs/configs/settings.md, src/utils/logger.js
Homepage logs to both stdout and a logs directory by default. While the log file path [can be customised](https://gethomepage.dev/latest/configs/settings/#log-path), it’s not currently possible to disable the file logging completely.
In some situations, such as on Kubernetes or where Homepage is running under a service manager like systemd, it may be preferable to only output to stdout, as log aggregation/collection is handled more centrally.
This patch introduces support for the `LOG_TARGETS` environment variable, which has possible values of `both` (default), `stdout`, or `file`. If left unset, the default value of `both` behaves the same as the previous default - so this change should be backward compatible.
Closes #3067
=> Enhancement: support `LOG_TARGETS` environment variable

src/widgets/glances/metrics/process.jsx
Currently when using the Glances process widget, the process name could overflow given the text is too long, especially on smaller laptops. The screenshot was taken on a 13-inch MacBook in the fullscreen with a reasonable layout standard.
By adding `truncate` to CSS, it prevents overflow with the maximum information provided. Although there is still a misalignment issue, it is caused by `grow` and can not be fixed with CSS only.
=> Fix: truncate long process names in Glances widget

docs/widgets/info/openmeteo.md, docs/widgets/info/openweathermap.md, docs/widgets/info/weather.md, src/components/widgets/openmeteo/openmeteo.jsx, src/components/widgets/openweathermap/weather.jsx, src/components/widgets/weather/weather.jsx
Adds formatting options to the weather widgets.
Closes #2827
=> Enhancement: Add formatting options to weather widgets

src/utils/config/service-helpers.js
```yaml
- homepage.widget.type=gamedig
- homepage.widget.url=udp://135.148.151.222:16261
- homepage.widget.serverType=csgo
- homepage.widget.fields=["status", "maxPlayers"]
```
Closes #3100
=> Fix: field parsing can fail with docker labels

docs/widgets/services/esphome.md, public/locales/en/common.json, src/widgets/esphome/component.jsx
After deploying changes of #2986 in different use-cases it became clear that internal handling of EspHome device states can be somewhat inconsistent w.r.t. the offline devices. Some users may want any device that is _not online_ to be shown as offline, but others may need the distinction of when a device is proven to be offline (cannot be reached).
This PR adds an alternative `offline` state that essentially groups both marked offline and unknown together.
In the following example I have one device whose address can be resolved, but cannot be pinged and 2 devices that are not even resolved;
Configuration used in this example:
```yaml
- ESPHome:
icon: esphome.png
widget:
type: esphome
url: http://localhost:6052
fields:
- online
- offline
- offline_alt
- unknown
```
=> Fix: Add alternative 'offline' status to EspHome widget

docs/installation/k8s.md
I recently encountered an issue in k8s that caused homepage to reload 3-5 times each time the window or tab was blurred then re-focused. The issue wound up going away when I reduced my homepage replica count to 1. I was able to resolve the issue, while still keeping my replica count at 2, by enabling sticky sessions for the homepage route. This PR aims to document this finding for anyone else that might be experiencing the same issue.
Related thread: https://github.com/gethomepage/homepage/discussions/2305#discussioncomment-8781811
=> Documentation: Adds sticky cookie note for k8s multiple replica setups

src/utils/config/service-helpers.js
This PR addresses an issue where a server fails to retrieve services from Docker without raising an error, potentially causing confusion regarding server functionality. The fix adds an error log to provide clarity in such scenarios.
=> fix(logging): add error log when getting services from Docker server

docs/widgets/services/jackett.md, src/utils/proxy/http.js, src/widgets/jackett/proxy.js, src/widgets/jackett/widget.js
Opening again because #3115 has 10 upvotes.
See #3125 for original PR
Fixes the error that occurs as seen in (#437, #1799 and #2794) which occurs due to the way password authentication works in Jackett. We now make a login request to Jackett to get the cookie and then use that cookie to make the actual request to the Jackett API.
Closes #3115 
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] If applicable, I have added corresponding documentation changes.
- [ x ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [ x ] I have …
=> Enhancement: support Jackett widget with admin password (#3097)

docs/widgets/services/glances.md, src/utils/config/service-helpers.js, src/widgets/glances/metrics/cpu.jsx, src/widgets/glances/metrics/info.jsx
This fix is for Glances Widget Service where the `info` metric without chart would only display the CPU instead of the OS, but most importantly fix the `cpu` metric to show the CPU brand / model as well as the temperature, instead of the OS as before.
The `cpu` metric now shows the temperatures as well, current and warn, just like the informational widget, and you can change the units to fahrenheit with `tempUnits: imperial`
Also updated the documentation to reflect `refreshInterval` and `pointsLimit` introduced in #2363 
Closes #3160
=> Fix: Glances cpu & info widgets information

src/widgets/glances/metrics/info.jsx
There is an issue with the spacing for the glances service cpu chartless widget, previously addressed by adding a margin right to ensure the label never touches the value [here](https://github.com/gethomepage/homepage/pull/3164/commits/459bc293c0c52c12b7852dcd094b59d4cc68e57f#diff-eac3c6efb61eb5fc47ec41f9997cc48e32ace2f8ae60d3193d3d6d9b961d2b62), now fixed by simply increasing the width of the flex container, matching the one from memory and swap.
=> Fix: Glances cpu chartless whitespace issue

docs/widgets/services/authentik.md
Add more information about what permissions are needed for the widget to retreive the fields it is intended to retrieve from Authentik.
Background for this is i wasted quite a bit of time figuring this out, and don't want a service account that retrieves statistics having more permissions than necessary.
=> Documentation: Update authentik api key info

docs/widgets/info/glances.md, docs/widgets/services/glances.md, src/pages/api/widgets/glances.js, src/utils/config/service-helpers.js, src/widgets/glances/metrics/cpu.jsx, src/widgets/glances/metrics/disk.jsx, src/widgets/glances/metrics/fs.jsx, src/widgets/glances/metrics/gpu.jsx, src/widgets/glances/metrics/info.jsx, src/widgets/glances/metrics/memory.jsx, src/widgets/glances/metrics/net.jsx, src/widgets/glances/metrics/process.jsx, src/widgets/glances/metrics/sensor.jsx, src/widgets/glances/widget.js
This will require folks to add `version: 4` to their config, but seemed the most straightforward way to handle this. Will likely have to do something similar for https://github.com/gethomepage/homepage/discussions/3168
Closes #3187
=> Feature: support for glances v4

src/widgets/homebridge/proxy.js
This fix is for Homebridge Widget Service where the login to the Homebridge API could not be performed, when the username or password ist numeric.
Before:
After:
=> Fix: Homebridge widget login

docs/widgets/services/emby.md, docs/widgets/services/plex-tautulli.md, src/utils/config/service-helpers.js, src/widgets/emby/component.jsx, src/widgets/tautulli/component.jsx
Added a new optional flag that can be added to the widget enableUser. If true the username will be added in parenthesis behind the title. Updated the documentation stating that this is an optional field and defaults to false.
Closes #1233  #151
=> Enhancement: option to show user for Tautulli and Emby/Jellyfin widgets

docs/overrides/main.html, docs/stylesheets/extra.css, mkdocs.yml
Move carbon ad placement to the side navigation
=> Carbon move

src/widgets/pihole/component.jsx
=> Fix: pihole `ads_percentage_today` sometimes returned as string

docs/widgets/services/medusa.md
Fix repo link for Medusa, using the wrong Medusa Project
Fixes Wrong Link in Documentation
- [ x] Documentation only
- [x ] If applicable, I have added corresponding documentation changes.
=> Documentation: correct Medusa link

docs/widgets/info/resources.md, src/components/widgets/resources/cputemp.jsx, src/components/widgets/resources/resources.jsx
Introduces `tempmin` and `tempmax` in **resources/cputemp.jsx** as optional parameters to configure the CPU temperature scale. By default, if no values are provided, the existing heuristic is used (scale from 0 to highest core temp). If `tempmin` and/or `tempmax` are set, the scale will be adjusted accordingly. This allows for a more meaningful scale, that isn't always at 99% for most use cases.
Closes #2478
=> Enhancement: configurable CPU temp scale

docs/widgets/services/authentik.md
Edits the documentation around Authentik to use fine-grained permissions since the widget only needs read access to Users and Events. The current documentation around these permissions are vague and could lead to people giving the widget unnecessary access.
=> Documentation: authentik fine-grained permissions

docs/widgets/services/emby.md, docs/widgets/services/jellyfin.md, docs/widgets/services/plex-tautulli.md, src/utils/config/service-helpers.js, src/widgets/emby/component.jsx, src/widgets/tautulli/component.jsx
Adds the following service widget options to Tautulli and Emby (includes Jellyfin)
- `expandOneStreamToTwoRows` 
- *optional* default to true
- functionality: currently expands one stream to two rows (top row is media details and bottom is media progress bar). This includes making 2 rows when there are 0 streams. When set to false, it will at most show 1 row saying, "No Active Streams". 
- `showEpisodeNumber`
- *optional* default to false
- functionality: would check the media type and if it is an episode type, would grab the episode number and display it right before the episode title and right after the show title
- e.g. `show_title`: `episode_number` - `episode_title`
Also changes username to friendly_name. Noticed that @brikim wanted to make that change on the last PR so thought it …
=> Enhancement: additional tautulli jellyfin emby configuration options

docs/widgets/services/speedtest-tracker.md, src/utils/config/service-helpers.js, src/widgets/speedtest/component.jsx
Add new widget configuration option for speedtest-tracker widget to configure the number of decimal places it will print the bitrate at. (`bitrateNumOfDecimalPlaces`)
It will now default to 2 decimal places but can be configured for any non-negative integer. If an invalid value is passed in, it will fallback to the default value.
with `bitrateNumOfDecimalPlaces: 3`:
with `bitrateNumOfDecimalPlaces: 0`:
with `bitrateNumOfDecimalPlaces: -3` (falls back to default):
Closes #1308 (issue)
=> Enhancement: add bitrate precision config option for speedtest-tracker 

src/widgets/romm/component.jsx
Use the `"common.number"` translation for displaying statistics for the Romm widget.
=> Fix: format Romm statistics

docs/configs/settings.md
Added "api" so that weather is working if a user copy&paste the entry from the documentation. See also #338
=> Documentation: correct weatherapi example

src/pages/index.jsx
Quicklaunch wouldn't start with characters that require modifier keys to be typed (i.e. !,@,#,$), making it annoying to use quicklaunch alongside duckduckgo bangs
=> Fix: allow exclamation to open quicklaunch

docs/widgets/services/wgeasy.md, public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/components.js, src/widgets/wgeasy/component.jsx, src/widgets/wgeasy/proxy.js, src/widgets/wgeasy/widget.js, src/widgets/widgets.js
This adds a widget for Wg-Easy. The widget can display how many Wireguard connections are enabled as well as how many are connected, it also shows total as well and has the option to show disabled. To check for connections the time since the last handshake is checked. It allows for a threshold value in the widget allowing you to adjust how long to wait since the last handshake  in minutes to consider the device connected. It defaults to `["connected", "enabled", "total"]`
Addresses #1580 though I saw this discussion post development.
=> Feature: Wg-Easy Widget

src/components/widgets/longhorn/node.jsx
This change corrects what looks like an incorrect icon copy/paste from another widget within the longhorn widget. Now longhorn displays a disk icon rather than a temperature icon
Before: 
https://imgur.com/2QWQY8m
After: 
https://imgur.com/VkOrMFz
Closes # N/A
=> Change icon in the longhorn widget to use the same as resources

src/widgets/caddy/component.jsx, src/widgets/evcc/component.jsx
Commit 19c25713c42c25795e117d2f75d92f69c4211f38 introduced a very minor layout bug to my Caddy and the EVCC widget (a comma character in the layout block of the widget).
It just shows up when the API call for the widget is still loading so it's very hard to notice, but once you do notice it the first time, you will notice it every time 😉 
I did not create a bug report since the issue is very minor. If necessary I can create one however.
=> Fix: remove comma in Caddy and EVCC widgets

src/pages/api/services/proxy.js
=> Fix: calendar integration broken in v0.9.0

src/widgets/wgeasy/component.jsx, src/widgets/wgeasy/proxy.js
Closes #3568
- Changes the threshold calculation accounting for a custom threshold.
- Prints out the actual error when login fails
- Adds a check for the cached sid within login
=> Fix: wg-easy threshold not properly computed

src/widgets/caddy/component.jsx, src/widgets/caddy/widget.js
=> Fix: caddy widget broken in v0.9.1

docs/configs/kubernetes.md, src/utils/config/service-helpers.js
This is an added feature to allow Kubernetes Ingresses to have multiple instance annotations, so this make it possible to show a single Ingress to a selected Homepage instances. The code change is very minimal and does not introduce breaking changes, and I already update the Kubernetes configuration documentation on how to use this feature.
This is very similar to issue #2340 which solved this problem for Docker, while this PR is for Kubernetes.
=> Enhancement: support multiple instance annotation for Kubernetes Automatic Service Discovery

src/widgets/glances/components/container.jsx, src/widgets/glances/components/error.jsx, src/widgets/glances/metrics/cpu.jsx, src/widgets/glances/metrics/disk.jsx, src/widgets/glances/metrics/fs.jsx, src/widgets/glances/metrics/gpu.jsx, src/widgets/glances/metrics/info.jsx, src/widgets/glances/metrics/memory.jsx, src/widgets/glances/metrics/net.jsx, src/widgets/glances/metrics/process.jsx, src/widgets/glances/metrics/sensor.jsx
I have the Glances widgets deployed in my Homepage instance and noticed that when a host is unreachable the widgets do not handle the errors as the other widgets do. It results in an ugly error message which doesn't respect either the global or service-level `hideErrors`. Here is an example from my deployment:
I have rewritten parts of the components such that the `Error` component is no longer needed, as it is now implemented within the `Container` component. The service and error attributes are now passed into the `Container` component, such that the service-level `hideErrors` flag can be checked. Additionally, the global settings are now imported into the `Container` component so the global `hideErrors` flag can be checked. Within each component, if the service data containers an …
=> Fix: Improve error handling for Glances widgets

src/pages/index.jsx
=> Fix: search dropdown overlay with boxedheaders option

src/widgets/calendar/event.jsx
=> Fix: increase width allowance for dates in ical agenda widget

docs/configs/kubernetes.md
The ingress annotation will still use pod-selector as the code paths were altered to expect that name. The documentation for the explicit service configuration is reverted to match the code path.
This fixes incorrect documentation change in #2187 where only the service discovery code path changed the expected configuration to `pod-selector`.
=> Fix mistaken documentation on field podSelector for services

src/pages/api/kubernetes/status/[...service].js
i'm using a kubernetes service that includes a web UI and cronjobs. because the job finish and go to status `Completed`, the homepage link to the web UI shows `partial` instead of `running`
this patch updates the `someReady` & `allReady` pod filter to include pods that are both `Running` and `Completed`
=> Fix: don't show "partial" for k8s status if there are completed job pods

src/widgets/wgeasy/component.jsx
=> Fix: wg-easy widget show o.filter is not a function when wg-easy api return error

docs/widgets/services/pfsense.md
Fixing pfSense widget documentation for usage with an API key. Current documentation has incorrect header of `Authorization` and a value of `client_id client_token`. The correct header name is `X-API-Key` and the value is the API `key` produced by the pfSense v2 API package. I have tested this format and it works as expected. 
Example working config for reference:
```
- pfSense:
icon: pfsense.png
href: https://pfsense.example.com
description: router
widget:
type: pfsense
url: https://pfsense.example.com
headers:
X-API-Key: 12345678
wan: ix0
version: 2
fields: ["load", "memory", "wanStatus", "wanIP"]
```
pfSense API authorization documentation is here: https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/
Closes [Discussion #3716](https://github.com/gethomepage/homepage/discussions/3757)
=> Documentation: clarify api key usage for pfsense v1 vs v2

src/components/tab.jsx
=> Fix: correctly decode tab names with special chars

docs/widgets/services/tubearchivist.md, src/widgets/tubearchivist/component.jsx, src/widgets/tubearchivist/widget.js
Seems like this was introduced a year or so ago, https://github.com/tubearchivist/tubearchivist/releases/tag/v0.4.4 so essentially will be required to use the widget now.
=> Enhancement: use tubearchivist stats endpoints

package-lock.json, package.json, pnpm-lock.yaml, src/widgets/gamedig/proxy.js
I upgraded the gamedig library to version 5.1.1 and enabled the checkOldIDs option to ensure that requests using old game IDs are still processed correctly. I verified that it functions correctly with both old and new IDs.
=> Chore: update Gamedig

README.md
Removed version: 3.3 line from docker compose yaml. Specifying version is obsolete and will throw a warning message in Docker.
=> Documentation: remove version line from readme docker compose yaml

docs/widgets/services/romm.md, public/locales/en/common.json, src/widgets/romm/component.jsx, src/widgets/romm/widget.js
An update to the currently existing RomM widget. This update changes the endpoint from the currently set 'platforms' endpoint to the more concise and cleaner 'stats' endpoint. The stats endpoint gives three additional fields of information that the existing two give, also without needing the calculations of the existing endpoint. Documentation has been updated to reflect the changes as well.
=> Refactor: change RomM API endpoint

docs/widgets/services/proxmox.md
I added one space for the indentation of the proxmox.md. It's how it's supposed to be but since they only have three spaces they aren't indented properly.
The screenshot shows that the first two things would look like the third set of things.
=> Documentation: fix indentation for proxmox docs.

docs/widgets/services/mealie.md, src/utils/config/service-helpers.js, src/widgets/mealie/component.jsx, src/widgets/mealie/widget.js
Mealie is introducing breaking API changes that are already merged in the "nightly" builds. See https://github.com/mealie-recipes/mealie/pull/3970. The `groups/statistics` endpoint is being deprecated and replaced with a `households/statistics` API.
I modelled the API handling on the Immich implementation https://github.com/gethomepage/homepage/pull/2284. If the version starts with "v2", or equals "nightly" it will use the new endpoint. Otherwise, it will keep using the existing endpoint to ensure this is non-breaking for people who pin to a v1 build.
Closes #
=> Chore: handle mealie API change

docs/widgets/services/index.md, docs/widgets/services/technitium.md, mkdocs.yml, public/locales/en/common.json, src/utils/config/service-helpers.js, src/widgets/components.js, src/widgets/technitium/component.jsx, src/widgets/technitium/widget.js, src/widgets/widgets.js
Adds a new service widget for Technitium DNS Server, based on their [Dashboard API](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md#dashboard-api-calls)
The above API call takes the format of: `<server ip / domain>/api/dashboard/stats/get?token=<api-token>&type=<time_range>&utc=true`
The following query string parameters are used
- `token`: Is the api token that can be created on the Technitium DNS dashboard, this is a permanant token that wont expire, that is specifically used to API calls.
- `type`: Is really a date range, and can be one of: `[LastHour, LastDay, LastWeek, LastMonth, LastYear]`
The response of this API call returns a lot of information, but the one this widget cares about, is the `response.stats` property that has the following data:
```json
{ …
```
=> Feature: Technitium DNS Widget

docs/widgets/authoring/proxies.md, docs/widgets/services/index.md, docs/widgets/services/zabbix.md, mkdocs.yml, public/locales/en/common.json, src/utils/proxy/handlers/jsonrpc.js, src/widgets/components.js, src/widgets/widgets.js, src/widgets/zabbix/component.jsx, src/widgets/zabbix/widget.js
The user will be able to add the widget to the `services.yaml` file using the following configuration:
```yaml
widget:
type: zabbix
url: http://zabbix.host.or.ip/zabbix
key: your-api-key
```
Relevant feature request: https://github.com/gethomepage/homepage/discussions/1953
I did somewhat break the Service Widget Guidelines.
- Zabbix exposes 6 alert fields by default, but I can cut it down to just 4.
- Zabbix requires an `auth`-field in the JSON RPC call for API tokens, which I could not figure out how to do with the generic jsonrpc proxy.
Let me know what I should change to have a valid pull request.
=> Feature: Zabbix service widget

docs/widgets/services/zabbix.md, public/locales/en/common.json, src/widgets/zabbix/component.jsx
Adds the missing severity for Zabbix, but ensures that no more than 4 fields are shown at any time (using the same logic as in https://github.com/gethomepage/homepage/pull/3047). Hopefully this is okay.
=> Enhancement: support more fields for zabbix widget

docs/widgets/services/tdarr.md, src/widgets/tdarr/proxy.js
Add Tdarr widget optional auth
Addresses already closed issue #2704, relevant to discussion #2705.
I realize the discussion does not have 10 upvotes as required, but I think this is a simple enough addition🙂
Also was unsure which branch to merge to so I hope main is alright 🤞
=> Enhancement: support Tdarr widget auth

src/utils/proxy/handlers/jsonrpc.js
Was also broken by #3905
Closes #3975
=> Fix: other jsonrpc widgets broken in 0.9.8

docs/installation/unraid.md
There were extra tabs before a MkDocs admonition declaration preventing the admonitions from rendering properly.
=> Documentation: fix mkdocs admonition in unraid.md

src/widgets/technitium/component.jsx, src/widgets/technitium/widget.js
During the cleanup commit from the original PR, the multiply by 100 while calculating the percentage number was accidently removed. Original code: https://github.com/gethomepage/homepage/pull/3904/commits/d8e45a2fbcc9ae1474a5d826cd5133edcd43154c#diff-bd42a75b6a61d8468c8570e33b7f13dfffcf6d6dca4997677b4d303ef56daab6R55
On my v9.8 dashboard, you can see the problem: 
And on the test bed you can see the fix:
=> Fix: Technitium widget percentage display

docs/widgets/services/changedetectionio.md
Just added additional documentation for the ChangeDetecion.io widget.
These fields are usable but wasn't listed previously in the documation. ["diffsDetected", "totalObserved"].
=> Documentation: add changedetection.io fields

docs/widgets/services/gluetun.md, src/widgets/gluetun/widget.js
As of release v3.41.0, all Gluetun control server routes will be private by default as described [here](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md#authentication). The existing Gluetun widget implementation does not support authentication. This PR adds support for apikey auth for the widget and is related to https://github.com/gethomepage/homepage/discussions/4026
=> Fix: Support Gluetun widget auth

docs/installation/index.md, src/widgets/mailcow/component.jsx
Closes #4052 
```json
[
{
"active": "1",
"aliases_in_domain": 0,
"aliases_left": 400,
"backupmx": "0",
"bytes_total": "5076666944",
"def_new_mailbox_quota": 3221225472,
"def_quota_for_mbox": 3221225472,
"description": "Some description",
"domain_name": "domain.tld",
"gal": "0",
"max_new_mailbox_quota": 10737418240,
"max_num_aliases_for_domain": 400,
"max_num_mboxes_for_domain": 10,
"max_quota_for_domain": 10737418240,
"max_quota_for_mbox": 10737418240,
"mboxes_in_domain": 0,
"mboxes_left": 10,
"msgs_total": "172440",
"quota_used_in_domain": "0",
"relay_all_recipients": "0",
"relayhost": "0",
"rl": false,
"tags": [
"tag1",
"tag2"
]
},
{
"active": "1",
"aliases_in_domain": 0,
"aliases_left": 400,
"backupmx": "1",
"bytes_total": "5076666944",
"def_new_mailbox_quota": 3221225472, …
```
=> Fix: correct caculations for mailcow widget

docs/widgets/services/unifi-controller.md
Added clearer instructions for the Unifi Controller widget when using Ubiquiti hardware.
=> Documentation: clarify account type for Unifi Controller widget

src/widgets/wgeasy/component.jsx
=> Fix: wg-easy disabled field not visible

docs/widgets/services/immich.md, src/utils/config/service-helpers.js, src/widgets/immich/component.jsx, src/widgets/immich/widget.js
=> Enhancement: handle immich v1.118 breaking API change

docs/widgets/services/netalertx.md, src/utils/proxy/handlers/credentialed.js, src/widgets/netalertx/widget.js
Closes https://github.com/jokob-sk/NetAlertX/issues/838
=> Enhancement: support netalertX token for password-protected instances

src/widgets/radarr/widget.js
The current usage of `/api/v3/movie`'s `all` mapping is only for mapping queue IDs to movie titles. Originally I planned to move to using the queue details title, but that is the full download title and not strictly just the movie title. To not change the UI, we can at least remove unnecessary attributes from the response which is currently very bloated. If it's fine to change from movie title to download title, then `all` can be removed completely.
A user reported for a library of ~10k movies the response was >4MB:
```
[2024-10-26T07:29:29.928Z] warn: API response for /api/services/proxy?group=Movies+and+Series+Management&service=Radarr&endpoint=movie exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
```
This change …
=> Chore: filter Radarr movie response

src/components/bookmarks/group.jsx, src/components/bookmarks/item.jsx
- Fixed the text-overflow in bookmarks (see screenshots)
=> Fix: text overflowing in bookmarks

src/pages/api/widgets/openmeteo.js
=> Fix: use same unit default for openmeteo widget and api

docs/widgets/services/headscale.md, docs/widgets/services/index.md, mkdocs.yml, public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/headscale/component.jsx, src/widgets/headscale/widget.js, src/widgets/widgets.js
Added service widget for [headscale](https://headscale.net/), as requested by [this discussion](https://github.com/gethomepage/homepage/discussions/1622).
=> Feature: Headscale Service Widget

docs/widgets/services/authentik.md
There is no default port 22070 for the configuration of this widget. You can either use the Port specified while installing Authentik or use the domain when using a reverse proxy. See: https://docs.goauthentik.io/docs/developer-docs/api/
=> Documentation: change authentik port to generic placeholder

docs/widgets/services/index.md, docs/widgets/services/prometheusmetric.md, mkdocs.yml, src/utils/config/service-helpers.js, src/widgets/components.js, src/widgets/prometheusmetric/component.jsx, src/widgets/prometheusmetric/widget.js, src/widgets/widgets.js
Adds a service widget to query prometheus metrics with PromQL queries and formats the results in a very similar way to how `customapi` does. I tried to combine this with the existing prometheus service widget but since the configuration for this one is quite fundamentally different I thought it makes more sense to have it in a separate widget. Let me know what you think.
Closes #779, #2969, #4267
=> Feature: Prometheus Metric service widget

src/widgets/tautulli/component.jsx
The tautulli widget is using session.Id as the unique key, but for whatever reason the tautulli api gives a blank id for each session as shown in the snippet below:
```
session_key: "5"
id: ""
session_id: "x24yt3vaw2r4tququrjg"
container: "mkv"
bitrate: "957"
```
This caused a react warning: ```Warning: Each child in a list should have a unique "key" prop.``` Note that this warning only shows up if sessions are present.
Using session_key fixes this since each session gets a unique key. Session_id (not session.id) could also be used if preferred.
=> Fix: use session_key instead of Id in tautulli component to resolve unique key warning

docs/widgets/services/suwayomi.md, public/locales/en/common.json, src/widgets/components.js, src/widgets/suwayomi/component.jsx, src/widgets/suwayomi/proxy.js, src/widgets/suwayomi/widget.js, src/widgets/widgets.js
add a [Suwayomi](https://github.com/Suwayomi/Suwayomi-Server) Service widget
Closes #2972
I had to use a custom proxy because i needed GraphQL variables for variable category selection.
in the case of `category: all` the response from Suwayomi would look like.
```json
{
"data": {
"downloadCount": {
"totalCount": 46428
},
"nonDownloadCount": {
"totalCount": 46428
},
"readCount": {
"totalCount": 31345
},
"UnreadCount": {
"totalCount": 33770
}
}
}
```
~200B
in the case of `category: {number}`
```json
{
"data": {
"category": {
"mangas": {
"nodes": [
{
"chapters": {
"nodes": [
{
"isRead": false,
"isDownloaded": true
},
{
"isRead": true,
"isDownloaded": true
},
...
]
}
},
...
]
}
}
}
}
```
~6Kib (for a massive library)
you can't filter chapters by what category they are in or filter chapters …
=> Feature: suwayomi Service Widget

docs/widgets/services/beszel.md
Improved Beszel widget documentation. Specifically:
- Fixed Beszel repository link
- Added information about where to find `systemId`
- Added information about how to set up custom fields
Closes #4281
=> Documentation: corrections Beszel widget docs

docs/widgets/services/argocd.md, docs/widgets/services/index.md, mkdocs.yml, public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/argocd/component.jsx, src/widgets/argocd/widget.js, src/widgets/components.js, src/widgets/prometheusmetric/component.jsx, src/widgets/widgets.js
This adds a widget for [ArgoCD](https://argo-cd.readthedocs.io/en/latest/). It can list the count of apps present in an ArgoCD instance by app status, e.g. `synced` or `healthy`.
Closes #2644
=> Feature: Add ArgoCD widget

docs/widgets/services/gitlab.md, docs/widgets/services/index.md, mkdocs.yml, public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/gitlab/component.jsx, src/widgets/gitlab/widget.js, src/widgets/widgets.js
This adds a widget for [Gitlab](https://gitlab.com). It is able to list the amount of `events` as well as the open `issues` and open `merge requests`
Closes #3406
=> Feature: gitlab service widget

docs/configs/kubernetes.md
Improves the documentation for the `gethomepage.dev/pod-selector` annotation on the automatic service discovery page. There's at least two discussions about this resulting in `NOT FOUND` on the service health icon, so this explains why that's happening and how to fix it.
Discussions:
- https://github.com/gethomepage/homepage/discussions/3781
- https://github.com/gethomepage/homepage/discussions/4297
=> Documentation: additional explainer for the pod-selector

docs/installation/k8s.md, docs/widgets/info/resources.md, src/components/widgets/resources/network.jsx, src/components/widgets/resources/resources.jsx, src/components/widgets/widget/resource.jsx, src/pages/api/widgets/resources.js
upd: Docs updated for network usage.
add: Widget resorce iconChildren param added.
upd: config file default options added.
upd: resources units type added.
Closes #3421 (Discussion)
=> Enhancement: resources network widget

docs/widgets/info/unifi_controller.md, docs/widgets/services/unifi-controller.md
Found missing admonition types in both of the UDM docs, set them to type: _warning_
Closes # none
=> Documentation: Added missing admonition type

docs/configs/settings.md, src/components/bookmarks/group.jsx, src/components/bookmarks/item.jsx, src/components/bookmarks/list.jsx, src/pages/index.jsx
Closes https://github.com/gethomepage/homepage/discussions/4294
=> Enhancement: icons-only bookmarks style

docs/widgets/services/qbittorrent.md, src/utils/config/service-helpers.js, src/widgets/qbittorrent/component.jsx
This change adds a flag `enableLeechProgress` to the qbittorrent widget. It will show the progress of leech/s as shown in the screenshot. It also shows the status/state of the leech as well as the ETA. 
Closes #4374
=> Enhancement: downloading torrents list for qbittorrent 

docs/widgets/services/esphome.md, src/utils/proxy/handlers/credentialed.js
This adds support for using basic auth credentials to access the ESPHome dashboard statistics from ESPHome 2025.1.0.
Related ESPHome PR https://github.com/esphome/esphome/pull/7965
Closes #3488
=> Enhancement: add basic auth to ESPHome widget

docs/widgets/services/deluge.md, src/utils/config/service-helpers.js, src/widgets/deluge/component.jsx, src/widgets/deluge/proxy.js
This change adds a flag enableLeechProgress to the deluge widget. It will show the progress of leech/s as shown in the screenshot. It also shows the status/state of the leech as well as the ETA.
=> Enhancement: downloading torrents list for deluge

docs/widgets/services/beszel.md, src/utils/config/service-helpers.js, src/widgets/beszel/proxy.js, src/widgets/beszel/widget.js
=> Enhancement: beszel widget compatibility with v0.9.0

src/components/services/group.jsx
See https://github.com/gethomepage/homepage/pull/4346#issuecomment-2558606939
=> Tweak: remove extra padding for nested groups

src/components/services/item.jsx
=> Fix: fix search overlay behind status indicators in 0.10.x

src/widgets/beszel/component.jsx, src/widgets/beszel/proxy.js
=> Enhancement: Better handle some beszel errors

src/components/bookmarks/group.jsx, src/components/bookmarks/list.jsx
=> Fix: correct iconsOnly bookmark group spacing

docs/widgets/services/customapi.md, src/widgets/customapi/component.jsx
This PR adds a `duration` format to the customapi widget. This allows formatting durations (in seconds) in to a more human-readable format, e.g. `1h20m` instead of `4,850`.
=> Enhancement: add duration format to customapi widget

src/pages/index.jsx
Fix for quick launch not showing nested services.
The issue can be reproduced with the following `services.yaml`, and then searching for "c" only shows `NonNestedCalendar`.
```yaml
- NonNested:
- NonNestedCalendar:
href: http://google.com
widget:
type: calendar
- NestedParent:
- Nested:
- NestedCalendar:
href: http://google.com
widget:
type: calendar
- NestedNestedParent:
- Nested1:
- Nested2:
- DoubleyNestedCalendar:
href: http://google.com
widget:
type: calendar
- NestedNestedNestedParent:
- NestedNestedParent:
- Nested1:
- Nested2:
- FullyNestedCalendar:
href: http://google.com
widget:
type: calendar
```
After this fix, searching for "c" finds both the non nested and all the nested services:
=> Fix: quick launch not showing  nested services

docs/configs/services.md, src/components/resolvedicon.jsx
Info: https://github.com/homarr-labs/dashboard-icons/discussions/797#discussioncomment-11736264.
_Note: The walkxcode/dashboard-icons repository will continue to function indefinitely but may no longer receive updates._
=> Chore: migrate dashboard-icons to homarr-labs

docs/widgets/services/unifi-controller.md
When users who have API errors in Unifi make changes, the cache is not cleared automatically.  This is covered in the documentation for Docker users, but not for non-Docker users.  This is a minor documentation change to add a hint for non-docker users to try restarting the service. 
Closes # N/A
=> Documentation: add note about clearing UniFi cache non-docker

src/styles/globals.css
=> Fix: fix overlap with glances charts in multi-widgets

src/widgets/calendar/event.jsx, src/widgets/calendar/monthly.jsx
If Sonarr/Radarr/Lidarr and the Homepage instance are running in separate timezone configurations, then the calendar in Monthly view will show blank due to an error in time comparisons of the two systems.
Current mainline version of this comparison compares the Unix Timestamp of the beginning of the day, which will differ from two same days in different timezones.  This PR changes is to compare the ISO Datestring instead (removing Time).
Closes # (no issue filed)
=> Fix: Timezone-aware Date comparison for Calendar integration

src/widgets/gamedig/proxy.js
gamedig's default value to get the number of players in a game **has changed to be** `numplayers`. No longer `players` - which is not always present, and which homepage currently uses. Initially, I thought it was an issue with gamedig, but it was a conscious choice. See: https://github.com/gamedig/node-gamedig/pull/676
>players is only present if gamedig knows details (like names) about specific players, and numplayers is always present.
This change breaks current instances of homepage gamedig widgets, one example being mumble (mumbleping protocol, the one without using a murmur plugin). Another being Minecraft Bedrock edition.
Further information:
* https://github.com/search?q=repo%3Agamedig%2Fnode-gamedig%20numplayers&type=code
* …
=> Enhancement: support gamedig numplayers

docs/configs/docker.md
Fix incorrect documentation for using multiple widgets in docker tags. Need to use `widgets` instead of `widget`.
=> Documentation: correct documentation for multiple widgets in docker labels

src/widgets/gamedig/proxy.js
Ensure gamedig's priority is for `numplayers` rather than `players.length` (See code change).
For some games, `players` returns `[]`, even when `numplayers` returns 5, for example.
```
you@yourmachine:~$ npx gamedig@5.2.0 --type mumble <mumbleserverhost> --debug | tail
},
"version": "1.5.255",
"maxplayers": 25,
"numplayers": 2,
"players": [],
"bots": [],
"queryPort": 64738,
"connect": "<mumbleserverhost>:64738",
"ping": 13
}
```
Because `players` is checked first, this returns `0`, rather than the correct `2`.
Previously `numplayers` worked when I had tested in my original PR https://github.com/gethomepage/homepage/pull/4760, but as you suggested, including the older `players?.length` is better. I did not test then - mea culpa - having assumed `players` would be null rather than an empty …
=> Enhancement: Improve gamedig player number estimate

docs/widgets/services/fritzbox.md, public/locales/en/common.json, src/widgets/fritzbox/component.jsx, src/widgets/fritzbox/proxy.js
This PR adds an ability to display external IPv6 address and/or IPv6-Prefix in the FritzBox widget.
Currently, the widget returns an empty IP address, because there is no IPv4 address assigned by my internet provider. Instead they provide me with an IPv6 subnet.
Unfortunately, the UPnP action is prefixed with `X_AVM_DE_` which might seem like an unstable option. However, there are already values prefixed with `NewX_AVM_DE_` used in the file (as per https://github.com/gethomepage/homepage/discussions/1213) and it seems to be even older, yet still present in my router.
I added an option for both, address and prefix, however, IMHO prefix is sufficient, because `::1` has only the router itself and all the clients (NAS, Raspberry Pi, Home server, etc.) will have a different IP address with a …
=> Fixhancement: add an option to fritzbox widget to display IPv6

docs/widgets/services/peanut.md
This is a simple documentation change to show users that the homepage PeaNUT widget can accept authentication.
=> Documentation: add auth documentation to PeaNUT

src/widgets/glances/metrics/containers.jsx
=> Fix: subtract inactive_file from glances container memory usage

docs/widgets/services/romm.md
The `/api/stats` endpoint doesn't require authentication, so we can remove `username` and `password` from the docs.
=> Documentation: remove auth info from romm widget

package-lock.json, package.json, pnpm-lock.yaml, postcss.config.js, src/components/bookmarks/group.jsx, src/components/bookmarks/item.jsx, src/components/quicklaunch.jsx, src/components/services/dropdown.jsx, src/components/services/group.jsx, src/components/services/item.jsx, src/components/services/widget.jsx, src/components/services/widget/block.jsx, src/components/services/widget/error.jsx, src/components/toggles/color.jsx, src/components/widgets/search/search.jsx, src/components/widgets/stocks/stocks.jsx, src/components/widgets/widget/container.jsx, src/pages/index.jsx, src/styles/globals.css, src/widgets/calendar/event.jsx, src/widgets/calendar/monthly.jsx, src/widgets/coinmarketcap/component.jsx, src/widgets/customapi/component.jsx, src/widgets/glances/metrics/fs.jsx, src/widgets/glances/metrics/info.jsx, src/widgets/iframe/component.jsx, src/widgets/stocks/component.jsx, src/widgets/truenas/pool.jsx
=> Chore: upgrade to tailwind v4

src/utils/kubernetes/httproute-list.js
The Kubernetes integration was only returning a single `HTTPRoute` per namespace due to array destructuring in the `listHttpRoute` function. This limited the service discovery capabilities for users with multiple HTTPRoutes in the same namespace.
I don't quite understand why it was limited to one `HTTPRoute` per namespace, as it's certainly interesting to have multiple `HTTPRoute` in the same namespace, on one or more `Gateway`, and thus exposing multiple services on the Homepage. As a result, I have flagged this as a bug.
=> Fix: return all http routes of a namespace (k8s)

src/widgets/diskstation/component.jsx
=> Fix: use 'real_usage' for synology diskstation memory stats

docs/widgets/services/komga.md, src/widgets/speedtest/component.jsx
=> Fix: correct units for speedtest tracker API v2

src/widgets/emby/component.jsx
=> Fix: jellyfin handle empty episode numbers

docs/installation/k8s.md
The goal of this PR is to add the newly required `HOMEPAGE_ALLOWED_HOSTS` environment variable to the kubernetes installation page. Specifically, the deployment manifest example.
=> Documentation: add HOMEPAGE_ALLOWED_HOSTS to k8s docs

docs/configs/kubernetes.md, k3d/k3d-helm-values.yaml, src/utils/kubernetes/ingress-list.js
@djeinstine @dudo sorry to keep bothering you guys, but now that I can run a little k3d cluster I was able to look at this, I was considering making `ingress: true` the default (aka not make 1.0 changes breaking). I believe this change will do it but the question is whether this will have other effects?
Thanks again for all your help
=> Change: re-enable k8s ingress by default

docs/configs/settings.md, src/components/services/group.jsx, src/pages/_app.jsx, src/pages/index.jsx
Adds `maxGroupColumns` and gracefully deprecate `fiveColumns` (the worst)
=> Enhancement: support maximum group cols up 8

docs/widgets/services/gitea.md, public/locales/en/common.json, src/widgets/gitea/component.jsx, src/widgets/gitea/widget.js
Hey i know Gitea is already present, but it only tracks notifications, issues & pulls, this PR adds repositories also
[(Closed Issue)](https://github.com/gethomepage/homepage/discussions/3614)
There was a prevous PR https://github.com/gethomepage/homepage/pull/3615
=> Enhancement: Add Repositories field to Gitea

src/widgets/customapi/component.jsx
Support SHVL syntax on dynamic list target templating
There is no way to access nested fields on dynamic lists `target` field
```
target: https://example.com/{subject.id}
```
=> Fix: support shvl on customapi dynamic list target

src/widgets/hoarder/widget.js
Removes the `asJson` import. It was there because I did use it in an older version of the widget.
=> Fix: remove unneeded import from Hoarder widget.js

src/components/widgets/longhorn/longhorn.jsx
The logic was falling to the final `return true` rather than breaking the logic chain when the node.id was matched to `"total"` and return false.
Fixes where the `widgets.yaml` configuration includes:
```
- longhorn:
total: false
nodes: true
```
Still shows a `total` node.
Bug-fix
=> Fix: Longhorn still showing Total despite `total: false`

src/pages/api/kubernetes/stats/[...service].js
After upgrading to v1, I noticed that my Kubernetes widgets were reporting invalid statistics:
This clearly can't be correct, since `kubectl top` reports that it only uses about 1.5gb of memory:
```
NAME                                                     CPU(cores)   MEMORY(bytes)
...
prometheus-grafana-0                                     19m          384Mi
prometheus-kube-prometheus-operator-796b68b4c-qjswh      1m           35Mi
prometheus-kube-state-metrics-c44f8f948-r7mvd            4m           58Mi
prometheus-prometheus-kube-prometheus-prometheus-0       290m         1294Mi
prometheus-prometheus-node-exporter-bnzs7                1m           17Mi
prometheus-prometheus-node-exporter-gr6h6                1m           15Mi
prometheus-prometheus-node-exporter-wsss6                1m …
```
=> Fix: kubernetes statistics not respecting selector

docs/widgets/services/customapi.md, src/widgets/customapi/component.jsx
This adds the capability to format the label in dynamic-list for the customapi widget. The options are the ones already available : `text`, `number`, `float`, `percent`, `duration`, `bytes`, `bitrate`, `size`, `date` and `relativeDate`.  
There wasn't an open specific feature request for this but I figured I must not be the only one who wants this since I noticed interest in comments of this one : https://github.com/gethomepage/homepage/discussions/4906#discussioncomment-12819608.  
I was going to make it for myself anyways so I thought I might as well share it. I know it isn't technically allowed in the guidelines to not have a linked feature request, so feel free to reject this PR for this reason.
I chose to parse the `format` parameter at the same level as `label` to keep it consistent …
=> Enhancement: add label formatting for dynamic-list customapi widget

docs/widgets/services/jellystat.md, public/locales/en/common.json, src/utils/config/service-helpers.js, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/jellystat/component.jsx, src/widgets/jellystat/widget.js, src/widgets/widgets.js
Implements #1333
This widget shows the playback count from user-specified libraries in the last `n` days.
It uses the API endpoint `http://jellystat.host.or.ip/stats/getViewsByLibraryType` implemented in [v1.1.16](https://github.com/CyferShepard/Jellystat/releases/tag/1.1.6)
- [GitHub](https://github.com/CyferShepard/Jellystat)
- [Docker Hub](https://hub.docker.com/r/cyfershepard/jellystat)
Generate an API key (http://jellystat.host.or.ip/settings)
Add this to `services.yaml`
```yml
- Dev:
- Jellystat:
href: http://jellystat.host.or.ip
widget:
type: jellystat
url: http://jellystat.host.or.ip
key: apikeyapikeyapikeyapikeyapikeyapikeyapikeyapikeyapikeyapikey
fields: ["songs", "movies", "episodes", "other"]
days: 30
```
=> Feature: Jellystat widget

docs/widgets/services/proxmoxbackupserver.md
Update Proxmox Backup Server documentation to add the new field introduced in https://github.com/gethomepage/homepage/pull/4614
=> Documentation: add data store option to PBS widget

docs/widgets/services/gluetun.md, public/locales/en/common.json, src/widgets/gluetun/component.jsx, src/widgets/gluetun/widget.js
Adds a fourth field block displaying the server side port  being forwarded. 
This information is useful to have at glance on your homepage as some vpn services don't assign a static forwarded port. For p2p services such as BitTorrent in order to be connectable you will need to configure and continually keep this port updated.
Closes #4576
=> Enhancement: Add port_forwarded field to Gluetun widget

src/widgets/beszel/proxy.js
Should fix #5146 and https://github.com/henrygd/beszel/issues/824
Issue is related to https://github.com/pocketbase/pocketbase/discussions/1570 - the API response is always 200 status even after the token expires.
1. Switch on the ability to edit collections in Beszel / PocketBase at `/_/#/settings`
2. In PocketBase, go to Collections > _superusers (expand "system") > Edit collection (cog icon at top)
3. Switch to the Options tab and expand Token Options at the bottom
4. Change "Auth duration" to `30`
5. Start homepage and observe that systems populate
6. Wait 30 seconds for token to expire and refresh, observe that systems do not populate
Let me know if have any questions about this. :+1:
=> Fix: refresh beszel token if empty list is returned

docs/widgets/services/trilium.md, public/locales/en/common.json, src/utils/proxy/handlers/credentialed.js, src/widgets/components.js, src/widgets/trilium/component.jsx, src/widgets/trilium/widget.js, src/widgets/widgets.js
Relevant discussion: https://github.com/gethomepage/homepage/discussions/2312
This adds the Trilium service widget to Homepage. This will fetch the current Trilium version, number of Notes, and number of Attachments from a user's instance and show them the above information:
Included in the PR is of course the code, but also the documentation for using it. Please feel free to let me know if you would like me to change anything.
=> Feature: Trilium Service widget

src/widgets/glances/metrics/process.jsx
resident set size, seems more consistent with what glances shows too:
=> Change: use glaces rss instead of data for process memory reporting

src/widgets/qbittorrent/component.jsx
The qBittorrent widget's leech progress list is a very nice feature, but its disordered nature makes it difficult to quickly parse (for me at least). This change sorts the list in the following order:
1. downloading
2. forcedDL
3. metaDL
4. forcedMetaDL
5. checkingDL
6. stalledDL
7. queuedDL
8. pausedDL
when any entry has the same status, e.g multiple torrents actively downloading, they will be sorted by progress (highest % done first).
https://github.com/gethomepage/homepage/discussions/5222
=> Enhancement: sort qBittorrent leechProgress

docs/widgets/services/grafana.md, src/utils/config/service-helpers.js, src/widgets/grafana/component.jsx, src/widgets/grafana/widget.js
This PR leaves the existing legacy `alerts` API call unchanged and adds support for querying both Grafana's `grafana-alerting` data source and the `alertmanager` data source so that firing alerts from either source will be displayed.
I have opened a discussion here: https://github.com/gethomepage/homepage/discussions/5475
=> Enhancement: support for new grafana alerting api

.vscode/settings.json, docs/widgets/services/filebrowser.md, docs/widgets/services/index.md, mkdocs.yml, public/locales/en/common.json, src/widgets/components.js, src/widgets/filebrowser/component.jsx, src/widgets/filebrowser/proxy.js, src/widgets/filebrowser/widget.js, src/widgets/widgets.js
Filebrowser requires a token for each API request. This will be generated automatically from the username and password using `https://{hostname}/api/login`. It returns the token as a string. The token will then be used for `https://{hostname}/api/usage` to get the usage `used` and `total`. This endpoints returns a dictionary like this:
```json
{
"total": 15875321102336,
"used": 8775814610944
}
```
This widget will show `used`, `total` and `available`(calculated from `total`-`used`).
Closes #4400
=> Feature: Filebrowser service widget

src/widgets/uptimerobot/component.jsx
*Note: reupload without the useWidgetAPI changes for POST requests*
Currently the UptimeRobot widget will show raw errors whenever the API is rate limiting our requests. Their rate limiting happens quite frequently, refreshing the page 3-5 times is enough to trigger it reliably.
This fixes the error handling to show it as intended:
=> Fix: properly handle UptimeRobot errors

docs/widgets/services/index.md, mkdocs.yml
Since my PR #5562 for Wallos service widget has been shipped, I've noticed the documentation link is **missing** from the website's documentation index and sidebar. However, I can access the page by navigating to https://gethomepage.dev/widgets/services/wallos/:
I've reviewed some other widgets' PRs and files, and I think the two files I've modified are what's required for the fix. But please correct me if more are missing.
=> Documentation: fix missing references to Wallos documentation doc

src/widgets/evcc/component.jsx
Currently the evcc widget is only providing the current charge_Power of the first evcc loadpoint only. In case a evcc user configured more than one loadpoint (like me), charge_power is not reflecting it.
With PR the chargePower sum of all loadpoints will be shown by the evcc widget.
Refer to feature request #5648.
=> Enhancement: summarize charge power of all loadpoints in evcc widget
